# Format: (attname, struct str, seek offset (from beggining of file),
#          type==TupleType, default value)

NIFTI_header_atts = []
NIFTI_header_atts.append(('sizeof_hdr', 'i', False, 348))
NIFTI_header_atts.append(('data_type', '10s', False, ' '*10))
NIFTI_header_atts.append(('db_name', '18s', False, ' '*18))
NIFTI_header_atts.append(('extents', 'i', False, 0))
NIFTI_header_atts.append(('session_error', 'h', False, 0))
NIFTI_header_atts.append(('regular', 's', False, 'r'))
NIFTI_header_atts.append(('dim_info', 'b', False, 0))
NIFTI_header_atts.append(('dim', '8h', True, (4,1,1,1,1) + (0,)*3))
NIFTI_header_atts.append(('intent_p1', 'f', False, 0.))
NIFTI_header_atts.append(('intent_p2', 'f', False, 0.))
NIFTI_header_atts.append(('intent_p3', 'f', False, 0.))
NIFTI_header_atts.append(('intent_code', 'h', False, 0))
NIFTI_header_atts.append(('datatype','h', False, 0))
NIFTI_header_atts.append(('bitpix','h', False, 0))
NIFTI_header_atts.append(('slice_start','h', False, 0))
NIFTI_header_atts.append(('pixdim','8f', True, (1.,) + (0.,)*7))
NIFTI_header_atts.append(('vox_offset','f', False, 0))
NIFTI_header_atts.append(('scl_slope','f', False, 1.0))
NIFTI_header_atts.append(('scl_inter','f', False, 0.))
NIFTI_header_atts.append(('slice_end','h', False, 0))
NIFTI_header_atts.append(('slice_code','b', False, 0))
NIFTI_header_atts.append(('xyzt_units','b', False, 0))
NIFTI_header_atts.append(('cal_max','f', False, 0))
NIFTI_header_atts.append(('cal_min','f', False, 0))
NIFTI_header_atts.append(('slice_duration','f', False, 0))
NIFTI_header_atts.append(('toffset','f', False, 0))
NIFTI_header_atts.append(('glmax','i', False, 0))
NIFTI_header_atts.append(('glmin','i', False, 0))
NIFTI_header_atts.append(('descrip','80s', False, ' '*80))
NIFTI_header_atts.append(('aux_file','24s', False, ' '*24))
NIFTI_header_atts.append(('qform_code','h', False, 0))
NIFTI_header_atts.append(('sform_code','h', False, 0))
NIFTI_header_atts.append(('quatern_b','f', False, 0.0))
NIFTI_header_atts.append(('quatern_c','f', False, 0.))
NIFTI_header_atts.append(('quatern_d','f', False, 0.))
NIFTI_header_atts.append(('qoffset_x','f', False, 0.))
NIFTI_header_atts.append(('qoffset_y','f', False, 0.))
NIFTI_header_atts.append(('qoffset_z','f', False, 0.))
NIFTI_header_atts.append(('srow_x','4f', True, [0.,0.,1.,0.]))
NIFTI_header_atts.append(('srow_y','4f', True, [0.,1.,0.,0.]))
NIFTI_header_atts.append(('srow_z','4f', True, [1.,0.,0.,0.]))
NIFTI_header_atts.append(('intent_name','16s', False, ' '*16))
NIFTI_header_atts.append(('magic','4s', False, 'ni1\0'))

NIFTI_header_dict = {}
for att in NIFTI_header_atts:
    NIFTI_header_dict[att[0]] = att[1:]

