/* Generated by Cython 0.10.3 on Wed Mar 04 23:09:14 2009 */

#define PY_SSIZE_T_CLEAN
#include "Python.h"
#include "structmember.h"
#ifndef PY_LONG_LONG
  #define PY_LONG_LONG LONG_LONG
#endif
#ifndef DL_EXPORT
  #define DL_EXPORT(t) t
#endif
#if PY_VERSION_HEX < 0x02040000
  #define METH_COEXIST 0
#endif
#if PY_VERSION_HEX < 0x02050000
  typedef int Py_ssize_t;
  #define PY_SSIZE_T_MAX INT_MAX
  #define PY_SSIZE_T_MIN INT_MIN
  #define PyInt_FromSsize_t(z) PyInt_FromLong(z)
  #define PyInt_AsSsize_t(o)   PyInt_AsLong(o)
  #define PyNumber_Index(o)    PyNumber_Int(o)
  #define PyIndex_Check(o)     PyNumber_Check(o)
#endif
#if PY_VERSION_HEX < 0x02060000
  #define Py_REFCNT(ob) (((PyObject*)(ob))->ob_refcnt)
  #define Py_TYPE(ob)   (((PyObject*)(ob))->ob_type)
  #define Py_SIZE(ob)   (((PyVarObject*)(ob))->ob_size)
  #define PyVarObject_HEAD_INIT(type, size) \
          PyObject_HEAD_INIT(type) size,
  #define PyType_Modified(t)

  typedef struct {
       void *buf;
       PyObject *obj;
       Py_ssize_t len;
       Py_ssize_t itemsize;
       int readonly;
       int ndim;
       char *format;
       Py_ssize_t *shape;
       Py_ssize_t *strides;
       Py_ssize_t *suboffsets;
       void *internal;
  } Py_buffer;

  #define PyBUF_SIMPLE 0
  #define PyBUF_WRITABLE 0x0001
  #define PyBUF_LOCK 0x0002
  #define PyBUF_FORMAT 0x0004
  #define PyBUF_ND 0x0008
  #define PyBUF_STRIDES (0x0010 | PyBUF_ND)
  #define PyBUF_C_CONTIGUOUS (0x0020 | PyBUF_STRIDES)
  #define PyBUF_F_CONTIGUOUS (0x0040 | PyBUF_STRIDES)
  #define PyBUF_ANY_CONTIGUOUS (0x0080 | PyBUF_STRIDES)
  #define PyBUF_INDIRECT (0x0100 | PyBUF_STRIDES)

#endif
#if PY_MAJOR_VERSION < 3
  #define __Pyx_BUILTIN_MODULE_NAME "__builtin__"
#else
  #define __Pyx_BUILTIN_MODULE_NAME "builtins"
#endif
#if PY_MAJOR_VERSION >= 3
  #define Py_TPFLAGS_CHECKTYPES 0
  #define Py_TPFLAGS_HAVE_INDEX 0
#endif
#if (PY_VERSION_HEX < 0x02060000) || (PY_MAJOR_VERSION >= 3)
  #define Py_TPFLAGS_HAVE_NEWBUFFER 0
#endif
#if PY_MAJOR_VERSION >= 3
  #define PyBaseString_Type            PyUnicode_Type
  #define PyString_Type                PyBytes_Type
  #define PyInt_Type                   PyLong_Type
  #define PyInt_Check(op)              PyLong_Check(op)
  #define PyInt_CheckExact(op)         PyLong_CheckExact(op)
  #define PyInt_FromString             PyLong_FromString
  #define PyInt_FromUnicode            PyLong_FromUnicode
  #define PyInt_FromLong               PyLong_FromLong
  #define PyInt_FromSize_t             PyLong_FromSize_t
  #define PyInt_FromSsize_t            PyLong_FromSsize_t
  #define PyInt_AsLong                 PyLong_AsLong
  #define PyInt_AS_LONG                PyLong_AS_LONG
  #define PyInt_AsSsize_t              PyLong_AsSsize_t
  #define PyInt_AsUnsignedLongMask     PyLong_AsUnsignedLongMask
  #define PyInt_AsUnsignedLongLongMask PyLong_AsUnsignedLongLongMask
  #define __Pyx_PyNumber_Divide(x,y)         PyNumber_TrueDivide(x,y)
#else
  #define __Pyx_PyNumber_Divide(x,y)         PyNumber_Divide(x,y)
  #define PyBytes_Type                 PyString_Type
#endif
#if PY_MAJOR_VERSION >= 3
  #define PyMethod_New(func, self, klass) PyInstanceMethod_New(func)
#endif
#if !defined(WIN32) && !defined(MS_WINDOWS)
  #ifndef __stdcall
    #define __stdcall
  #endif
  #ifndef __cdecl
    #define __cdecl
  #endif
#else
  #define _USE_MATH_DEFINES
#endif
#ifdef __cplusplus
#define __PYX_EXTERN_C extern "C"
#else
#define __PYX_EXTERN_C extern
#endif
#include <math.h>
#define __PYX_HAVE_API__fff2__bindings__wrapper
#include "numpy/arrayobject.h"
#include "fff_base.h"
#include "fff_vector.h"
#include "fff_matrix.h"
#include "fff_array.h"
#include "randomkit.h"
#include "fffpy.h"


#ifdef __GNUC__
#define INLINE __inline__
#elif _WIN32
#define INLINE __inline
#else
#define INLINE 
#endif

typedef struct {PyObject **p; char *s; long n; char is_unicode; char intern; char is_identifier;} __Pyx_StringTabEntry; /*proto*/



static int __pyx_skip_dispatch = 0;


/* Type Conversion Predeclarations */

#if PY_MAJOR_VERSION < 3
#define __Pyx_PyBytes_FromString PyString_FromString
#define __Pyx_PyBytes_AsString   PyString_AsString
#else
#define __Pyx_PyBytes_FromString PyBytes_FromString
#define __Pyx_PyBytes_AsString   PyBytes_AsString
#endif

#define __Pyx_PyBool_FromLong(b) ((b) ? (Py_INCREF(Py_True), Py_True) : (Py_INCREF(Py_False), Py_False))
static INLINE int __Pyx_PyObject_IsTrue(PyObject* x);
static INLINE PY_LONG_LONG __pyx_PyInt_AsLongLong(PyObject* x);
static INLINE unsigned PY_LONG_LONG __pyx_PyInt_AsUnsignedLongLong(PyObject* x);
static INLINE Py_ssize_t __pyx_PyIndex_AsSsize_t(PyObject* b);

#define __pyx_PyInt_AsLong(x) (PyInt_CheckExact(x) ? PyInt_AS_LONG(x) : PyInt_AsLong(x))
#define __pyx_PyFloat_AsDouble(x) (PyFloat_CheckExact(x) ? PyFloat_AS_DOUBLE(x) : PyFloat_AsDouble(x))

static INLINE unsigned char __pyx_PyInt_unsigned_char(PyObject* x);
static INLINE unsigned short __pyx_PyInt_unsigned_short(PyObject* x);
static INLINE char __pyx_PyInt_char(PyObject* x);
static INLINE short __pyx_PyInt_short(PyObject* x);
static INLINE int __pyx_PyInt_int(PyObject* x);
static INLINE long __pyx_PyInt_long(PyObject* x);
static INLINE signed char __pyx_PyInt_signed_char(PyObject* x);
static INLINE signed short __pyx_PyInt_signed_short(PyObject* x);
static INLINE signed int __pyx_PyInt_signed_int(PyObject* x);
static INLINE signed long __pyx_PyInt_signed_long(PyObject* x);
static INLINE long double __pyx_PyInt_long_double(PyObject* x);
#ifdef __GNUC__
/* Test for GCC > 2.95 */
#if __GNUC__ > 2 ||               (__GNUC__ == 2 && (__GNUC_MINOR__ > 95)) 
#define likely(x)   __builtin_expect(!!(x), 1)
#define unlikely(x) __builtin_expect(!!(x), 0)
#else /* __GNUC__ > 2 ... */
#define likely(x)   (x)
#define unlikely(x) (x)
#endif /* __GNUC__ > 2 ... */
#else /* __GNUC__ */
#define likely(x)   (x)
#define unlikely(x) (x)
#endif /* __GNUC__ */
    
static PyObject *__pyx_m;
static PyObject *__pyx_b;
static PyObject *__pyx_empty_tuple;
static int __pyx_lineno;
static int __pyx_clineno = 0;
static const char * __pyx_cfilenm= __FILE__;
static const char *__pyx_filename;
static const char **__pyx_f;

static char __pyx_mdoc[] = "\nIterators for testing. \nAuthor: Alexis Roche, 2009.\n";

static void __Pyx_RaiseDoubleKeywordsError(
    const char* func_name, PyObject* kw_name); /*proto*/

static void __Pyx_RaiseArgtupleInvalid(const char* func_name, int exact,
    Py_ssize_t num_min, Py_ssize_t num_max, Py_ssize_t num_found); /*proto*/

static int __Pyx_ParseOptionalKeywords(PyObject *kwds, PyObject **argnames[],     PyObject *kwds2, PyObject *values[], Py_ssize_t num_pos_args,     const char* function_name); /*proto*/

static INLINE int __Pyx_SetItemInt(PyObject *o, Py_ssize_t i, PyObject *v, int is_unsigned) {
    int r;
    if (PyList_CheckExact(o) && 0 <= i && i < PyList_GET_SIZE(o)) {
        Py_DECREF(PyList_GET_ITEM(o, i));
        Py_INCREF(v);
        PyList_SET_ITEM(o, i, v);
        return 1;
    }
    else if (Py_TYPE(o)->tp_as_sequence && Py_TYPE(o)->tp_as_sequence->sq_ass_item && (likely(i >= 0) || !is_unsigned))
        r = PySequence_SetItem(o, i, v);
    else {
        PyObject *j = (likely(i >= 0) || !is_unsigned) ? PyInt_FromLong(i) : PyLong_FromUnsignedLongLong((sizeof(unsigned long long) > sizeof(Py_ssize_t) ? (1ULL << (sizeof(Py_ssize_t)*8)) : 0) + i);
        if (!j)
            return -1;
        r = PyObject_SetItem(o, j, v);
        Py_DECREF(j);
    }
    return r;
}

static int __Pyx_ArgTypeTest(PyObject *obj, PyTypeObject *type, int none_allowed,
    const char *name, int exact); /*proto*/

static PyObject *__Pyx_Import(PyObject *name, PyObject *from_list); /*proto*/

static PyObject *__Pyx_GetName(PyObject *dict, PyObject *name); /*proto*/

static PyTypeObject *__Pyx_ImportType(const char *module_name, const char *class_name, long size);  /*proto*/

static PyObject *__Pyx_ImportModule(const char *name); /*proto*/

static void __Pyx_AddTraceback(const char *funcname); /*proto*/

static int __Pyx_InitStrings(__Pyx_StringTabEntry *t); /*proto*/

/* Type declarations */

typedef unsigned long __pyx_t_4fff2_8bindings_7wrapper_size_t;
/* Module declarations from numpy */

/* Module declarations from fff2.bindings.wrapper */

static PyTypeObject *__pyx_ptype_4fff2_8bindings_7wrapper_dtype = 0;
static PyTypeObject *__pyx_ptype_4fff2_8bindings_7wrapper_ndarray = 0;
static PyTypeObject *__pyx_ptype_4fff2_8bindings_7wrapper_flatiter = 0;
static PyTypeObject *__pyx_ptype_4fff2_8bindings_7wrapper_broadcast = 0;


/* Implementation of fff2.bindings.wrapper */
static char __pyx_k_1[] = "0.1";
static char __pyx_k_2[] = "unknown type";
static char __pyx_k_3[] = "unsigned char";
static char __pyx_k_4[] = "signed char";
static char __pyx_k_5[] = "unsigned short";
static char __pyx_k_6[] = "signed short";
static char __pyx_k_8[] = "unsigned int";
static char __pyx_k_9[] = "unsigned long";
static PyObject *__pyx_int_1;
static char __pyx_k_T[] = "T";
static PyObject *__pyx_kp_T;
static char __pyx_k_X[] = "X";
static PyObject *__pyx_kp_X;
static char __pyx_k_flag[] = "flag";
static PyObject *__pyx_kp_flag;
static char __pyx_k_axis[] = "axis";
static PyObject *__pyx_kp_axis;
static char __pyx_k_niters[] = "niters";
static PyObject *__pyx_kp_niters;
static char __pyx_k_Y[] = "Y";
static PyObject *__pyx_kp_Y;
static char __pyx_k___version__[] = "__version__";
static PyObject *__pyx_kp___version__;
static char __pyx_k_numpy[] = "numpy";
static PyObject *__pyx_kp_numpy;
static char __pyx_k_np[] = "np";
static PyObject *__pyx_kp_np;
static char __pyx_k_7[] = "int";
static PyObject *__pyx_kp_7;
static char __pyx_k_10[] = "long";
static PyObject *__pyx_kp_10;
static char __pyx_k_11[] = "float";
static PyObject *__pyx_kp_11;
static char __pyx_k_12[] = "double";
static PyObject *__pyx_kp_12;
static char __pyx_k_c_types[] = "c_types";
static PyObject *__pyx_kp_c_types;
static char __pyx_k_fff_types[] = "fff_types";
static PyObject *__pyx_kp_fff_types;
static char __pyx_k_npy_types[] = "npy_types";
static PyObject *__pyx_kp_npy_types;
static char __pyx_k_index[] = "index";
static PyObject *__pyx_kp_index;
static char __pyx_k_copy[] = "copy";
static PyObject *__pyx_kp_copy;
static char __pyx_k_zeros[] = "zeros";
static PyObject *__pyx_kp_zeros;
static char __pyx_k_shape[] = "shape";
static PyObject *__pyx_kp_shape;
static char __pyx_k_squeeze[] = "squeeze";
static PyObject *__pyx_kp_squeeze;
static PyObject *__pyx_kp_1;
static PyObject *__pyx_kp_2;
static PyObject *__pyx_kp_3;
static PyObject *__pyx_kp_4;
static PyObject *__pyx_kp_5;
static PyObject *__pyx_kp_6;
static PyObject *__pyx_kp_8;
static PyObject *__pyx_kp_9;

/* "d:\home\ar203069\bzr\nipy\fff2\fff2\bindings\wrapper.pyx":31
 * 
 * 
 * def fff_type(dtype T):             # <<<<<<<<<<<<<<
 *     """
 *     fff_t, nbytes = fff_type(T)
 */

static PyObject *__pyx_pf_4fff2_8bindings_7wrapper_fff_type(PyObject *__pyx_self, PyObject *__pyx_v_T); /*proto*/
static char __pyx_doc_4fff2_8bindings_7wrapper_fff_type[] = "\n    fff_t, nbytes = fff_type(T)\n\n    T is a np.dtype instance. Return a tuple (str, int). \n    ";
static PyObject *__pyx_pf_4fff2_8bindings_7wrapper_fff_type(PyObject *__pyx_self, PyObject *__pyx_v_T) {
  fff_datatype __pyx_v_fff_t;
  unsigned int __pyx_v_nbytes;
  PyObject *__pyx_r;
  PyObject *__pyx_1 = 0;
  PyObject *__pyx_2 = 0;
  PyObject *__pyx_3 = 0;
  PyObject *__pyx_4 = 0;
  __pyx_self = __pyx_self;
  if (unlikely(!__Pyx_ArgTypeTest(((PyObject *)__pyx_v_T), __pyx_ptype_4fff2_8bindings_7wrapper_dtype, 1, "T", 0))) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 31; __pyx_clineno = __LINE__; goto __pyx_L1_error;}

  /* "d:\home\ar203069\bzr\nipy\fff2\fff2\bindings\wrapper.pyx":39
 *     cdef fff_datatype fff_t
 *     cdef unsigned int nbytes
 *     fff_t =  fff_datatype_fromNumPy(T.type_num)             # <<<<<<<<<<<<<<
 *     nbytes =  fff_nbytes(fff_t)
 *     return c_types[fff_types.index(<int>fff_t)], nbytes
 */
  __pyx_v_fff_t = fff_datatype_fromNumPy(((PyArray_Descr *)__pyx_v_T)->type_num);

  /* "d:\home\ar203069\bzr\nipy\fff2\fff2\bindings\wrapper.pyx":40
 *     cdef unsigned int nbytes
 *     fff_t =  fff_datatype_fromNumPy(T.type_num)
 *     nbytes =  fff_nbytes(fff_t)             # <<<<<<<<<<<<<<
 *     return c_types[fff_types.index(<int>fff_t)], nbytes
 * 
 */
  __pyx_v_nbytes = fff_nbytes(__pyx_v_fff_t);

  /* "d:\home\ar203069\bzr\nipy\fff2\fff2\bindings\wrapper.pyx":41
 *     fff_t =  fff_datatype_fromNumPy(T.type_num)
 *     nbytes =  fff_nbytes(fff_t)
 *     return c_types[fff_types.index(<int>fff_t)], nbytes             # <<<<<<<<<<<<<<
 * 
 * 
 */
  __pyx_1 = __Pyx_GetName(__pyx_m, __pyx_kp_c_types); if (unlikely(!__pyx_1)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 41; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
  __pyx_2 = __Pyx_GetName(__pyx_m, __pyx_kp_fff_types); if (unlikely(!__pyx_2)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 41; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
  __pyx_3 = PyObject_GetAttr(__pyx_2, __pyx_kp_index); if (unlikely(!__pyx_3)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 41; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
  Py_DECREF(__pyx_2); __pyx_2 = 0;
  __pyx_2 = PyInt_FromLong(((int)__pyx_v_fff_t)); if (unlikely(!__pyx_2)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 41; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
  __pyx_4 = PyTuple_New(1); if (unlikely(!__pyx_4)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 41; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
  PyTuple_SET_ITEM(__pyx_4, 0, __pyx_2);
  __pyx_2 = 0;
  __pyx_2 = PyObject_Call(__pyx_3, ((PyObject *)__pyx_4), NULL); if (unlikely(!__pyx_2)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 41; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
  Py_DECREF(__pyx_3); __pyx_3 = 0;
  Py_DECREF(((PyObject *)__pyx_4)); __pyx_4 = 0;
  __pyx_3 = PyObject_GetItem(__pyx_1, __pyx_2); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 41; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
  Py_DECREF(__pyx_1); __pyx_1 = 0;
  Py_DECREF(__pyx_2); __pyx_2 = 0;
  __pyx_4 = PyLong_FromUnsignedLong(__pyx_v_nbytes); if (unlikely(!__pyx_4)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 41; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
  __pyx_1 = PyTuple_New(2); if (unlikely(!__pyx_1)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 41; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
  PyTuple_SET_ITEM(__pyx_1, 0, __pyx_3);
  PyTuple_SET_ITEM(__pyx_1, 1, __pyx_4);
  __pyx_3 = 0;
  __pyx_4 = 0;
  __pyx_r = ((PyObject *)__pyx_1);
  __pyx_1 = 0;
  goto __pyx_L0;

  __pyx_r = Py_None; Py_INCREF(Py_None);
  goto __pyx_L0;
  __pyx_L1_error:;
  Py_XDECREF(__pyx_1);
  Py_XDECREF(__pyx_2);
  Py_XDECREF(__pyx_3);
  Py_XDECREF(__pyx_4);
  __Pyx_AddTraceback("fff2.bindings.wrapper.fff_type");
  __pyx_r = NULL;
  __pyx_L0:;
  return __pyx_r;
}

/* "d:\home\ar203069\bzr\nipy\fff2\fff2\bindings\wrapper.pyx":44
 * 
 * 
 * def npy_type(T):             # <<<<<<<<<<<<<<
 *     """
 *     npy_t, nbytes = npy_type(T)
 */

static PyObject *__pyx_pf_4fff2_8bindings_7wrapper_npy_type(PyObject *__pyx_self, PyObject *__pyx_v_T); /*proto*/
static char __pyx_doc_4fff2_8bindings_7wrapper_npy_type[] = "\n    npy_t, nbytes = npy_type(T)\n\n    T is a string. Return a tuple (str, int). \n    ";
static PyObject *__pyx_pf_4fff2_8bindings_7wrapper_npy_type(PyObject *__pyx_self, PyObject *__pyx_v_T) {
  int __pyx_v_npy_t;
  fff_datatype __pyx_v_fff_t;
  unsigned int __pyx_v_nbytes;
  PyObject *__pyx_r;
  PyObject *__pyx_1 = 0;
  PyObject *__pyx_2 = 0;
  PyObject *__pyx_3 = 0;
  PyObject *__pyx_4 = 0;
  fff_datatype __pyx_5;
  __pyx_self = __pyx_self;

  /* "d:\home\ar203069\bzr\nipy\fff2\fff2\bindings\wrapper.pyx":53
 *     cdef fff_datatype fff_t
 *     cdef unsigned int nbytes
 *     fff_t = <fff_datatype>fff_types[c_types.index(T)]             # <<<<<<<<<<<<<<
 *     npy_t = fff_datatype_toNumPy(fff_t)
 *     nbytes =  fff_nbytes(fff_t)
 */
  __pyx_1 = __Pyx_GetName(__pyx_m, __pyx_kp_fff_types); if (unlikely(!__pyx_1)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 53; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
  __pyx_2 = __Pyx_GetName(__pyx_m, __pyx_kp_c_types); if (unlikely(!__pyx_2)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 53; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
  __pyx_3 = PyObject_GetAttr(__pyx_2, __pyx_kp_index); if (unlikely(!__pyx_3)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 53; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
  Py_DECREF(__pyx_2); __pyx_2 = 0;
  __pyx_2 = PyTuple_New(1); if (unlikely(!__pyx_2)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 53; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
  Py_INCREF(__pyx_v_T);
  PyTuple_SET_ITEM(__pyx_2, 0, __pyx_v_T);
  __pyx_4 = PyObject_Call(__pyx_3, ((PyObject *)__pyx_2), NULL); if (unlikely(!__pyx_4)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 53; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
  Py_DECREF(__pyx_3); __pyx_3 = 0;
  Py_DECREF(((PyObject *)__pyx_2)); __pyx_2 = 0;
  __pyx_3 = PyObject_GetItem(__pyx_1, __pyx_4); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 53; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
  Py_DECREF(__pyx_1); __pyx_1 = 0;
  Py_DECREF(__pyx_4); __pyx_4 = 0;
  __pyx_5 = ((fff_datatype)PyInt_AsLong(__pyx_3)); if (unlikely(PyErr_Occurred())) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 53; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
  Py_DECREF(__pyx_3); __pyx_3 = 0;
  __pyx_v_fff_t = ((fff_datatype)__pyx_5);

  /* "d:\home\ar203069\bzr\nipy\fff2\fff2\bindings\wrapper.pyx":54
 *     cdef unsigned int nbytes
 *     fff_t = <fff_datatype>fff_types[c_types.index(T)]
 *     npy_t = fff_datatype_toNumPy(fff_t)             # <<<<<<<<<<<<<<
 *     nbytes =  fff_nbytes(fff_t)
 *     return c_types[npy_types.index(npy_t)], nbytes
 */
  __pyx_v_npy_t = fff_datatype_toNumPy(__pyx_v_fff_t);

  /* "d:\home\ar203069\bzr\nipy\fff2\fff2\bindings\wrapper.pyx":55
 *     fff_t = <fff_datatype>fff_types[c_types.index(T)]
 *     npy_t = fff_datatype_toNumPy(fff_t)
 *     nbytes =  fff_nbytes(fff_t)             # <<<<<<<<<<<<<<
 *     return c_types[npy_types.index(npy_t)], nbytes
 * 
 */
  __pyx_v_nbytes = fff_nbytes(__pyx_v_fff_t);

  /* "d:\home\ar203069\bzr\nipy\fff2\fff2\bindings\wrapper.pyx":56
 *     npy_t = fff_datatype_toNumPy(fff_t)
 *     nbytes =  fff_nbytes(fff_t)
 *     return c_types[npy_types.index(npy_t)], nbytes             # <<<<<<<<<<<<<<
 * 
 * def pass_vector(ndarray X):
 */
  __pyx_2 = __Pyx_GetName(__pyx_m, __pyx_kp_c_types); if (unlikely(!__pyx_2)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 56; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
  __pyx_1 = __Pyx_GetName(__pyx_m, __pyx_kp_npy_types); if (unlikely(!__pyx_1)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 56; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
  __pyx_4 = PyObject_GetAttr(__pyx_1, __pyx_kp_index); if (unlikely(!__pyx_4)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 56; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
  Py_DECREF(__pyx_1); __pyx_1 = 0;
  __pyx_3 = PyInt_FromLong(__pyx_v_npy_t); if (unlikely(!__pyx_3)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 56; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
  __pyx_1 = PyTuple_New(1); if (unlikely(!__pyx_1)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 56; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
  PyTuple_SET_ITEM(__pyx_1, 0, __pyx_3);
  __pyx_3 = 0;
  __pyx_3 = PyObject_Call(__pyx_4, ((PyObject *)__pyx_1), NULL); if (unlikely(!__pyx_3)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 56; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
  Py_DECREF(__pyx_4); __pyx_4 = 0;
  Py_DECREF(((PyObject *)__pyx_1)); __pyx_1 = 0;
  __pyx_4 = PyObject_GetItem(__pyx_2, __pyx_3); if (!__pyx_4) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 56; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
  Py_DECREF(__pyx_2); __pyx_2 = 0;
  Py_DECREF(__pyx_3); __pyx_3 = 0;
  __pyx_1 = PyLong_FromUnsignedLong(__pyx_v_nbytes); if (unlikely(!__pyx_1)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 56; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
  __pyx_2 = PyTuple_New(2); if (unlikely(!__pyx_2)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 56; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
  PyTuple_SET_ITEM(__pyx_2, 0, __pyx_4);
  PyTuple_SET_ITEM(__pyx_2, 1, __pyx_1);
  __pyx_4 = 0;
  __pyx_1 = 0;
  __pyx_r = ((PyObject *)__pyx_2);
  __pyx_2 = 0;
  goto __pyx_L0;

  __pyx_r = Py_None; Py_INCREF(Py_None);
  goto __pyx_L0;
  __pyx_L1_error:;
  Py_XDECREF(__pyx_1);
  Py_XDECREF(__pyx_2);
  Py_XDECREF(__pyx_3);
  Py_XDECREF(__pyx_4);
  __Pyx_AddTraceback("fff2.bindings.wrapper.npy_type");
  __pyx_r = NULL;
  __pyx_L0:;
  return __pyx_r;
}

/* "d:\home\ar203069\bzr\nipy\fff2\fff2\bindings\wrapper.pyx":58
 *     return c_types[npy_types.index(npy_t)], nbytes
 * 
 * def pass_vector(ndarray X):             # <<<<<<<<<<<<<<
 *     """
 *     Y = pass_vector(X)
 */

static PyObject *__pyx_pf_4fff2_8bindings_7wrapper_pass_vector(PyObject *__pyx_self, PyObject *__pyx_v_X); /*proto*/
static char __pyx_doc_4fff2_8bindings_7wrapper_pass_vector[] = "\n    Y = pass_vector(X)\n    ";
static PyObject *__pyx_pf_4fff2_8bindings_7wrapper_pass_vector(PyObject *__pyx_self, PyObject *__pyx_v_X) {
  fff_vector *__pyx_v_x;
  fff_vector *__pyx_v_y;
  PyObject *__pyx_r;
  PyObject *__pyx_1 = 0;
  __pyx_self = __pyx_self;
  if (unlikely(!__Pyx_ArgTypeTest(((PyObject *)__pyx_v_X), __pyx_ptype_4fff2_8bindings_7wrapper_ndarray, 1, "X", 0))) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 58; __pyx_clineno = __LINE__; goto __pyx_L1_error;}

  /* "d:\home\ar203069\bzr\nipy\fff2\fff2\bindings\wrapper.pyx":63
 *     """
 *     cdef fff_vector *x, *y
 *     x = fff_vector_fromPyArray(X)             # <<<<<<<<<<<<<<
 *     y = fff_vector_new(x.size)
 *     fff_vector_memcpy(y, x)
 */
  __pyx_v_x = fff_vector_fromPyArray(((PyArrayObject *)__pyx_v_X));

  /* "d:\home\ar203069\bzr\nipy\fff2\fff2\bindings\wrapper.pyx":64
 *     cdef fff_vector *x, *y
 *     x = fff_vector_fromPyArray(X)
 *     y = fff_vector_new(x.size)             # <<<<<<<<<<<<<<
 *     fff_vector_memcpy(y, x)
 *     fff_vector_delete(x)
 */
  __pyx_v_y = fff_vector_new(__pyx_v_x->size);

  /* "d:\home\ar203069\bzr\nipy\fff2\fff2\bindings\wrapper.pyx":65
 *     x = fff_vector_fromPyArray(X)
 *     y = fff_vector_new(x.size)
 *     fff_vector_memcpy(y, x)             # <<<<<<<<<<<<<<
 *     fff_vector_delete(x)
 *     return fff_vector_toPyArray(y)
 */
  fff_vector_memcpy(__pyx_v_y, __pyx_v_x);

  /* "d:\home\ar203069\bzr\nipy\fff2\fff2\bindings\wrapper.pyx":66
 *     y = fff_vector_new(x.size)
 *     fff_vector_memcpy(y, x)
 *     fff_vector_delete(x)             # <<<<<<<<<<<<<<
 *     return fff_vector_toPyArray(y)
 * 
 */
  fff_vector_delete(__pyx_v_x);

  /* "d:\home\ar203069\bzr\nipy\fff2\fff2\bindings\wrapper.pyx":67
 *     fff_vector_memcpy(y, x)
 *     fff_vector_delete(x)
 *     return fff_vector_toPyArray(y)             # <<<<<<<<<<<<<<
 * 
 * 
 */
  __pyx_1 = ((PyObject *)fff_vector_toPyArray(__pyx_v_y)); if (unlikely(!__pyx_1)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 67; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
  __pyx_r = __pyx_1;
  __pyx_1 = 0;
  goto __pyx_L0;

  __pyx_r = Py_None; Py_INCREF(Py_None);
  goto __pyx_L0;
  __pyx_L1_error:;
  Py_XDECREF(__pyx_1);
  __Pyx_AddTraceback("fff2.bindings.wrapper.pass_vector");
  __pyx_r = NULL;
  __pyx_L0:;
  return __pyx_r;
}

/* "d:\home\ar203069\bzr\nipy\fff2\fff2\bindings\wrapper.pyx":70
 * 
 * 
 * def copy_vector(ndarray X, int flag):             # <<<<<<<<<<<<<<
 *     """
 *     Y = copy_vector(X, flag)
 */

static PyObject *__pyx_pf_4fff2_8bindings_7wrapper_copy_vector(PyObject *__pyx_self, PyObject *__pyx_args, PyObject *__pyx_kwds); /*proto*/
static char __pyx_doc_4fff2_8bindings_7wrapper_copy_vector[] = "\n    Y = copy_vector(X, flag)\n\n    flag == 0 ==> use fff\n    flag == 1 ==> use numpy\n    ";
static PyObject *__pyx_pf_4fff2_8bindings_7wrapper_copy_vector(PyObject *__pyx_self, PyObject *__pyx_args, PyObject *__pyx_kwds) {
  PyArrayObject *__pyx_v_X = 0;
  int __pyx_v_flag;
  fff_vector *__pyx_v_y;
  void *__pyx_v_data;
  int __pyx_v_size;
  int __pyx_v_stride;
  int __pyx_v_relstride;
  int __pyx_v_type;
  int __pyx_v_itemsize;
  fff_datatype __pyx_v_fff_type;
  PyObject *__pyx_r;
  int __pyx_1;
  PyObject *__pyx_2 = 0;
  static PyObject **__pyx_pyargnames[] = {&__pyx_kp_X,&__pyx_kp_flag,0};
  __pyx_self = __pyx_self;
  if (unlikely(__pyx_kwds)) {
    PyObject* values[2] = {0,0};
    Py_ssize_t kw_args = PyDict_Size(__pyx_kwds);
    switch (PyTuple_GET_SIZE(__pyx_args)) {
      case  2: values[1] = PyTuple_GET_ITEM(__pyx_args, 1);
      case  1: values[0] = PyTuple_GET_ITEM(__pyx_args, 0);
      case  0: break;
      default: goto __pyx_L5_argtuple_error;
    }
    switch (PyTuple_GET_SIZE(__pyx_args)) {
      case  0:
      values[0] = PyDict_GetItem(__pyx_kwds, __pyx_kp_X);
      if (likely(values[0])) kw_args--;
      else goto __pyx_L5_argtuple_error;
      case  1:
      values[1] = PyDict_GetItem(__pyx_kwds, __pyx_kp_flag);
      if (likely(values[1])) kw_args--;
      else {
        __Pyx_RaiseArgtupleInvalid("copy_vector", 1, 2, 2, 1); {__pyx_filename = __pyx_f[0]; __pyx_lineno = 70; __pyx_clineno = __LINE__; goto __pyx_L3_error;}
      }
    }
    if (unlikely(kw_args > 0)) {
      if (unlikely(__Pyx_ParseOptionalKeywords(__pyx_kwds, __pyx_pyargnames, 0, values, PyTuple_GET_SIZE(__pyx_args), "copy_vector") < 0)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 70; __pyx_clineno = __LINE__; goto __pyx_L3_error;}
    }
    __pyx_v_X = ((PyArrayObject *)values[0]);
    __pyx_v_flag = __pyx_PyInt_int(values[1]); if (unlikely((__pyx_v_flag == (int)-1) && PyErr_Occurred())) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 70; __pyx_clineno = __LINE__; goto __pyx_L3_error;}
  } else if (PyTuple_GET_SIZE(__pyx_args) != 2) {
    goto __pyx_L5_argtuple_error;
  } else {
    __pyx_v_X = ((PyArrayObject *)PyTuple_GET_ITEM(__pyx_args, 0));
    __pyx_v_flag = __pyx_PyInt_int(PyTuple_GET_ITEM(__pyx_args, 1)); if (unlikely((__pyx_v_flag == (int)-1) && PyErr_Occurred())) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 70; __pyx_clineno = __LINE__; goto __pyx_L3_error;}
  }
  goto __pyx_L4_argument_unpacking_done;
  __pyx_L5_argtuple_error:;
  __Pyx_RaiseArgtupleInvalid("copy_vector", 1, 2, 2, PyTuple_GET_SIZE(__pyx_args)); {__pyx_filename = __pyx_f[0]; __pyx_lineno = 70; __pyx_clineno = __LINE__; goto __pyx_L3_error;}
  __pyx_L3_error:;
  __Pyx_AddTraceback("fff2.bindings.wrapper.copy_vector");
  return NULL;
  __pyx_L4_argument_unpacking_done:;
  if (unlikely(!__Pyx_ArgTypeTest(((PyObject *)__pyx_v_X), __pyx_ptype_4fff2_8bindings_7wrapper_ndarray, 1, "X", 0))) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 70; __pyx_clineno = __LINE__; goto __pyx_L1_error;}

  /* "d:\home\ar203069\bzr\nipy\fff2\fff2\bindings\wrapper.pyx":82
 *     cdef fff_datatype fff_type
 * 
 *     data = <void*>X.data             # <<<<<<<<<<<<<<
 *     size = X.dimensions[0]
 *     stride = X.strides[0]
 */
  __pyx_v_data = ((void *)__pyx_v_X->data);

  /* "d:\home\ar203069\bzr\nipy\fff2\fff2\bindings\wrapper.pyx":83
 * 
 *     data = <void*>X.data
 *     size = X.dimensions[0]             # <<<<<<<<<<<<<<
 *     stride = X.strides[0]
 *     itemsize = X.descr.elsize
 */
  __pyx_v_size = (__pyx_v_X->dimensions[0]);

  /* "d:\home\ar203069\bzr\nipy\fff2\fff2\bindings\wrapper.pyx":84
 *     data = <void*>X.data
 *     size = X.dimensions[0]
 *     stride = X.strides[0]             # <<<<<<<<<<<<<<
 *     itemsize = X.descr.elsize
 *     type = X.descr.type_num
 */
  __pyx_v_stride = (__pyx_v_X->strides[0]);

  /* "d:\home\ar203069\bzr\nipy\fff2\fff2\bindings\wrapper.pyx":85
 *     size = X.dimensions[0]
 *     stride = X.strides[0]
 *     itemsize = X.descr.elsize             # <<<<<<<<<<<<<<
 *     type = X.descr.type_num
 * 
 */
  __pyx_v_itemsize = __pyx_v_X->descr->elsize;

  /* "d:\home\ar203069\bzr\nipy\fff2\fff2\bindings\wrapper.pyx":86
 *     stride = X.strides[0]
 *     itemsize = X.descr.elsize
 *     type = X.descr.type_num             # <<<<<<<<<<<<<<
 * 
 *     relstride = stride/itemsize
 */
  __pyx_v_type = __pyx_v_X->descr->type_num;

  /* "d:\home\ar203069\bzr\nipy\fff2\fff2\bindings\wrapper.pyx":88
 *     type = X.descr.type_num
 * 
 *     relstride = stride/itemsize             # <<<<<<<<<<<<<<
 *     fff_type =  fff_datatype_fromNumPy(type)
 * 
 */
  __pyx_v_relstride = (__pyx_v_stride / __pyx_v_itemsize);

  /* "d:\home\ar203069\bzr\nipy\fff2\fff2\bindings\wrapper.pyx":89
 * 
 *     relstride = stride/itemsize
 *     fff_type =  fff_datatype_fromNumPy(type)             # <<<<<<<<<<<<<<
 * 
 *     y = fff_vector_new(size)
 */
  __pyx_v_fff_type = fff_datatype_fromNumPy(__pyx_v_type);

  /* "d:\home\ar203069\bzr\nipy\fff2\fff2\bindings\wrapper.pyx":91
 *     fff_type =  fff_datatype_fromNumPy(type)
 * 
 *     y = fff_vector_new(size)             # <<<<<<<<<<<<<<
 * 
 *     if flag == 0:
 */
  __pyx_v_y = fff_vector_new(__pyx_v_size);

  /* "d:\home\ar203069\bzr\nipy\fff2\fff2\bindings\wrapper.pyx":93
 *     y = fff_vector_new(size)
 * 
 *     if flag == 0:             # <<<<<<<<<<<<<<
 *         fff_vector_fetch(y, data, fff_type, relstride)
 *     else:
 */
  __pyx_1 = (__pyx_v_flag == 0);
  if (__pyx_1) {

    /* "d:\home\ar203069\bzr\nipy\fff2\fff2\bindings\wrapper.pyx":94
 * 
 *     if flag == 0:
 *         fff_vector_fetch(y, data, fff_type, relstride)             # <<<<<<<<<<<<<<
 *     else:
 *         fff_vector_fetch_using_NumPy(y, <char*>data, stride, type, itemsize)
 */
    fff_vector_fetch(__pyx_v_y, __pyx_v_data, __pyx_v_fff_type, __pyx_v_relstride);
    goto __pyx_L6;
  }
  /*else*/ {

    /* "d:\home\ar203069\bzr\nipy\fff2\fff2\bindings\wrapper.pyx":96
 *         fff_vector_fetch(y, data, fff_type, relstride)
 *     else:
 *         fff_vector_fetch_using_NumPy(y, <char*>data, stride, type, itemsize)             # <<<<<<<<<<<<<<
 * 
 *     return fff_vector_toPyArray(y)
 */
    fff_vector_fetch_using_NumPy(__pyx_v_y, ((char *)__pyx_v_data), __pyx_v_stride, __pyx_v_type, __pyx_v_itemsize);
  }
  __pyx_L6:;

  /* "d:\home\ar203069\bzr\nipy\fff2\fff2\bindings\wrapper.pyx":98
 *         fff_vector_fetch_using_NumPy(y, <char*>data, stride, type, itemsize)
 * 
 *     return fff_vector_toPyArray(y)             # <<<<<<<<<<<<<<
 * 
 * 
 */
  __pyx_2 = ((PyObject *)fff_vector_toPyArray(__pyx_v_y)); if (unlikely(!__pyx_2)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 98; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
  __pyx_r = __pyx_2;
  __pyx_2 = 0;
  goto __pyx_L0;

  __pyx_r = Py_None; Py_INCREF(Py_None);
  goto __pyx_L0;
  __pyx_L1_error:;
  Py_XDECREF(__pyx_2);
  __Pyx_AddTraceback("fff2.bindings.wrapper.copy_vector");
  __pyx_r = NULL;
  __pyx_L0:;
  return __pyx_r;
}

/* "d:\home\ar203069\bzr\nipy\fff2\fff2\bindings\wrapper.pyx":101
 * 
 * 
 * def pass_matrix(ndarray X):             # <<<<<<<<<<<<<<
 *     """
 *     Y = pass_matrix(X)
 */

static PyObject *__pyx_pf_4fff2_8bindings_7wrapper_pass_matrix(PyObject *__pyx_self, PyObject *__pyx_v_X); /*proto*/
static char __pyx_doc_4fff2_8bindings_7wrapper_pass_matrix[] = "\n    Y = pass_matrix(X)\n    ";
static PyObject *__pyx_pf_4fff2_8bindings_7wrapper_pass_matrix(PyObject *__pyx_self, PyObject *__pyx_v_X) {
  fff_matrix *__pyx_v_x;
  fff_matrix *__pyx_v_y;
  PyObject *__pyx_r;
  PyObject *__pyx_1 = 0;
  __pyx_self = __pyx_self;
  if (unlikely(!__Pyx_ArgTypeTest(((PyObject *)__pyx_v_X), __pyx_ptype_4fff2_8bindings_7wrapper_ndarray, 1, "X", 0))) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 101; __pyx_clineno = __LINE__; goto __pyx_L1_error;}

  /* "d:\home\ar203069\bzr\nipy\fff2\fff2\bindings\wrapper.pyx":106
 *     """
 *     cdef fff_matrix *x, *y
 *     x = fff_matrix_fromPyArray(X)             # <<<<<<<<<<<<<<
 *     y = fff_matrix_new(x.size1, x.size2)
 *     fff_matrix_memcpy(y, x)
 */
  __pyx_v_x = fff_matrix_fromPyArray(((PyArrayObject *)__pyx_v_X));

  /* "d:\home\ar203069\bzr\nipy\fff2\fff2\bindings\wrapper.pyx":107
 *     cdef fff_matrix *x, *y
 *     x = fff_matrix_fromPyArray(X)
 *     y = fff_matrix_new(x.size1, x.size2)             # <<<<<<<<<<<<<<
 *     fff_matrix_memcpy(y, x)
 *     fff_matrix_delete(x)
 */
  __pyx_v_y = fff_matrix_new(__pyx_v_x->size1, __pyx_v_x->size2);

  /* "d:\home\ar203069\bzr\nipy\fff2\fff2\bindings\wrapper.pyx":108
 *     x = fff_matrix_fromPyArray(X)
 *     y = fff_matrix_new(x.size1, x.size2)
 *     fff_matrix_memcpy(y, x)             # <<<<<<<<<<<<<<
 *     fff_matrix_delete(x)
 *     return fff_matrix_toPyArray(y)
 */
  fff_matrix_memcpy(__pyx_v_y, __pyx_v_x);

  /* "d:\home\ar203069\bzr\nipy\fff2\fff2\bindings\wrapper.pyx":109
 *     y = fff_matrix_new(x.size1, x.size2)
 *     fff_matrix_memcpy(y, x)
 *     fff_matrix_delete(x)             # <<<<<<<<<<<<<<
 *     return fff_matrix_toPyArray(y)
 * 
 */
  fff_matrix_delete(__pyx_v_x);

  /* "d:\home\ar203069\bzr\nipy\fff2\fff2\bindings\wrapper.pyx":110
 *     fff_matrix_memcpy(y, x)
 *     fff_matrix_delete(x)
 *     return fff_matrix_toPyArray(y)             # <<<<<<<<<<<<<<
 * 
 * 
 */
  __pyx_1 = ((PyObject *)fff_matrix_toPyArray(__pyx_v_y)); if (unlikely(!__pyx_1)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 110; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
  __pyx_r = __pyx_1;
  __pyx_1 = 0;
  goto __pyx_L0;

  __pyx_r = Py_None; Py_INCREF(Py_None);
  goto __pyx_L0;
  __pyx_L1_error:;
  Py_XDECREF(__pyx_1);
  __Pyx_AddTraceback("fff2.bindings.wrapper.pass_matrix");
  __pyx_r = NULL;
  __pyx_L0:;
  return __pyx_r;
}

/* "d:\home\ar203069\bzr\nipy\fff2\fff2\bindings\wrapper.pyx":113
 * 
 * 
 * def pass_array(ndarray X):             # <<<<<<<<<<<<<<
 *     """
 *     Y = pass_array(X)
 */

static PyObject *__pyx_pf_4fff2_8bindings_7wrapper_pass_array(PyObject *__pyx_self, PyObject *__pyx_v_X); /*proto*/
static char __pyx_doc_4fff2_8bindings_7wrapper_pass_array[] = "\n    Y = pass_array(X)\n    ";
static PyObject *__pyx_pf_4fff2_8bindings_7wrapper_pass_array(PyObject *__pyx_self, PyObject *__pyx_v_X) {
  fff_array *__pyx_v_x;
  fff_array *__pyx_v_y;
  PyObject *__pyx_r;
  PyObject *__pyx_1 = 0;
  __pyx_self = __pyx_self;
  if (unlikely(!__Pyx_ArgTypeTest(((PyObject *)__pyx_v_X), __pyx_ptype_4fff2_8bindings_7wrapper_ndarray, 1, "X", 0))) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 113; __pyx_clineno = __LINE__; goto __pyx_L1_error;}

  /* "d:\home\ar203069\bzr\nipy\fff2\fff2\bindings\wrapper.pyx":118
 *     """
 *     cdef fff_array *x, *y
 *     x = fff_array_fromPyArray(X)             # <<<<<<<<<<<<<<
 *     y = fff_array_new(x.datatype, x.dimX, x.dimY, x.dimZ, x.dimT)
 *     fff_array_copy(y, x)
 */
  __pyx_v_x = fff_array_fromPyArray(((PyArrayObject *)__pyx_v_X));

  /* "d:\home\ar203069\bzr\nipy\fff2\fff2\bindings\wrapper.pyx":119
 *     cdef fff_array *x, *y
 *     x = fff_array_fromPyArray(X)
 *     y = fff_array_new(x.datatype, x.dimX, x.dimY, x.dimZ, x.dimT)             # <<<<<<<<<<<<<<
 *     fff_array_copy(y, x)
 *     fff_array_delete(x)
 */
  __pyx_v_y = fff_array_new(__pyx_v_x->datatype, __pyx_v_x->dimX, __pyx_v_x->dimY, __pyx_v_x->dimZ, __pyx_v_x->dimT);

  /* "d:\home\ar203069\bzr\nipy\fff2\fff2\bindings\wrapper.pyx":120
 *     x = fff_array_fromPyArray(X)
 *     y = fff_array_new(x.datatype, x.dimX, x.dimY, x.dimZ, x.dimT)
 *     fff_array_copy(y, x)             # <<<<<<<<<<<<<<
 *     fff_array_delete(x)
 *     return fff_array_toPyArray(y)
 */
  fff_array_copy(__pyx_v_y, __pyx_v_x);

  /* "d:\home\ar203069\bzr\nipy\fff2\fff2\bindings\wrapper.pyx":121
 *     y = fff_array_new(x.datatype, x.dimX, x.dimY, x.dimZ, x.dimT)
 *     fff_array_copy(y, x)
 *     fff_array_delete(x)             # <<<<<<<<<<<<<<
 *     return fff_array_toPyArray(y)
 * 
 */
  fff_array_delete(__pyx_v_x);

  /* "d:\home\ar203069\bzr\nipy\fff2\fff2\bindings\wrapper.pyx":122
 *     fff_array_copy(y, x)
 *     fff_array_delete(x)
 *     return fff_array_toPyArray(y)             # <<<<<<<<<<<<<<
 * 
 * 
 */
  __pyx_1 = ((PyObject *)fff_array_toPyArray(__pyx_v_y)); if (unlikely(!__pyx_1)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 122; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
  __pyx_r = __pyx_1;
  __pyx_1 = 0;
  goto __pyx_L0;

  __pyx_r = Py_None; Py_INCREF(Py_None);
  goto __pyx_L0;
  __pyx_L1_error:;
  Py_XDECREF(__pyx_1);
  __Pyx_AddTraceback("fff2.bindings.wrapper.pass_array");
  __pyx_r = NULL;
  __pyx_L0:;
  return __pyx_r;
}

/* "d:\home\ar203069\bzr\nipy\fff2\fff2\bindings\wrapper.pyx":125
 * 
 * 
 * def pass_vector_via_iterator(ndarray X, int axis=0, int niters=0):             # <<<<<<<<<<<<<<
 *     """
 *     Y = pass_vector_via_iterator(X, axis=0, niters=0)
 */

static PyObject *__pyx_pf_4fff2_8bindings_7wrapper_pass_vector_via_iterator(PyObject *__pyx_self, PyObject *__pyx_args, PyObject *__pyx_kwds); /*proto*/
static char __pyx_doc_4fff2_8bindings_7wrapper_pass_vector_via_iterator[] = "\n    Y = pass_vector_via_iterator(X, axis=0, niters=0)\n    ";
static PyObject *__pyx_pf_4fff2_8bindings_7wrapper_pass_vector_via_iterator(PyObject *__pyx_self, PyObject *__pyx_args, PyObject *__pyx_kwds) {
  PyArrayObject *__pyx_v_X = 0;
  int __pyx_v_axis;
  int __pyx_v_niters;
  fff_vector *__pyx_v_x;
  fff_vector *__pyx_v_y;
  fffpy_multi_iterator *__pyx_v_multi;
  PyObject *__pyx_v_Xdum;
  PyObject *__pyx_r;
  PyObject *__pyx_1 = 0;
  PyObject *__pyx_2 = 0;
  int __pyx_3;
  static PyObject **__pyx_pyargnames[] = {&__pyx_kp_X,&__pyx_kp_axis,&__pyx_kp_niters,0};
  __pyx_self = __pyx_self;
  __pyx_v_axis = 0;
  __pyx_v_niters = 0;
  if (unlikely(__pyx_kwds)) {
    PyObject* values[3] = {0,0,0};
    Py_ssize_t kw_args = PyDict_Size(__pyx_kwds);
    switch (PyTuple_GET_SIZE(__pyx_args)) {
      case  3: values[2] = PyTuple_GET_ITEM(__pyx_args, 2);
      case  2: values[1] = PyTuple_GET_ITEM(__pyx_args, 1);
      case  1: values[0] = PyTuple_GET_ITEM(__pyx_args, 0);
      case  0: break;
      default: goto __pyx_L5_argtuple_error;
    }
    switch (PyTuple_GET_SIZE(__pyx_args)) {
      case  0:
      values[0] = PyDict_GetItem(__pyx_kwds, __pyx_kp_X);
      if (likely(values[0])) kw_args--;
      else goto __pyx_L5_argtuple_error;
    }
    if (unlikely(kw_args > 0)) {
      if (unlikely(__Pyx_ParseOptionalKeywords(__pyx_kwds, __pyx_pyargnames, 0, values, PyTuple_GET_SIZE(__pyx_args), "pass_vector_via_iterator") < 0)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 125; __pyx_clineno = __LINE__; goto __pyx_L3_error;}
    }
    __pyx_v_X = ((PyArrayObject *)values[0]);
    if (values[1]) {
      __pyx_v_axis = __pyx_PyInt_int(values[1]); if (unlikely((__pyx_v_axis == (int)-1) && PyErr_Occurred())) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 125; __pyx_clineno = __LINE__; goto __pyx_L3_error;}
    }
    if (values[2]) {
      __pyx_v_niters = __pyx_PyInt_int(values[2]); if (unlikely((__pyx_v_niters == (int)-1) && PyErr_Occurred())) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 125; __pyx_clineno = __LINE__; goto __pyx_L3_error;}
    }
  } else {
    switch (PyTuple_GET_SIZE(__pyx_args)) {
      case  3: __pyx_v_niters = __pyx_PyInt_int(PyTuple_GET_ITEM(__pyx_args, 2)); if (unlikely((__pyx_v_niters == (int)-1) && PyErr_Occurred())) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 125; __pyx_clineno = __LINE__; goto __pyx_L3_error;}
      case  2: __pyx_v_axis = __pyx_PyInt_int(PyTuple_GET_ITEM(__pyx_args, 1)); if (unlikely((__pyx_v_axis == (int)-1) && PyErr_Occurred())) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 125; __pyx_clineno = __LINE__; goto __pyx_L3_error;}
      case  1: __pyx_v_X = ((PyArrayObject *)PyTuple_GET_ITEM(__pyx_args, 0));
      break;
      default: goto __pyx_L5_argtuple_error;
    }
  }
  goto __pyx_L4_argument_unpacking_done;
  __pyx_L5_argtuple_error:;
  __Pyx_RaiseArgtupleInvalid("pass_vector_via_iterator", 0, 1, 3, PyTuple_GET_SIZE(__pyx_args)); {__pyx_filename = __pyx_f[0]; __pyx_lineno = 125; __pyx_clineno = __LINE__; goto __pyx_L3_error;}
  __pyx_L3_error:;
  __Pyx_AddTraceback("fff2.bindings.wrapper.pass_vector_via_iterator");
  return NULL;
  __pyx_L4_argument_unpacking_done:;
  __pyx_v_Xdum = Py_None; Py_INCREF(Py_None);
  if (unlikely(!__Pyx_ArgTypeTest(((PyObject *)__pyx_v_X), __pyx_ptype_4fff2_8bindings_7wrapper_ndarray, 1, "X", 0))) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 125; __pyx_clineno = __LINE__; goto __pyx_L1_error;}

  /* "d:\home\ar203069\bzr\nipy\fff2\fff2\bindings\wrapper.pyx":132
 *     cdef fffpy_multi_iterator* multi
 * 
 *     Xdum = X.copy() ## at least two arrays needed for multi iterator             # <<<<<<<<<<<<<<
 *     multi = fffpy_multi_iterator_new(2, axis, <void*>X, <void*>Xdum)
 *     x = multi.vector[0]
 */
  __pyx_1 = PyObject_GetAttr(((PyObject *)__pyx_v_X), __pyx_kp_copy); if (unlikely(!__pyx_1)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 132; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
  __pyx_2 = PyObject_Call(__pyx_1, ((PyObject *)__pyx_empty_tuple), NULL); if (unlikely(!__pyx_2)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 132; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
  Py_DECREF(__pyx_1); __pyx_1 = 0;
  Py_DECREF(__pyx_v_Xdum);
  __pyx_v_Xdum = __pyx_2;
  __pyx_2 = 0;

  /* "d:\home\ar203069\bzr\nipy\fff2\fff2\bindings\wrapper.pyx":133
 * 
 *     Xdum = X.copy() ## at least two arrays needed for multi iterator
 *     multi = fffpy_multi_iterator_new(2, axis, <void*>X, <void*>Xdum)             # <<<<<<<<<<<<<<
 *     x = multi.vector[0]
 * 
 */
  __pyx_v_multi = fffpy_multi_iterator_new(2, __pyx_v_axis, ((void *)__pyx_v_X), ((void *)__pyx_v_Xdum));

  /* "d:\home\ar203069\bzr\nipy\fff2\fff2\bindings\wrapper.pyx":134
 *     Xdum = X.copy() ## at least two arrays needed for multi iterator
 *     multi = fffpy_multi_iterator_new(2, axis, <void*>X, <void*>Xdum)
 *     x = multi.vector[0]             # <<<<<<<<<<<<<<
 * 
 *     while(multi.index < niters):
 */
  __pyx_v_x = (__pyx_v_multi->vector[0]);

  /* "d:\home\ar203069\bzr\nipy\fff2\fff2\bindings\wrapper.pyx":136
 *     x = multi.vector[0]
 * 
 *     while(multi.index < niters):             # <<<<<<<<<<<<<<
 *         fffpy_multi_iterator_update(multi)
 * 
 */
  while (1) {
    __pyx_3 = (__pyx_v_multi->index < __pyx_v_niters);
    if (!__pyx_3) break;

    /* "d:\home\ar203069\bzr\nipy\fff2\fff2\bindings\wrapper.pyx":137
 * 
 *     while(multi.index < niters):
 *         fffpy_multi_iterator_update(multi)             # <<<<<<<<<<<<<<
 * 
 *     y = fff_vector_new(x.size)
 */
    fffpy_multi_iterator_update(__pyx_v_multi);
  }

  /* "d:\home\ar203069\bzr\nipy\fff2\fff2\bindings\wrapper.pyx":139
 *         fffpy_multi_iterator_update(multi)
 * 
 *     y = fff_vector_new(x.size)             # <<<<<<<<<<<<<<
 *     fff_vector_memcpy(y, x)
 *     fffpy_multi_iterator_delete(multi)
 */
  __pyx_v_y = fff_vector_new(__pyx_v_x->size);

  /* "d:\home\ar203069\bzr\nipy\fff2\fff2\bindings\wrapper.pyx":140
 * 
 *     y = fff_vector_new(x.size)
 *     fff_vector_memcpy(y, x)             # <<<<<<<<<<<<<<
 *     fffpy_multi_iterator_delete(multi)
 *     return fff_vector_toPyArray(y)
 */
  fff_vector_memcpy(__pyx_v_y, __pyx_v_x);

  /* "d:\home\ar203069\bzr\nipy\fff2\fff2\bindings\wrapper.pyx":141
 *     y = fff_vector_new(x.size)
 *     fff_vector_memcpy(y, x)
 *     fffpy_multi_iterator_delete(multi)             # <<<<<<<<<<<<<<
 *     return fff_vector_toPyArray(y)
 * 
 */
  fffpy_multi_iterator_delete(__pyx_v_multi);

  /* "d:\home\ar203069\bzr\nipy\fff2\fff2\bindings\wrapper.pyx":142
 *     fff_vector_memcpy(y, x)
 *     fffpy_multi_iterator_delete(multi)
 *     return fff_vector_toPyArray(y)             # <<<<<<<<<<<<<<
 * 
 * 
 */
  __pyx_1 = ((PyObject *)fff_vector_toPyArray(__pyx_v_y)); if (unlikely(!__pyx_1)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 142; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
  __pyx_r = __pyx_1;
  __pyx_1 = 0;
  goto __pyx_L0;

  __pyx_r = Py_None; Py_INCREF(Py_None);
  goto __pyx_L0;
  __pyx_L1_error:;
  Py_XDECREF(__pyx_1);
  Py_XDECREF(__pyx_2);
  __Pyx_AddTraceback("fff2.bindings.wrapper.pass_vector_via_iterator");
  __pyx_r = NULL;
  __pyx_L0:;
  Py_DECREF(__pyx_v_Xdum);
  return __pyx_r;
}

/* "d:\home\ar203069\bzr\nipy\fff2\fff2\bindings\wrapper.pyx":145
 * 
 * 
 * def copy_via_iterators(ndarray Y, int axis=0):             # <<<<<<<<<<<<<<
 *     """
 *     Z = copy_via_iterators(Y, int axis=0)
 */

static PyObject *__pyx_pf_4fff2_8bindings_7wrapper_copy_via_iterators(PyObject *__pyx_self, PyObject *__pyx_args, PyObject *__pyx_kwds); /*proto*/
static char __pyx_doc_4fff2_8bindings_7wrapper_copy_via_iterators[] = "\n    Z = copy_via_iterators(Y, int axis=0) \n\n    Copy array Y into Z via fff's PyArray_MultiIterAllButAxis C function.\n    Behavior should be equivalent to Z = Y.copy(). \n    ";
static PyObject *__pyx_pf_4fff2_8bindings_7wrapper_copy_via_iterators(PyObject *__pyx_self, PyObject *__pyx_args, PyObject *__pyx_kwds) {
  PyArrayObject *__pyx_v_Y = 0;
  int __pyx_v_axis;
  fff_vector *__pyx_v_y;
  fff_vector *__pyx_v_z;
  fffpy_multi_iterator *__pyx_v_multi;
  PyObject *__pyx_v_Z;
  PyObject *__pyx_r;
  PyObject *__pyx_1 = 0;
  PyObject *__pyx_2 = 0;
  PyObject *__pyx_3 = 0;
  int __pyx_4;
  static PyObject **__pyx_pyargnames[] = {&__pyx_kp_Y,&__pyx_kp_axis,0};
  __pyx_self = __pyx_self;
  __pyx_v_axis = 0;
  if (unlikely(__pyx_kwds)) {
    PyObject* values[2] = {0,0};
    Py_ssize_t kw_args = PyDict_Size(__pyx_kwds);
    switch (PyTuple_GET_SIZE(__pyx_args)) {
      case  2: values[1] = PyTuple_GET_ITEM(__pyx_args, 1);
      case  1: values[0] = PyTuple_GET_ITEM(__pyx_args, 0);
      case  0: break;
      default: goto __pyx_L5_argtuple_error;
    }
    switch (PyTuple_GET_SIZE(__pyx_args)) {
      case  0:
      values[0] = PyDict_GetItem(__pyx_kwds, __pyx_kp_Y);
      if (likely(values[0])) kw_args--;
      else goto __pyx_L5_argtuple_error;
    }
    if (unlikely(kw_args > 0)) {
      if (unlikely(__Pyx_ParseOptionalKeywords(__pyx_kwds, __pyx_pyargnames, 0, values, PyTuple_GET_SIZE(__pyx_args), "copy_via_iterators") < 0)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 145; __pyx_clineno = __LINE__; goto __pyx_L3_error;}
    }
    __pyx_v_Y = ((PyArrayObject *)values[0]);
    if (values[1]) {
      __pyx_v_axis = __pyx_PyInt_int(values[1]); if (unlikely((__pyx_v_axis == (int)-1) && PyErr_Occurred())) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 145; __pyx_clineno = __LINE__; goto __pyx_L3_error;}
    }
  } else {
    switch (PyTuple_GET_SIZE(__pyx_args)) {
      case  2: __pyx_v_axis = __pyx_PyInt_int(PyTuple_GET_ITEM(__pyx_args, 1)); if (unlikely((__pyx_v_axis == (int)-1) && PyErr_Occurred())) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 145; __pyx_clineno = __LINE__; goto __pyx_L3_error;}
      case  1: __pyx_v_Y = ((PyArrayObject *)PyTuple_GET_ITEM(__pyx_args, 0));
      break;
      default: goto __pyx_L5_argtuple_error;
    }
  }
  goto __pyx_L4_argument_unpacking_done;
  __pyx_L5_argtuple_error:;
  __Pyx_RaiseArgtupleInvalid("copy_via_iterators", 0, 1, 2, PyTuple_GET_SIZE(__pyx_args)); {__pyx_filename = __pyx_f[0]; __pyx_lineno = 145; __pyx_clineno = __LINE__; goto __pyx_L3_error;}
  __pyx_L3_error:;
  __Pyx_AddTraceback("fff2.bindings.wrapper.copy_via_iterators");
  return NULL;
  __pyx_L4_argument_unpacking_done:;
  __pyx_v_Z = Py_None; Py_INCREF(Py_None);
  if (unlikely(!__Pyx_ArgTypeTest(((PyObject *)__pyx_v_Y), __pyx_ptype_4fff2_8bindings_7wrapper_ndarray, 1, "Y", 0))) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 145; __pyx_clineno = __LINE__; goto __pyx_L1_error;}

  /* "d:\home\ar203069\bzr\nipy\fff2\fff2\bindings\wrapper.pyx":156
 * 
 *     # Allocate output array
 *     Z = np.zeros(Y.shape)             # <<<<<<<<<<<<<<
 * 
 *     # Create a new array iterator
 */
  __pyx_1 = __Pyx_GetName(__pyx_m, __pyx_kp_np); if (unlikely(!__pyx_1)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 156; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
  __pyx_2 = PyObject_GetAttr(__pyx_1, __pyx_kp_zeros); if (unlikely(!__pyx_2)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 156; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
  Py_DECREF(__pyx_1); __pyx_1 = 0;
  __pyx_1 = PyObject_GetAttr(((PyObject *)__pyx_v_Y), __pyx_kp_shape); if (unlikely(!__pyx_1)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 156; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
  __pyx_3 = PyTuple_New(1); if (unlikely(!__pyx_3)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 156; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
  PyTuple_SET_ITEM(__pyx_3, 0, __pyx_1);
  __pyx_1 = 0;
  __pyx_1 = PyObject_Call(__pyx_2, ((PyObject *)__pyx_3), NULL); if (unlikely(!__pyx_1)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 156; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
  Py_DECREF(__pyx_2); __pyx_2 = 0;
  Py_DECREF(((PyObject *)__pyx_3)); __pyx_3 = 0;
  Py_DECREF(__pyx_v_Z);
  __pyx_v_Z = __pyx_1;
  __pyx_1 = 0;

  /* "d:\home\ar203069\bzr\nipy\fff2\fff2\bindings\wrapper.pyx":159
 * 
 *     # Create a new array iterator
 *     multi = fffpy_multi_iterator_new(2, axis, <void*>Y, <void*>Z)             # <<<<<<<<<<<<<<
 * 
 *     # Create views
 */
  __pyx_v_multi = fffpy_multi_iterator_new(2, __pyx_v_axis, ((void *)__pyx_v_Y), ((void *)__pyx_v_Z));

  /* "d:\home\ar203069\bzr\nipy\fff2\fff2\bindings\wrapper.pyx":162
 * 
 *     # Create views
 *     y = multi.vector[0]             # <<<<<<<<<<<<<<
 *     z = multi.vector[1]
 * 
 */
  __pyx_v_y = (__pyx_v_multi->vector[0]);

  /* "d:\home\ar203069\bzr\nipy\fff2\fff2\bindings\wrapper.pyx":163
 *     # Create views
 *     y = multi.vector[0]
 *     z = multi.vector[1]             # <<<<<<<<<<<<<<
 * 
 *     # Loop
 */
  __pyx_v_z = (__pyx_v_multi->vector[1]);

  /* "d:\home\ar203069\bzr\nipy\fff2\fff2\bindings\wrapper.pyx":166
 * 
 *     # Loop
 *     while(multi.index < multi.size):             # <<<<<<<<<<<<<<
 *         fff_vector_memcpy(z, y)
 *         fffpy_multi_iterator_update(multi)
 */
  while (1) {
    __pyx_4 = (__pyx_v_multi->index < __pyx_v_multi->size);
    if (!__pyx_4) break;

    /* "d:\home\ar203069\bzr\nipy\fff2\fff2\bindings\wrapper.pyx":167
 *     # Loop
 *     while(multi.index < multi.size):
 *         fff_vector_memcpy(z, y)             # <<<<<<<<<<<<<<
 *         fffpy_multi_iterator_update(multi)
 * 
 */
    fff_vector_memcpy(__pyx_v_z, __pyx_v_y);

    /* "d:\home\ar203069\bzr\nipy\fff2\fff2\bindings\wrapper.pyx":168
 *     while(multi.index < multi.size):
 *         fff_vector_memcpy(z, y)
 *         fffpy_multi_iterator_update(multi)             # <<<<<<<<<<<<<<
 * 
 *     # Free memory
 */
    fffpy_multi_iterator_update(__pyx_v_multi);
  }

  /* "d:\home\ar203069\bzr\nipy\fff2\fff2\bindings\wrapper.pyx":171
 * 
 *     # Free memory
 *     fffpy_multi_iterator_delete(multi)             # <<<<<<<<<<<<<<
 * 
 *     # Return
 */
  fffpy_multi_iterator_delete(__pyx_v_multi);

  /* "d:\home\ar203069\bzr\nipy\fff2\fff2\bindings\wrapper.pyx":174
 * 
 *     # Return
 *     return Z             # <<<<<<<<<<<<<<
 * 
 * 
 */
  Py_INCREF(__pyx_v_Z);
  __pyx_r = __pyx_v_Z;
  goto __pyx_L0;

  __pyx_r = Py_None; Py_INCREF(Py_None);
  goto __pyx_L0;
  __pyx_L1_error:;
  Py_XDECREF(__pyx_1);
  Py_XDECREF(__pyx_2);
  Py_XDECREF(__pyx_3);
  __Pyx_AddTraceback("fff2.bindings.wrapper.copy_via_iterators");
  __pyx_r = NULL;
  __pyx_L0:;
  Py_DECREF(__pyx_v_Z);
  return __pyx_r;
}

/* "d:\home\ar203069\bzr\nipy\fff2\fff2\bindings\wrapper.pyx":177
 * 
 * 
 * def sum_via_iterators(ndarray Y, int axis=0):             # <<<<<<<<<<<<<<
 *     """
 *     Z = dummy_iterator(Y, int axis=0)
 */

static PyObject *__pyx_pf_4fff2_8bindings_7wrapper_sum_via_iterators(PyObject *__pyx_self, PyObject *__pyx_args, PyObject *__pyx_kwds); /*proto*/
static char __pyx_doc_4fff2_8bindings_7wrapper_sum_via_iterators[] = "\n    Z = dummy_iterator(Y, int axis=0) \n\n    Return the sum of input elements along the dimension specified by axis.\n    Behavior should be equivalent to Z = Y.sum(axis). \n    ";
static PyObject *__pyx_pf_4fff2_8bindings_7wrapper_sum_via_iterators(PyObject *__pyx_self, PyObject *__pyx_args, PyObject *__pyx_kwds) {
  PyArrayObject *__pyx_v_Y = 0;
  int __pyx_v_axis;
  fff_vector *__pyx_v_y;
  fff_vector *__pyx_v_z;
  fffpy_multi_iterator *__pyx_v_multi;
  PyObject *__pyx_v_dims;
  PyObject *__pyx_v_Z;
  PyObject *__pyx_r;
  PyObject *__pyx_1 = 0;
  PyObject *__pyx_2 = 0;
  PyObject *__pyx_3 = 0;
  int __pyx_4;
  static PyObject **__pyx_pyargnames[] = {&__pyx_kp_Y,&__pyx_kp_axis,0};
  __pyx_self = __pyx_self;
  __pyx_v_axis = 0;
  if (unlikely(__pyx_kwds)) {
    PyObject* values[2] = {0,0};
    Py_ssize_t kw_args = PyDict_Size(__pyx_kwds);
    switch (PyTuple_GET_SIZE(__pyx_args)) {
      case  2: values[1] = PyTuple_GET_ITEM(__pyx_args, 1);
      case  1: values[0] = PyTuple_GET_ITEM(__pyx_args, 0);
      case  0: break;
      default: goto __pyx_L5_argtuple_error;
    }
    switch (PyTuple_GET_SIZE(__pyx_args)) {
      case  0:
      values[0] = PyDict_GetItem(__pyx_kwds, __pyx_kp_Y);
      if (likely(values[0])) kw_args--;
      else goto __pyx_L5_argtuple_error;
    }
    if (unlikely(kw_args > 0)) {
      if (unlikely(__Pyx_ParseOptionalKeywords(__pyx_kwds, __pyx_pyargnames, 0, values, PyTuple_GET_SIZE(__pyx_args), "sum_via_iterators") < 0)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 177; __pyx_clineno = __LINE__; goto __pyx_L3_error;}
    }
    __pyx_v_Y = ((PyArrayObject *)values[0]);
    if (values[1]) {
      __pyx_v_axis = __pyx_PyInt_int(values[1]); if (unlikely((__pyx_v_axis == (int)-1) && PyErr_Occurred())) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 177; __pyx_clineno = __LINE__; goto __pyx_L3_error;}
    }
  } else {
    switch (PyTuple_GET_SIZE(__pyx_args)) {
      case  2: __pyx_v_axis = __pyx_PyInt_int(PyTuple_GET_ITEM(__pyx_args, 1)); if (unlikely((__pyx_v_axis == (int)-1) && PyErr_Occurred())) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 177; __pyx_clineno = __LINE__; goto __pyx_L3_error;}
      case  1: __pyx_v_Y = ((PyArrayObject *)PyTuple_GET_ITEM(__pyx_args, 0));
      break;
      default: goto __pyx_L5_argtuple_error;
    }
  }
  goto __pyx_L4_argument_unpacking_done;
  __pyx_L5_argtuple_error:;
  __Pyx_RaiseArgtupleInvalid("sum_via_iterators", 0, 1, 2, PyTuple_GET_SIZE(__pyx_args)); {__pyx_filename = __pyx_f[0]; __pyx_lineno = 177; __pyx_clineno = __LINE__; goto __pyx_L3_error;}
  __pyx_L3_error:;
  __Pyx_AddTraceback("fff2.bindings.wrapper.sum_via_iterators");
  return NULL;
  __pyx_L4_argument_unpacking_done:;
  __pyx_v_dims = Py_None; Py_INCREF(Py_None);
  __pyx_v_Z = Py_None; Py_INCREF(Py_None);
  if (unlikely(!__Pyx_ArgTypeTest(((PyObject *)__pyx_v_Y), __pyx_ptype_4fff2_8bindings_7wrapper_ndarray, 1, "Y", 0))) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 177; __pyx_clineno = __LINE__; goto __pyx_L1_error;}

  /* "d:\home\ar203069\bzr\nipy\fff2\fff2\bindings\wrapper.pyx":188
 * 
 *     # Allocate output array
 *     dims = list(Y.shape)             # <<<<<<<<<<<<<<
 *     dims[axis] = 1
 *     Z = np.zeros(dims)
 */
  __pyx_1 = PyObject_GetAttr(((PyObject *)__pyx_v_Y), __pyx_kp_shape); if (unlikely(!__pyx_1)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 188; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
  __pyx_2 = PyTuple_New(1); if (unlikely(!__pyx_2)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 188; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
  PyTuple_SET_ITEM(__pyx_2, 0, __pyx_1);
  __pyx_1 = 0;
  __pyx_1 = PyObject_Call(((PyObject *)((PyObject*)&PyList_Type)), ((PyObject *)__pyx_2), NULL); if (unlikely(!__pyx_1)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 188; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
  Py_DECREF(((PyObject *)__pyx_2)); __pyx_2 = 0;
  Py_DECREF(__pyx_v_dims);
  __pyx_v_dims = __pyx_1;
  __pyx_1 = 0;

  /* "d:\home\ar203069\bzr\nipy\fff2\fff2\bindings\wrapper.pyx":189
 *     # Allocate output array
 *     dims = list(Y.shape)
 *     dims[axis] = 1             # <<<<<<<<<<<<<<
 *     Z = np.zeros(dims)
 * 
 */
  if (__Pyx_SetItemInt(__pyx_v_dims, __pyx_v_axis, __pyx_int_1, 0) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 189; __pyx_clineno = __LINE__; goto __pyx_L1_error;}

  /* "d:\home\ar203069\bzr\nipy\fff2\fff2\bindings\wrapper.pyx":190
 *     dims = list(Y.shape)
 *     dims[axis] = 1
 *     Z = np.zeros(dims)             # <<<<<<<<<<<<<<
 * 
 *     # Create a new array iterator
 */
  __pyx_2 = __Pyx_GetName(__pyx_m, __pyx_kp_np); if (unlikely(!__pyx_2)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 190; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
  __pyx_1 = PyObject_GetAttr(__pyx_2, __pyx_kp_zeros); if (unlikely(!__pyx_1)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 190; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
  Py_DECREF(__pyx_2); __pyx_2 = 0;
  __pyx_2 = PyTuple_New(1); if (unlikely(!__pyx_2)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 190; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
  Py_INCREF(__pyx_v_dims);
  PyTuple_SET_ITEM(__pyx_2, 0, __pyx_v_dims);
  __pyx_3 = PyObject_Call(__pyx_1, ((PyObject *)__pyx_2), NULL); if (unlikely(!__pyx_3)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 190; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
  Py_DECREF(__pyx_1); __pyx_1 = 0;
  Py_DECREF(((PyObject *)__pyx_2)); __pyx_2 = 0;
  Py_DECREF(__pyx_v_Z);
  __pyx_v_Z = __pyx_3;
  __pyx_3 = 0;

  /* "d:\home\ar203069\bzr\nipy\fff2\fff2\bindings\wrapper.pyx":193
 * 
 *     # Create a new array iterator
 *     multi = fffpy_multi_iterator_new(2, axis, <void*>Y, <void*>Z)             # <<<<<<<<<<<<<<
 * 
 *     # Create views
 */
  __pyx_v_multi = fffpy_multi_iterator_new(2, __pyx_v_axis, ((void *)__pyx_v_Y), ((void *)__pyx_v_Z));

  /* "d:\home\ar203069\bzr\nipy\fff2\fff2\bindings\wrapper.pyx":196
 * 
 *     # Create views
 *     y = multi.vector[0]             # <<<<<<<<<<<<<<
 *     z = multi.vector[1]
 * 
 */
  __pyx_v_y = (__pyx_v_multi->vector[0]);

  /* "d:\home\ar203069\bzr\nipy\fff2\fff2\bindings\wrapper.pyx":197
 *     # Create views
 *     y = multi.vector[0]
 *     z = multi.vector[1]             # <<<<<<<<<<<<<<
 * 
 *     # Loop
 */
  __pyx_v_z = (__pyx_v_multi->vector[1]);

  /* "d:\home\ar203069\bzr\nipy\fff2\fff2\bindings\wrapper.pyx":200
 * 
 *     # Loop
 *     while(multi.index < multi.size):             # <<<<<<<<<<<<<<
 *         z.data[0] = <double>fff_vector_sum(y)
 *         fffpy_multi_iterator_update(multi)
 */
  while (1) {
    __pyx_4 = (__pyx_v_multi->index < __pyx_v_multi->size);
    if (!__pyx_4) break;

    /* "d:\home\ar203069\bzr\nipy\fff2\fff2\bindings\wrapper.pyx":201
 *     # Loop
 *     while(multi.index < multi.size):
 *         z.data[0] = <double>fff_vector_sum(y)             # <<<<<<<<<<<<<<
 *         fffpy_multi_iterator_update(multi)
 * 
 */
    (__pyx_v_z->data[0]) = ((double)fff_vector_sum(__pyx_v_y));

    /* "d:\home\ar203069\bzr\nipy\fff2\fff2\bindings\wrapper.pyx":202
 *     while(multi.index < multi.size):
 *         z.data[0] = <double>fff_vector_sum(y)
 *         fffpy_multi_iterator_update(multi)             # <<<<<<<<<<<<<<
 * 
 *     # Free memory
 */
    fffpy_multi_iterator_update(__pyx_v_multi);
  }

  /* "d:\home\ar203069\bzr\nipy\fff2\fff2\bindings\wrapper.pyx":205
 * 
 *     # Free memory
 *     fffpy_multi_iterator_delete(multi)             # <<<<<<<<<<<<<<
 * 
 *     # Return
 */
  fffpy_multi_iterator_delete(__pyx_v_multi);

  /* "d:\home\ar203069\bzr\nipy\fff2\fff2\bindings\wrapper.pyx":208
 * 
 *     # Return
 *     return Z.squeeze()             # <<<<<<<<<<<<<<
 * 
 * 
 */
  __pyx_1 = PyObject_GetAttr(__pyx_v_Z, __pyx_kp_squeeze); if (unlikely(!__pyx_1)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 208; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
  __pyx_2 = PyObject_Call(__pyx_1, ((PyObject *)__pyx_empty_tuple), NULL); if (unlikely(!__pyx_2)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 208; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
  Py_DECREF(__pyx_1); __pyx_1 = 0;
  __pyx_r = __pyx_2;
  __pyx_2 = 0;
  goto __pyx_L0;

  __pyx_r = Py_None; Py_INCREF(Py_None);
  goto __pyx_L0;
  __pyx_L1_error:;
  Py_XDECREF(__pyx_1);
  Py_XDECREF(__pyx_2);
  Py_XDECREF(__pyx_3);
  __Pyx_AddTraceback("fff2.bindings.wrapper.sum_via_iterators");
  __pyx_r = NULL;
  __pyx_L0:;
  Py_DECREF(__pyx_v_dims);
  Py_DECREF(__pyx_v_Z);
  return __pyx_r;
}

static struct PyMethodDef __pyx_methods[] = {
  {"fff_type", (PyCFunction)__pyx_pf_4fff2_8bindings_7wrapper_fff_type, METH_O, __pyx_doc_4fff2_8bindings_7wrapper_fff_type},
  {"npy_type", (PyCFunction)__pyx_pf_4fff2_8bindings_7wrapper_npy_type, METH_O, __pyx_doc_4fff2_8bindings_7wrapper_npy_type},
  {"pass_vector", (PyCFunction)__pyx_pf_4fff2_8bindings_7wrapper_pass_vector, METH_O, __pyx_doc_4fff2_8bindings_7wrapper_pass_vector},
  {"copy_vector", (PyCFunction)__pyx_pf_4fff2_8bindings_7wrapper_copy_vector, METH_VARARGS|METH_KEYWORDS, __pyx_doc_4fff2_8bindings_7wrapper_copy_vector},
  {"pass_matrix", (PyCFunction)__pyx_pf_4fff2_8bindings_7wrapper_pass_matrix, METH_O, __pyx_doc_4fff2_8bindings_7wrapper_pass_matrix},
  {"pass_array", (PyCFunction)__pyx_pf_4fff2_8bindings_7wrapper_pass_array, METH_O, __pyx_doc_4fff2_8bindings_7wrapper_pass_array},
  {"pass_vector_via_iterator", (PyCFunction)__pyx_pf_4fff2_8bindings_7wrapper_pass_vector_via_iterator, METH_VARARGS|METH_KEYWORDS, __pyx_doc_4fff2_8bindings_7wrapper_pass_vector_via_iterator},
  {"copy_via_iterators", (PyCFunction)__pyx_pf_4fff2_8bindings_7wrapper_copy_via_iterators, METH_VARARGS|METH_KEYWORDS, __pyx_doc_4fff2_8bindings_7wrapper_copy_via_iterators},
  {"sum_via_iterators", (PyCFunction)__pyx_pf_4fff2_8bindings_7wrapper_sum_via_iterators, METH_VARARGS|METH_KEYWORDS, __pyx_doc_4fff2_8bindings_7wrapper_sum_via_iterators},
  {0, 0, 0, 0}
};

static void __pyx_init_filenames(void); /*proto*/

#if PY_MAJOR_VERSION >= 3
static struct PyModuleDef __pyx_moduledef = {
    PyModuleDef_HEAD_INIT,
    "wrapper",
    __pyx_mdoc, /* m_doc */
    -1, /* m_size */
    __pyx_methods /* m_methods */,
    NULL, /* m_reload */
    NULL, /* m_traverse */
    NULL, /* m_clear */
    NULL /* m_free */
};
#endif

static __Pyx_StringTabEntry __pyx_string_tab[] = {
  {&__pyx_kp_T, __pyx_k_T, sizeof(__pyx_k_T), 1, 1, 1},
  {&__pyx_kp_X, __pyx_k_X, sizeof(__pyx_k_X), 1, 1, 1},
  {&__pyx_kp_flag, __pyx_k_flag, sizeof(__pyx_k_flag), 1, 1, 1},
  {&__pyx_kp_axis, __pyx_k_axis, sizeof(__pyx_k_axis), 1, 1, 1},
  {&__pyx_kp_niters, __pyx_k_niters, sizeof(__pyx_k_niters), 1, 1, 1},
  {&__pyx_kp_Y, __pyx_k_Y, sizeof(__pyx_k_Y), 1, 1, 1},
  {&__pyx_kp___version__, __pyx_k___version__, sizeof(__pyx_k___version__), 1, 1, 1},
  {&__pyx_kp_numpy, __pyx_k_numpy, sizeof(__pyx_k_numpy), 1, 1, 1},
  {&__pyx_kp_np, __pyx_k_np, sizeof(__pyx_k_np), 0, 1, 1},
  {&__pyx_kp_7, __pyx_k_7, sizeof(__pyx_k_7), 0, 1, 0},
  {&__pyx_kp_10, __pyx_k_10, sizeof(__pyx_k_10), 0, 1, 0},
  {&__pyx_kp_11, __pyx_k_11, sizeof(__pyx_k_11), 0, 1, 0},
  {&__pyx_kp_12, __pyx_k_12, sizeof(__pyx_k_12), 0, 1, 0},
  {&__pyx_kp_c_types, __pyx_k_c_types, sizeof(__pyx_k_c_types), 1, 1, 1},
  {&__pyx_kp_fff_types, __pyx_k_fff_types, sizeof(__pyx_k_fff_types), 1, 1, 1},
  {&__pyx_kp_npy_types, __pyx_k_npy_types, sizeof(__pyx_k_npy_types), 1, 1, 1},
  {&__pyx_kp_index, __pyx_k_index, sizeof(__pyx_k_index), 1, 1, 1},
  {&__pyx_kp_copy, __pyx_k_copy, sizeof(__pyx_k_copy), 1, 1, 1},
  {&__pyx_kp_zeros, __pyx_k_zeros, sizeof(__pyx_k_zeros), 1, 1, 1},
  {&__pyx_kp_shape, __pyx_k_shape, sizeof(__pyx_k_shape), 1, 1, 1},
  {&__pyx_kp_squeeze, __pyx_k_squeeze, sizeof(__pyx_k_squeeze), 1, 1, 1},
  {&__pyx_kp_1, __pyx_k_1, sizeof(__pyx_k_1), 0, 0, 0},
  {&__pyx_kp_2, __pyx_k_2, sizeof(__pyx_k_2), 0, 0, 0},
  {&__pyx_kp_3, __pyx_k_3, sizeof(__pyx_k_3), 0, 0, 0},
  {&__pyx_kp_4, __pyx_k_4, sizeof(__pyx_k_4), 0, 0, 0},
  {&__pyx_kp_5, __pyx_k_5, sizeof(__pyx_k_5), 0, 0, 0},
  {&__pyx_kp_6, __pyx_k_6, sizeof(__pyx_k_6), 0, 0, 0},
  {&__pyx_kp_8, __pyx_k_8, sizeof(__pyx_k_8), 0, 0, 0},
  {&__pyx_kp_9, __pyx_k_9, sizeof(__pyx_k_9), 0, 0, 0},
  {0, 0, 0, 0, 0, 0}
};
static int __Pyx_InitCachedBuiltins(void) {
  return 0;
  return -1;
}

static int __Pyx_InitGlobals(void) {
  __pyx_int_1 = PyInt_FromLong(1); if (unlikely(!__pyx_int_1)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 1; __pyx_clineno = __LINE__; goto __pyx_L1_error;};
  if (__Pyx_InitStrings(__pyx_string_tab) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 1; __pyx_clineno = __LINE__; goto __pyx_L1_error;};
  return 0;
  __pyx_L1_error:;
  return -1;
}

#if PY_MAJOR_VERSION < 3
PyMODINIT_FUNC initwrapper(void); /*proto*/
PyMODINIT_FUNC initwrapper(void)
#else
PyMODINIT_FUNC PyInit_wrapper(void); /*proto*/
PyMODINIT_FUNC PyInit_wrapper(void)
#endif
{
  PyObject *__pyx_1 = 0;
  PyObject *__pyx_2 = 0;
  PyObject *__pyx_3 = 0;
  PyObject *__pyx_4 = 0;
  PyObject *__pyx_5 = 0;
  PyObject *__pyx_6 = 0;
  PyObject *__pyx_7 = 0;
  PyObject *__pyx_8 = 0;
  PyObject *__pyx_9 = 0;
  PyObject *__pyx_10 = 0;
  PyObject *__pyx_11 = 0;
  PyObject *__pyx_12 = 0;
  __pyx_empty_tuple = PyTuple_New(0); if (unlikely(!__pyx_empty_tuple)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 1; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
  /*--- Library function declarations ---*/
  __pyx_init_filenames();
  /*--- Initialize various global constants etc. ---*/
  if (unlikely(__Pyx_InitGlobals() < 0)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 1; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
  /*--- Module creation code ---*/
  #if PY_MAJOR_VERSION < 3
  __pyx_m = Py_InitModule4("wrapper", __pyx_methods, __pyx_mdoc, 0, PYTHON_API_VERSION);
  #else
  __pyx_m = PyModule_Create(&__pyx_moduledef);
  #endif
  if (!__pyx_m) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 1; __pyx_clineno = __LINE__; goto __pyx_L1_error;};
  #if PY_MAJOR_VERSION < 3
  Py_INCREF(__pyx_m);
  #endif
  __pyx_b = PyImport_AddModule(__Pyx_BUILTIN_MODULE_NAME);
  if (!__pyx_b) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 1; __pyx_clineno = __LINE__; goto __pyx_L1_error;};
  if (PyObject_SetAttrString(__pyx_m, "__builtins__", __pyx_b) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 1; __pyx_clineno = __LINE__; goto __pyx_L1_error;};
  /*--- Builtin init code ---*/
  if (unlikely(__Pyx_InitCachedBuiltins() < 0)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 1; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
  __pyx_skip_dispatch = 0;
  /*--- Global init code ---*/
  /*--- Function export code ---*/
  /*--- Type init code ---*/
  __pyx_ptype_4fff2_8bindings_7wrapper_dtype = __Pyx_ImportType("numpy", "dtype", sizeof(PyArray_Descr)); if (unlikely(!__pyx_ptype_4fff2_8bindings_7wrapper_dtype)) {__pyx_filename = __pyx_f[1]; __pyx_lineno = 74; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
  __pyx_ptype_4fff2_8bindings_7wrapper_ndarray = __Pyx_ImportType("numpy", "ndarray", sizeof(PyArrayObject)); if (unlikely(!__pyx_ptype_4fff2_8bindings_7wrapper_ndarray)) {__pyx_filename = __pyx_f[1]; __pyx_lineno = 79; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
  __pyx_ptype_4fff2_8bindings_7wrapper_flatiter = __Pyx_ImportType("numpy", "flatiter", sizeof(PyArrayIterObject)); if (unlikely(!__pyx_ptype_4fff2_8bindings_7wrapper_flatiter)) {__pyx_filename = __pyx_f[1]; __pyx_lineno = 88; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
  __pyx_ptype_4fff2_8bindings_7wrapper_broadcast = __Pyx_ImportType("numpy", "broadcast", sizeof(PyArrayMultiIterObject)); if (unlikely(!__pyx_ptype_4fff2_8bindings_7wrapper_broadcast)) {__pyx_filename = __pyx_f[1]; __pyx_lineno = 94; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
  /*--- Type import code ---*/
  /*--- Function import code ---*/
  /*--- Execution code ---*/

  /* "d:\home\ar203069\bzr\nipy\fff2\fff2\bindings\wrapper.pyx":9
 * """
 * 
 * __version__ = '0.1'             # <<<<<<<<<<<<<<
 * 
 * 
 */
  if (PyObject_SetAttr(__pyx_m, __pyx_kp___version__, __pyx_kp_1) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 9; __pyx_clineno = __LINE__; goto __pyx_L1_error;}

  /* "d:\home\ar203069\bzr\nipy\fff2\fff2\bindings\wrapper.pyx":16
 * 
 * # Initialize numpy
 * fffpy_import_array()             # <<<<<<<<<<<<<<
 * import_array()
 * import numpy as np
 */
  fffpy_import_array();

  /* "d:\home\ar203069\bzr\nipy\fff2\fff2\bindings\wrapper.pyx":17
 * # Initialize numpy
 * fffpy_import_array()
 * import_array()             # <<<<<<<<<<<<<<
 * import numpy as np
 * 
 */
  import_array();

  /* "d:\home\ar203069\bzr\nipy\fff2\fff2\bindings\wrapper.pyx":18
 * fffpy_import_array()
 * import_array()
 * import numpy as np             # <<<<<<<<<<<<<<
 * 
 * 
 */
  __pyx_1 = __Pyx_Import(__pyx_kp_numpy, 0); if (unlikely(!__pyx_1)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 18; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
  if (PyObject_SetAttr(__pyx_m, __pyx_kp_np, __pyx_1) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 18; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
  Py_DECREF(__pyx_1); __pyx_1 = 0;

  /* "d:\home\ar203069\bzr\nipy\fff2\fff2\bindings\wrapper.pyx":22
 * 
 * c_types = ['unknown type', 'unsigned char', 'signed char', 'unsigned short', 'signed short',
 *            'int', 'unsigned int', 'unsigned long', 'long', 'float', 'double']             # <<<<<<<<<<<<<<
 * 
 * fff_types = [FFF_UNKNOWN_TYPE, FFF_UCHAR, FFF_SCHAR, FFF_USHORT, FFF_SSHORT,
 */
  __pyx_1 = PyList_New(11); if (unlikely(!__pyx_1)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 21; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
  Py_INCREF(__pyx_kp_2);
  PyList_SET_ITEM(__pyx_1, 0, __pyx_kp_2);
  Py_INCREF(__pyx_kp_3);
  PyList_SET_ITEM(__pyx_1, 1, __pyx_kp_3);
  Py_INCREF(__pyx_kp_4);
  PyList_SET_ITEM(__pyx_1, 2, __pyx_kp_4);
  Py_INCREF(__pyx_kp_5);
  PyList_SET_ITEM(__pyx_1, 3, __pyx_kp_5);
  Py_INCREF(__pyx_kp_6);
  PyList_SET_ITEM(__pyx_1, 4, __pyx_kp_6);
  Py_INCREF(__pyx_kp_7);
  PyList_SET_ITEM(__pyx_1, 5, __pyx_kp_7);
  Py_INCREF(__pyx_kp_8);
  PyList_SET_ITEM(__pyx_1, 6, __pyx_kp_8);
  Py_INCREF(__pyx_kp_9);
  PyList_SET_ITEM(__pyx_1, 7, __pyx_kp_9);
  Py_INCREF(__pyx_kp_10);
  PyList_SET_ITEM(__pyx_1, 8, __pyx_kp_10);
  Py_INCREF(__pyx_kp_11);
  PyList_SET_ITEM(__pyx_1, 9, __pyx_kp_11);
  Py_INCREF(__pyx_kp_12);
  PyList_SET_ITEM(__pyx_1, 10, __pyx_kp_12);
  if (PyObject_SetAttr(__pyx_m, __pyx_kp_c_types, ((PyObject *)__pyx_1)) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 21; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
  Py_DECREF(((PyObject *)__pyx_1)); __pyx_1 = 0;

  /* "d:\home\ar203069\bzr\nipy\fff2\fff2\bindings\wrapper.pyx":24
 *            'int', 'unsigned int', 'unsigned long', 'long', 'float', 'double']
 * 
 * fff_types = [FFF_UNKNOWN_TYPE, FFF_UCHAR, FFF_SCHAR, FFF_USHORT, FFF_SSHORT,             # <<<<<<<<<<<<<<
 *              FFF_UINT, FFF_INT, FFF_ULONG, FFF_LONG, FFF_FLOAT, FFF_DOUBLE]
 * 
 */
  __pyx_1 = PyInt_FromLong(FFF_UNKNOWN_TYPE); if (unlikely(!__pyx_1)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 24; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
  __pyx_2 = PyInt_FromLong(FFF_UCHAR); if (unlikely(!__pyx_2)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 24; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
  __pyx_3 = PyInt_FromLong(FFF_SCHAR); if (unlikely(!__pyx_3)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 24; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
  __pyx_4 = PyInt_FromLong(FFF_USHORT); if (unlikely(!__pyx_4)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 24; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
  __pyx_5 = PyInt_FromLong(FFF_SSHORT); if (unlikely(!__pyx_5)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 24; __pyx_clineno = __LINE__; goto __pyx_L1_error;}

  /* "d:\home\ar203069\bzr\nipy\fff2\fff2\bindings\wrapper.pyx":25
 * 
 * fff_types = [FFF_UNKNOWN_TYPE, FFF_UCHAR, FFF_SCHAR, FFF_USHORT, FFF_SSHORT,
 *              FFF_UINT, FFF_INT, FFF_ULONG, FFF_LONG, FFF_FLOAT, FFF_DOUBLE]             # <<<<<<<<<<<<<<
 * 
 * npy_types = [NPY_NOTYPE, NPY_UBYTE, NPY_BYTE, NPY_USHORT, NPY_SHORT,
 */
  __pyx_6 = PyInt_FromLong(FFF_UINT); if (unlikely(!__pyx_6)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 25; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
  __pyx_7 = PyInt_FromLong(FFF_INT); if (unlikely(!__pyx_7)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 25; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
  __pyx_8 = PyInt_FromLong(FFF_ULONG); if (unlikely(!__pyx_8)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 25; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
  __pyx_9 = PyInt_FromLong(FFF_LONG); if (unlikely(!__pyx_9)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 25; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
  __pyx_10 = PyInt_FromLong(FFF_FLOAT); if (unlikely(!__pyx_10)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 25; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
  __pyx_11 = PyInt_FromLong(FFF_DOUBLE); if (unlikely(!__pyx_11)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 25; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
  __pyx_12 = PyList_New(11); if (unlikely(!__pyx_12)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 24; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
  PyList_SET_ITEM(__pyx_12, 0, __pyx_1);
  PyList_SET_ITEM(__pyx_12, 1, __pyx_2);
  PyList_SET_ITEM(__pyx_12, 2, __pyx_3);
  PyList_SET_ITEM(__pyx_12, 3, __pyx_4);
  PyList_SET_ITEM(__pyx_12, 4, __pyx_5);
  PyList_SET_ITEM(__pyx_12, 5, __pyx_6);
  PyList_SET_ITEM(__pyx_12, 6, __pyx_7);
  PyList_SET_ITEM(__pyx_12, 7, __pyx_8);
  PyList_SET_ITEM(__pyx_12, 8, __pyx_9);
  PyList_SET_ITEM(__pyx_12, 9, __pyx_10);
  PyList_SET_ITEM(__pyx_12, 10, __pyx_11);
  __pyx_1 = 0;
  __pyx_2 = 0;
  __pyx_3 = 0;
  __pyx_4 = 0;
  __pyx_5 = 0;
  __pyx_6 = 0;
  __pyx_7 = 0;
  __pyx_8 = 0;
  __pyx_9 = 0;
  __pyx_10 = 0;
  __pyx_11 = 0;
  if (PyObject_SetAttr(__pyx_m, __pyx_kp_fff_types, ((PyObject *)__pyx_12)) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 24; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
  Py_DECREF(((PyObject *)__pyx_12)); __pyx_12 = 0;

  /* "d:\home\ar203069\bzr\nipy\fff2\fff2\bindings\wrapper.pyx":27
 *              FFF_UINT, FFF_INT, FFF_ULONG, FFF_LONG, FFF_FLOAT, FFF_DOUBLE]
 * 
 * npy_types = [NPY_NOTYPE, NPY_UBYTE, NPY_BYTE, NPY_USHORT, NPY_SHORT,             # <<<<<<<<<<<<<<
 *              NPY_UINT, NPY_INT, NPY_ULONG, NPY_LONG, NPY_FLOAT, NPY_DOUBLE]
 * 
 */
  __pyx_1 = PyInt_FromLong(NPY_NOTYPE); if (unlikely(!__pyx_1)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 27; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
  __pyx_2 = PyInt_FromLong(NPY_UBYTE); if (unlikely(!__pyx_2)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 27; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
  __pyx_3 = PyInt_FromLong(NPY_BYTE); if (unlikely(!__pyx_3)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 27; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
  __pyx_4 = PyInt_FromLong(NPY_USHORT); if (unlikely(!__pyx_4)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 27; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
  __pyx_5 = PyInt_FromLong(NPY_SHORT); if (unlikely(!__pyx_5)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 27; __pyx_clineno = __LINE__; goto __pyx_L1_error;}

  /* "d:\home\ar203069\bzr\nipy\fff2\fff2\bindings\wrapper.pyx":28
 * 
 * npy_types = [NPY_NOTYPE, NPY_UBYTE, NPY_BYTE, NPY_USHORT, NPY_SHORT,
 *              NPY_UINT, NPY_INT, NPY_ULONG, NPY_LONG, NPY_FLOAT, NPY_DOUBLE]             # <<<<<<<<<<<<<<
 * 
 * 
 */
  __pyx_6 = PyInt_FromLong(NPY_UINT); if (unlikely(!__pyx_6)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 28; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
  __pyx_7 = PyInt_FromLong(NPY_INT); if (unlikely(!__pyx_7)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 28; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
  __pyx_8 = PyInt_FromLong(NPY_ULONG); if (unlikely(!__pyx_8)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 28; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
  __pyx_9 = PyInt_FromLong(NPY_LONG); if (unlikely(!__pyx_9)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 28; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
  __pyx_10 = PyInt_FromLong(NPY_FLOAT); if (unlikely(!__pyx_10)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 28; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
  __pyx_11 = PyInt_FromLong(NPY_DOUBLE); if (unlikely(!__pyx_11)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 28; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
  __pyx_12 = PyList_New(11); if (unlikely(!__pyx_12)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 27; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
  PyList_SET_ITEM(__pyx_12, 0, __pyx_1);
  PyList_SET_ITEM(__pyx_12, 1, __pyx_2);
  PyList_SET_ITEM(__pyx_12, 2, __pyx_3);
  PyList_SET_ITEM(__pyx_12, 3, __pyx_4);
  PyList_SET_ITEM(__pyx_12, 4, __pyx_5);
  PyList_SET_ITEM(__pyx_12, 5, __pyx_6);
  PyList_SET_ITEM(__pyx_12, 6, __pyx_7);
  PyList_SET_ITEM(__pyx_12, 7, __pyx_8);
  PyList_SET_ITEM(__pyx_12, 8, __pyx_9);
  PyList_SET_ITEM(__pyx_12, 9, __pyx_10);
  PyList_SET_ITEM(__pyx_12, 10, __pyx_11);
  __pyx_1 = 0;
  __pyx_2 = 0;
  __pyx_3 = 0;
  __pyx_4 = 0;
  __pyx_5 = 0;
  __pyx_6 = 0;
  __pyx_7 = 0;
  __pyx_8 = 0;
  __pyx_9 = 0;
  __pyx_10 = 0;
  __pyx_11 = 0;
  if (PyObject_SetAttr(__pyx_m, __pyx_kp_npy_types, ((PyObject *)__pyx_12)) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 27; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
  Py_DECREF(((PyObject *)__pyx_12)); __pyx_12 = 0;

  /* "d:\home\ar203069\bzr\nipy\fff2\fff2\bindings\wrapper.pyx":177
 * 
 * 
 * def sum_via_iterators(ndarray Y, int axis=0):             # <<<<<<<<<<<<<<
 *     """
 *     Z = dummy_iterator(Y, int axis=0)
 */
  #if PY_MAJOR_VERSION < 3
  return;
  #else
  return __pyx_m;
  #endif
  __pyx_L1_error:;
  Py_XDECREF(__pyx_1);
  Py_XDECREF(__pyx_2);
  Py_XDECREF(__pyx_3);
  Py_XDECREF(__pyx_4);
  Py_XDECREF(__pyx_5);
  Py_XDECREF(__pyx_6);
  Py_XDECREF(__pyx_7);
  Py_XDECREF(__pyx_8);
  Py_XDECREF(__pyx_9);
  Py_XDECREF(__pyx_10);
  Py_XDECREF(__pyx_11);
  Py_XDECREF(__pyx_12);
  __Pyx_AddTraceback("fff2.bindings.wrapper");
  #if PY_MAJOR_VERSION >= 3
  return NULL;
  #endif
}

static const char *__pyx_filenames[] = {
  "wrapper.pyx",
  "numpy.pxi",
};

/* Runtime support code */

static void __pyx_init_filenames(void) {
  __pyx_f = __pyx_filenames;
}

static void __Pyx_RaiseDoubleKeywordsError(
    const char* func_name,
    PyObject* kw_name)
{
    PyErr_Format(PyExc_TypeError,
        #if PY_MAJOR_VERSION >= 3
        "%s() got multiple values for keyword argument '%U'", func_name, kw_name);
        #else
        "%s() got multiple values for keyword argument '%s'", func_name,
        PyString_AS_STRING(kw_name));
        #endif
}

static void __Pyx_RaiseArgtupleInvalid(
    const char* func_name,
    int exact,
    Py_ssize_t num_min,
    Py_ssize_t num_max,
    Py_ssize_t num_found)
{
    Py_ssize_t num_expected;
    const char *number, *more_or_less;

    if (num_found < num_min) {
        num_expected = num_min;
        more_or_less = "at least";
    } else {
        num_expected = num_max;
        more_or_less = "at most";
    }
    if (exact) {
        more_or_less = "exactly";
    }
    number = (num_expected == 1) ? "" : "s";
    PyErr_Format(PyExc_TypeError,
        #if PY_VERSION_HEX < 0x02050000
            "%s() takes %s %d positional argument%s (%d given)",
        #else
            "%s() takes %s %zd positional argument%s (%zd given)",
        #endif
        func_name, more_or_less, num_expected, number, num_found);
}

static int __Pyx_ParseOptionalKeywords(
    PyObject *kwds,
    PyObject **argnames[],
    PyObject *kwds2,
    PyObject *values[],
    Py_ssize_t num_pos_args,
    const char* function_name)
{
    PyObject *key = 0, *value = 0;
    Py_ssize_t pos = 0;
    PyObject*** name;
    PyObject*** first_kw_arg = argnames + num_pos_args;

    while (PyDict_Next(kwds, &pos, &key, &value)) {
        #if PY_MAJOR_VERSION < 3
        if (unlikely(!PyString_CheckExact(key)) && unlikely(!PyString_Check(key))) {
        #else
        if (unlikely(!PyUnicode_CheckExact(key)) && unlikely(!PyUnicode_Check(key))) {
        #endif
            goto invalid_keyword_type;
        } else {
            name = argnames;
            while (*name && (**name != key)) name++;
            if (*name) {
                if (name < first_kw_arg) goto arg_passed_twice;
                values[name-argnames] = value;
            } else {
                for (name = first_kw_arg; *name; name++) {
                    #if PY_MAJOR_VERSION >= 3
                    if (PyUnicode_GET_SIZE(**name) == PyUnicode_GET_SIZE(key) &&
                        PyUnicode_Compare(**name, key) == 0) break;
                    #else
                    if (PyString_GET_SIZE(**name) == PyString_GET_SIZE(key) &&
                        strcmp(PyString_AS_STRING(**name),
                               PyString_AS_STRING(key)) == 0) break;
                    #endif
                }
                if (*name) {
                    values[name-argnames] = value;
                } else {
                    /* unexpected keyword found */
                    for (name=argnames; name != first_kw_arg; name++) {
                        if (**name == key) goto arg_passed_twice;
                        #if PY_MAJOR_VERSION >= 3
                        if (PyUnicode_GET_SIZE(**name) == PyUnicode_GET_SIZE(key) &&
                            PyUnicode_Compare(**name, key) == 0) goto arg_passed_twice;
                        #else
                        if (PyString_GET_SIZE(**name) == PyString_GET_SIZE(key) &&
                            strcmp(PyString_AS_STRING(**name),
                                   PyString_AS_STRING(key)) == 0) goto arg_passed_twice;
                        #endif
                    }
                    if (kwds2) {
                        if (unlikely(PyDict_SetItem(kwds2, key, value))) goto bad;
                    } else {
                        goto invalid_keyword;
                    }
                }
            }
        }
    }
    return 0;
arg_passed_twice:
    __Pyx_RaiseDoubleKeywordsError(function_name, **name);
    goto bad;
invalid_keyword_type:
    PyErr_Format(PyExc_TypeError,
        "%s() keywords must be strings", function_name);
    goto bad;
invalid_keyword:
    PyErr_Format(PyExc_TypeError,
    #if PY_MAJOR_VERSION < 3
        "%s() got an unexpected keyword argument '%s'",
        function_name, PyString_AsString(key));
    #else
        "%s() got an unexpected keyword argument '%U'",
        function_name, key);
    #endif
bad:
    return -1;
}


static int __Pyx_ArgTypeTest(PyObject *obj, PyTypeObject *type, int none_allowed,
    const char *name, int exact)
{
    if (!type) {
        PyErr_Format(PyExc_SystemError, "Missing type object");
        return 0;
    }
    if (none_allowed && obj == Py_None) return 1;
    else if (exact) {
        if (Py_TYPE(obj) == type) return 1;
    }
    else {
        if (PyObject_TypeCheck(obj, type)) return 1;
    }
    PyErr_Format(PyExc_TypeError,
        "Argument '%s' has incorrect type (expected %s, got %s)",
        name, type->tp_name, Py_TYPE(obj)->tp_name);
    return 0;
}

static PyObject *__Pyx_Import(PyObject *name, PyObject *from_list) {
    PyObject *__import__ = 0;
    PyObject *empty_list = 0;
    PyObject *module = 0;
    PyObject *global_dict = 0;
    PyObject *empty_dict = 0;
    PyObject *list;
    __import__ = PyObject_GetAttrString(__pyx_b, "__import__");
    if (!__import__)
        goto bad;
    if (from_list)
        list = from_list;
    else {
        empty_list = PyList_New(0);
        if (!empty_list)
            goto bad;
        list = empty_list;
    }
    global_dict = PyModule_GetDict(__pyx_m);
    if (!global_dict)
        goto bad;
    empty_dict = PyDict_New();
    if (!empty_dict)
        goto bad;
    module = PyObject_CallFunction(__import__, "OOOO",
        name, global_dict, empty_dict, list);
bad:
    Py_XDECREF(empty_list);
    Py_XDECREF(__import__);
    Py_XDECREF(empty_dict);
    return module;
}

static PyObject *__Pyx_GetName(PyObject *dict, PyObject *name) {
    PyObject *result;
    result = PyObject_GetAttr(dict, name);
    if (!result)
        PyErr_SetObject(PyExc_NameError, name);
    return result;
}

#ifndef __PYX_HAVE_RT_ImportType
#define __PYX_HAVE_RT_ImportType
static PyTypeObject *__Pyx_ImportType(const char *module_name, const char *class_name,
    long size)
{
    PyObject *py_module = 0;
    PyObject *result = 0;
    PyObject *py_name = 0;

    py_module = __Pyx_ImportModule(module_name);
    if (!py_module)
        goto bad;
    #if PY_MAJOR_VERSION < 3
    py_name = PyString_FromString(class_name);
    #else
    py_name = PyUnicode_FromString(class_name);
    #endif
    if (!py_name)
        goto bad;
    result = PyObject_GetAttr(py_module, py_name);
    Py_DECREF(py_name);
    py_name = 0;
    Py_DECREF(py_module);
    py_module = 0;
    if (!result)
        goto bad;
    if (!PyType_Check(result)) {
        PyErr_Format(PyExc_TypeError, 
            "%s.%s is not a type object",
            module_name, class_name);
        goto bad;
    }
    if (((PyTypeObject *)result)->tp_basicsize != size) {
        PyErr_Format(PyExc_ValueError, 
            "%s.%s does not appear to be the correct type object",
            module_name, class_name);
        goto bad;
    }
    return (PyTypeObject *)result;
bad:
    Py_XDECREF(py_module);
    Py_XDECREF(result);
    return 0;
}
#endif

#ifndef __PYX_HAVE_RT_ImportModule
#define __PYX_HAVE_RT_ImportModule
static PyObject *__Pyx_ImportModule(const char *name) {
    PyObject *py_name = 0;
    PyObject *py_module = 0;

    #if PY_MAJOR_VERSION < 3
    py_name = PyString_FromString(name);
    #else
    py_name = PyUnicode_FromString(name);
    #endif
    if (!py_name)
        goto bad;
    py_module = PyImport_Import(py_name);
    Py_DECREF(py_name);
    return py_module;
bad:
    Py_XDECREF(py_name);
    return 0;
}
#endif

#include "compile.h"
#include "frameobject.h"
#include "traceback.h"

static void __Pyx_AddTraceback(const char *funcname) {
    PyObject *py_srcfile = 0;
    PyObject *py_funcname = 0;
    PyObject *py_globals = 0;
    PyObject *empty_string = 0;
    PyCodeObject *py_code = 0;
    PyFrameObject *py_frame = 0;

    #if PY_MAJOR_VERSION < 3
    py_srcfile = PyString_FromString(__pyx_filename);
    #else
    py_srcfile = PyUnicode_FromString(__pyx_filename);
    #endif
    if (!py_srcfile) goto bad;
    if (__pyx_clineno) {
        #if PY_MAJOR_VERSION < 3
        py_funcname = PyString_FromFormat( "%s (%s:%d)", funcname, __pyx_cfilenm, __pyx_clineno);
        #else
        py_funcname = PyUnicode_FromFormat( "%s (%s:%d)", funcname, __pyx_cfilenm, __pyx_clineno);
        #endif
    }
    else {
        #if PY_MAJOR_VERSION < 3
        py_funcname = PyString_FromString(funcname);
        #else
        py_funcname = PyUnicode_FromString(funcname);
        #endif
    }
    if (!py_funcname) goto bad;
    py_globals = PyModule_GetDict(__pyx_m);
    if (!py_globals) goto bad;
    #if PY_MAJOR_VERSION < 3
    empty_string = PyString_FromStringAndSize("", 0);
    #else
    empty_string = PyBytes_FromStringAndSize("", 0);
    #endif
    if (!empty_string) goto bad;
    py_code = PyCode_New(
        0,            /*int argcount,*/
        #if PY_MAJOR_VERSION >= 3
        0,            /*int kwonlyargcount,*/
        #endif
        0,            /*int nlocals,*/
        0,            /*int stacksize,*/
        0,            /*int flags,*/
        empty_string, /*PyObject *code,*/
        __pyx_empty_tuple,  /*PyObject *consts,*/
        __pyx_empty_tuple,  /*PyObject *names,*/
        __pyx_empty_tuple,  /*PyObject *varnames,*/
        __pyx_empty_tuple,  /*PyObject *freevars,*/
        __pyx_empty_tuple,  /*PyObject *cellvars,*/
        py_srcfile,   /*PyObject *filename,*/
        py_funcname,  /*PyObject *name,*/
        __pyx_lineno,   /*int firstlineno,*/
        empty_string  /*PyObject *lnotab*/
    );
    if (!py_code) goto bad;
    py_frame = PyFrame_New(
        PyThreadState_GET(), /*PyThreadState *tstate,*/
        py_code,             /*PyCodeObject *code,*/
        py_globals,          /*PyObject *globals,*/
        0                    /*PyObject *locals*/
    );
    if (!py_frame) goto bad;
    py_frame->f_lineno = __pyx_lineno;
    PyTraceBack_Here(py_frame);
bad:
    Py_XDECREF(py_srcfile);
    Py_XDECREF(py_funcname);
    Py_XDECREF(empty_string);
    Py_XDECREF(py_code);
    Py_XDECREF(py_frame);
}

static int __Pyx_InitStrings(__Pyx_StringTabEntry *t) {
    while (t->p) {
        #if PY_MAJOR_VERSION < 3
        if (t->is_unicode && (!t->is_identifier)) {
            *t->p = PyUnicode_DecodeUTF8(t->s, t->n - 1, NULL);
        } else if (t->intern) {
            *t->p = PyString_InternFromString(t->s);
        } else {
            *t->p = PyString_FromStringAndSize(t->s, t->n - 1);
        }
        #else  /* Python 3+ has unicode identifiers */
        if (t->is_identifier || (t->is_unicode && t->intern)) {
            *t->p = PyUnicode_InternFromString(t->s);
        } else if (t->is_unicode) {
            *t->p = PyUnicode_FromStringAndSize(t->s, t->n - 1);
        } else {
            *t->p = PyBytes_FromStringAndSize(t->s, t->n - 1);
        }
        #endif
        if (!*t->p)
            return -1;
        ++t;
    }
    return 0;
}

/* Type Conversion Functions */

static INLINE Py_ssize_t __pyx_PyIndex_AsSsize_t(PyObject* b) {
  Py_ssize_t ival;
  PyObject* x = PyNumber_Index(b);
  if (!x) return -1;
  ival = PyInt_AsSsize_t(x);
  Py_DECREF(x);
  return ival;
}

static INLINE int __Pyx_PyObject_IsTrue(PyObject* x) {
   if (x == Py_True) return 1;
   else if (x == Py_False) return 0;
   else return PyObject_IsTrue(x);
}

static INLINE PY_LONG_LONG __pyx_PyInt_AsLongLong(PyObject* x) {
    if (PyInt_CheckExact(x)) {
        return PyInt_AS_LONG(x);
    }
    else if (PyLong_CheckExact(x)) {
        return PyLong_AsLongLong(x);
    }
    else {
        PY_LONG_LONG val;
        PyObject* tmp = PyNumber_Int(x); if (!tmp) return (PY_LONG_LONG)-1;
        val = __pyx_PyInt_AsLongLong(tmp);
        Py_DECREF(tmp);
        return val;
    }
}

static INLINE unsigned PY_LONG_LONG __pyx_PyInt_AsUnsignedLongLong(PyObject* x) {
    if (PyInt_CheckExact(x)) {
        long val = PyInt_AS_LONG(x);
        if (unlikely(val < 0)) {
            PyErr_SetString(PyExc_TypeError, "Negative assignment to unsigned type.");
            return (unsigned PY_LONG_LONG)-1;
        }
        return val;
    }
    else if (PyLong_CheckExact(x)) {
        return PyLong_AsUnsignedLongLong(x);
    }
    else {
        PY_LONG_LONG val;
        PyObject* tmp = PyNumber_Int(x); if (!tmp) return (PY_LONG_LONG)-1;
        val = __pyx_PyInt_AsUnsignedLongLong(tmp);
        Py_DECREF(tmp);
        return val;
    }
}


static INLINE unsigned char __pyx_PyInt_unsigned_char(PyObject* x) {
    if (sizeof(unsigned char) < sizeof(long)) {
        long long_val = __pyx_PyInt_AsLong(x);
        unsigned char val = (unsigned char)long_val;
        if (unlikely((val != long_val)  || (long_val < 0))) {
            PyErr_SetString(PyExc_OverflowError, "value too large to convert to unsigned char");
            return (unsigned char)-1;
        }
        return val;
    }
    else {
        return __pyx_PyInt_AsLong(x);
    }
}

static INLINE unsigned short __pyx_PyInt_unsigned_short(PyObject* x) {
    if (sizeof(unsigned short) < sizeof(long)) {
        long long_val = __pyx_PyInt_AsLong(x);
        unsigned short val = (unsigned short)long_val;
        if (unlikely((val != long_val)  || (long_val < 0))) {
            PyErr_SetString(PyExc_OverflowError, "value too large to convert to unsigned short");
            return (unsigned short)-1;
        }
        return val;
    }
    else {
        return __pyx_PyInt_AsLong(x);
    }
}

static INLINE char __pyx_PyInt_char(PyObject* x) {
    if (sizeof(char) < sizeof(long)) {
        long long_val = __pyx_PyInt_AsLong(x);
        char val = (char)long_val;
        if (unlikely((val != long_val) )) {
            PyErr_SetString(PyExc_OverflowError, "value too large to convert to char");
            return (char)-1;
        }
        return val;
    }
    else {
        return __pyx_PyInt_AsLong(x);
    }
}

static INLINE short __pyx_PyInt_short(PyObject* x) {
    if (sizeof(short) < sizeof(long)) {
        long long_val = __pyx_PyInt_AsLong(x);
        short val = (short)long_val;
        if (unlikely((val != long_val) )) {
            PyErr_SetString(PyExc_OverflowError, "value too large to convert to short");
            return (short)-1;
        }
        return val;
    }
    else {
        return __pyx_PyInt_AsLong(x);
    }
}

static INLINE int __pyx_PyInt_int(PyObject* x) {
    if (sizeof(int) < sizeof(long)) {
        long long_val = __pyx_PyInt_AsLong(x);
        int val = (int)long_val;
        if (unlikely((val != long_val) )) {
            PyErr_SetString(PyExc_OverflowError, "value too large to convert to int");
            return (int)-1;
        }
        return val;
    }
    else {
        return __pyx_PyInt_AsLong(x);
    }
}

static INLINE long __pyx_PyInt_long(PyObject* x) {
    if (sizeof(long) < sizeof(long)) {
        long long_val = __pyx_PyInt_AsLong(x);
        long val = (long)long_val;
        if (unlikely((val != long_val) )) {
            PyErr_SetString(PyExc_OverflowError, "value too large to convert to long");
            return (long)-1;
        }
        return val;
    }
    else {
        return __pyx_PyInt_AsLong(x);
    }
}

static INLINE signed char __pyx_PyInt_signed_char(PyObject* x) {
    if (sizeof(signed char) < sizeof(long)) {
        long long_val = __pyx_PyInt_AsLong(x);
        signed char val = (signed char)long_val;
        if (unlikely((val != long_val) )) {
            PyErr_SetString(PyExc_OverflowError, "value too large to convert to signed char");
            return (signed char)-1;
        }
        return val;
    }
    else {
        return __pyx_PyInt_AsLong(x);
    }
}

static INLINE signed short __pyx_PyInt_signed_short(PyObject* x) {
    if (sizeof(signed short) < sizeof(long)) {
        long long_val = __pyx_PyInt_AsLong(x);
        signed short val = (signed short)long_val;
        if (unlikely((val != long_val) )) {
            PyErr_SetString(PyExc_OverflowError, "value too large to convert to signed short");
            return (signed short)-1;
        }
        return val;
    }
    else {
        return __pyx_PyInt_AsLong(x);
    }
}

static INLINE signed int __pyx_PyInt_signed_int(PyObject* x) {
    if (sizeof(signed int) < sizeof(long)) {
        long long_val = __pyx_PyInt_AsLong(x);
        signed int val = (signed int)long_val;
        if (unlikely((val != long_val) )) {
            PyErr_SetString(PyExc_OverflowError, "value too large to convert to signed int");
            return (signed int)-1;
        }
        return val;
    }
    else {
        return __pyx_PyInt_AsLong(x);
    }
}

static INLINE signed long __pyx_PyInt_signed_long(PyObject* x) {
    if (sizeof(signed long) < sizeof(long)) {
        long long_val = __pyx_PyInt_AsLong(x);
        signed long val = (signed long)long_val;
        if (unlikely((val != long_val) )) {
            PyErr_SetString(PyExc_OverflowError, "value too large to convert to signed long");
            return (signed long)-1;
        }
        return val;
    }
    else {
        return __pyx_PyInt_AsLong(x);
    }
}

static INLINE long double __pyx_PyInt_long_double(PyObject* x) {
    if (sizeof(long double) < sizeof(long)) {
        long long_val = __pyx_PyInt_AsLong(x);
        long double val = (long double)long_val;
        if (unlikely((val != long_val) )) {
            PyErr_SetString(PyExc_OverflowError, "value too large to convert to long double");
            return (long double)-1;
        }
        return val;
    }
    else {
        return __pyx_PyInt_AsLong(x);
    }
}

