#!/bin/sh
PYTHON_PATH=../lib
FILTER='tests\|enthought\|sandbox\|config'

output_dir=api
mkdir -p ${output_dir}
epydoc  \
  --output ${output_dir} \
  --name nipy \
  --url http://neuroimaging.scipy.org \
  --no-private \
  --inheritance listed \
  --graph all \
  --debug \
  $(find $PYTHON_PATH/neuroimaging -name "*py" | grep -v $FILTER)
