#!/bin/sh
PYTHON_PATH=../lib
output_dir=api
mkdir -p ${output_dir}
epydoc -qqqq \
  --output ${output_dir} \
  --name nipy \
  --url http://neuroimaging.scipy.org \
  --no-private \
  --inheritance listed \
  --graph all \
  $PYTHON_PATH/neuroimaging
