#!/bin/sh
PYTHON_PATH=../lib
output_dir=api
mkdir -p ${output_dir}
epydoc -vvvv \
  --output ${output_dir} \
  --name nipy \
  --url http://neuroimaging.scipy.org \
  --no-private \
  --inheritance listed \
  --graph all \
  $(find $PYTHON_PATH/neuroimaging -name "*py" | grep -v tests | grep -v enthought)
#  $PYTHON_PATH/neuroimaging
