#-------------------------------------------------------------------------------
#
#  The 'ViewHandler' traits view definition and handler.
#
#-------------------------------------------------------------------------------
#
#  Generated by the VET tool (version 0.1.0) on Tue May 23 10:10:08 2006.
#
#-------------------------------------------------------------------------------
#
#  Usage is:
#    ViewHandler().edit_traits( context = object_to_edit, ... )
#
#-------------------------------------------------------------------------------

#-------------------------------------------------------------------------------
#  Imports:
#-------------------------------------------------------------------------------

from enthought.traits.ui      import Handler, View, Group, Item
from enthought.traits.ui.menu import MenuBar, Menu, Action, Separator

#-------------------------------------------------------------------------------
#  'ViewHandler' class:
#-------------------------------------------------------------------------------

class ViewHandler ( Handler ):
    
    #---------------------------------------------------------------------------
    #  Traits view definition:    
    #---------------------------------------------------------------------------
        
    traits_view = View(
        Group(
            Item(
                name   = 'fmrifile',
                object = 'RunUI'
            ),
            Item(
                name   = 'maskfile',
                object = 'RunUI'
            ),
            Item(
                name   = 'mask',
                object = 'RunUI'
            ),
            Item(
                name   = 'run',
                object = 'RunUI'
            )
        ),
        Group(
            Item(
                name   = 'drift_df',
                object = 'RunUI'
            ),
            Item(
                name   = 'knots',
                object = 'RunUI'
            ),
            Item( name = '_' ),
            Item(
                name   = 'normalize',
                object = 'RunUI'
            )
        )
    ) 
    
#-------------------------------------------------------------------------------
#  'ViewHandler' test case: 
#-------------------------------------------------------------------------------

if __name__ == '__main__':
    import ui
    ViewHandler().configure_traits( context = {
        'RunUI': ui.RunUI()
    } )
