#!/usr/bin/env python
''' Script to run nosetests with all favorite options

In this case, with full console output, and doctests

You can add other options with (e.g.):

bignose --with-coverage
'''
import sys
import nose

sys.argv += ['-sv', '--with-doctest']

nose.run()
