#!/usr/bin/env python3
# vim: ft=python
""" Run nosetests using nipy doctest plugin

Use as ``nosetests`` except we always run the doctests, and we use the nipy
doctest plugin, which adds some new flags, and features, such as adding ``np``
to the namespace of tests, and discovering docstrings in cython modules.

To reproduce a standard ``nipy.test()`` run::

    nipnost -A "not slow" /path/to/nipy/nipy

To run without doctests, add the flag ``--without-doctest``.
"""

import sys
import nose
from nipy.testing.nosetester import prepare_imports, fpw_opt_str
from nipy.testing.doctester import NipyDoctest
from nipy.fixes.numpy.testing.noseclasses import KnownFailure

if __name__ == '__main__':
    prepare_imports()
    argv = sys.argv[:] + [fpw_opt_str()]
    if '--without-doctest' in argv:
        argv.remove('--without-doctest')
    else:
        argv.append('--with-nipydoctest')
    nose.core.TestProgram(argv=argv, addplugins=[NipyDoctest(), KnownFailure()])
