/* Generated by Cython 0.10.3 on Sat Apr 04 00:44:38 2009 */

#define PY_SSIZE_T_CLEAN
#include "Python.h"
#include "structmember.h"
#ifndef PY_LONG_LONG
  #define PY_LONG_LONG LONG_LONG
#endif
#ifndef DL_EXPORT
  #define DL_EXPORT(t) t
#endif
#if PY_VERSION_HEX < 0x02040000
  #define METH_COEXIST 0
#endif
#if PY_VERSION_HEX < 0x02050000
  typedef int Py_ssize_t;
  #define PY_SSIZE_T_MAX INT_MAX
  #define PY_SSIZE_T_MIN INT_MIN
  #define PyInt_FromSsize_t(z) PyInt_FromLong(z)
  #define PyInt_AsSsize_t(o)   PyInt_AsLong(o)
  #define PyNumber_Index(o)    PyNumber_Int(o)
  #define PyIndex_Check(o)     PyNumber_Check(o)
#endif
#if PY_VERSION_HEX < 0x02060000
  #define Py_REFCNT(ob) (((PyObject*)(ob))->ob_refcnt)
  #define Py_TYPE(ob)   (((PyObject*)(ob))->ob_type)
  #define Py_SIZE(ob)   (((PyVarObject*)(ob))->ob_size)
  #define PyVarObject_HEAD_INIT(type, size) \
          PyObject_HEAD_INIT(type) size,
  #define PyType_Modified(t)

  typedef struct {
       void *buf;
       PyObject *obj;
       Py_ssize_t len;
       Py_ssize_t itemsize;
       int readonly;
       int ndim;
       char *format;
       Py_ssize_t *shape;
       Py_ssize_t *strides;
       Py_ssize_t *suboffsets;
       void *internal;
  } Py_buffer;

  #define PyBUF_SIMPLE 0
  #define PyBUF_WRITABLE 0x0001
  #define PyBUF_LOCK 0x0002
  #define PyBUF_FORMAT 0x0004
  #define PyBUF_ND 0x0008
  #define PyBUF_STRIDES (0x0010 | PyBUF_ND)
  #define PyBUF_C_CONTIGUOUS (0x0020 | PyBUF_STRIDES)
  #define PyBUF_F_CONTIGUOUS (0x0040 | PyBUF_STRIDES)
  #define PyBUF_ANY_CONTIGUOUS (0x0080 | PyBUF_STRIDES)
  #define PyBUF_INDIRECT (0x0100 | PyBUF_STRIDES)

#endif
#if PY_MAJOR_VERSION < 3
  #define __Pyx_BUILTIN_MODULE_NAME "__builtin__"
#else
  #define __Pyx_BUILTIN_MODULE_NAME "builtins"
#endif
#if PY_MAJOR_VERSION >= 3
  #define Py_TPFLAGS_CHECKTYPES 0
  #define Py_TPFLAGS_HAVE_INDEX 0
#endif
#if (PY_VERSION_HEX < 0x02060000) || (PY_MAJOR_VERSION >= 3)
  #define Py_TPFLAGS_HAVE_NEWBUFFER 0
#endif
#if PY_MAJOR_VERSION >= 3
  #define PyBaseString_Type            PyUnicode_Type
  #define PyString_Type                PyBytes_Type
  #define PyInt_Type                   PyLong_Type
  #define PyInt_Check(op)              PyLong_Check(op)
  #define PyInt_CheckExact(op)         PyLong_CheckExact(op)
  #define PyInt_FromString             PyLong_FromString
  #define PyInt_FromUnicode            PyLong_FromUnicode
  #define PyInt_FromLong               PyLong_FromLong
  #define PyInt_FromSize_t             PyLong_FromSize_t
  #define PyInt_FromSsize_t            PyLong_FromSsize_t
  #define PyInt_AsLong                 PyLong_AsLong
  #define PyInt_AS_LONG                PyLong_AS_LONG
  #define PyInt_AsSsize_t              PyLong_AsSsize_t
  #define PyInt_AsUnsignedLongMask     PyLong_AsUnsignedLongMask
  #define PyInt_AsUnsignedLongLongMask PyLong_AsUnsignedLongLongMask
  #define __Pyx_PyNumber_Divide(x,y)         PyNumber_TrueDivide(x,y)
#else
  #define __Pyx_PyNumber_Divide(x,y)         PyNumber_Divide(x,y)
  #define PyBytes_Type                 PyString_Type
#endif
#if PY_MAJOR_VERSION >= 3
  #define PyMethod_New(func, self, klass) PyInstanceMethod_New(func)
#endif
#if !defined(WIN32) && !defined(MS_WINDOWS)
  #ifndef __stdcall
    #define __stdcall
  #endif
  #ifndef __cdecl
    #define __cdecl
  #endif
#else
  #define _USE_MATH_DEFINES
#endif
#ifdef __cplusplus
#define __PYX_EXTERN_C extern "C"
#else
#define __PYX_EXTERN_C extern
#endif
#include <math.h>
#define __PYX_HAVE_API__neuroimaging__neurospin__utils__routines
#include "numpy/arrayobject.h"
#include "fff_base.h"
#include "fff_vector.h"
#include "fff_matrix.h"
#include "fff_array.h"
#include "randomkit.h"
#include "fffpy.h"
#include "fff_gen_stats.h"
#include "fff_specfun.h"


#ifdef __GNUC__
#define INLINE __inline__
#elif _WIN32
#define INLINE __inline
#else
#define INLINE 
#endif

typedef struct {PyObject **p; char *s; long n; char is_unicode; char intern; char is_identifier;} __Pyx_StringTabEntry; /*proto*/



static int __pyx_skip_dispatch = 0;


/* Type Conversion Predeclarations */

#if PY_MAJOR_VERSION < 3
#define __Pyx_PyBytes_FromString PyString_FromString
#define __Pyx_PyBytes_AsString   PyString_AsString
#else
#define __Pyx_PyBytes_FromString PyBytes_FromString
#define __Pyx_PyBytes_AsString   PyBytes_AsString
#endif

#define __Pyx_PyBool_FromLong(b) ((b) ? (Py_INCREF(Py_True), Py_True) : (Py_INCREF(Py_False), Py_False))
static INLINE int __Pyx_PyObject_IsTrue(PyObject* x);
static INLINE PY_LONG_LONG __pyx_PyInt_AsLongLong(PyObject* x);
static INLINE unsigned PY_LONG_LONG __pyx_PyInt_AsUnsignedLongLong(PyObject* x);
static INLINE Py_ssize_t __pyx_PyIndex_AsSsize_t(PyObject* b);

#define __pyx_PyInt_AsLong(x) (PyInt_CheckExact(x) ? PyInt_AS_LONG(x) : PyInt_AsLong(x))
#define __pyx_PyFloat_AsDouble(x) (PyFloat_CheckExact(x) ? PyFloat_AS_DOUBLE(x) : PyFloat_AsDouble(x))

static INLINE unsigned char __pyx_PyInt_unsigned_char(PyObject* x);
static INLINE unsigned short __pyx_PyInt_unsigned_short(PyObject* x);
static INLINE char __pyx_PyInt_char(PyObject* x);
static INLINE short __pyx_PyInt_short(PyObject* x);
static INLINE int __pyx_PyInt_int(PyObject* x);
static INLINE long __pyx_PyInt_long(PyObject* x);
static INLINE signed char __pyx_PyInt_signed_char(PyObject* x);
static INLINE signed short __pyx_PyInt_signed_short(PyObject* x);
static INLINE signed int __pyx_PyInt_signed_int(PyObject* x);
static INLINE signed long __pyx_PyInt_signed_long(PyObject* x);
static INLINE long double __pyx_PyInt_long_double(PyObject* x);
#ifdef __GNUC__
/* Test for GCC > 2.95 */
#if __GNUC__ > 2 ||               (__GNUC__ == 2 && (__GNUC_MINOR__ > 95)) 
#define likely(x)   __builtin_expect(!!(x), 1)
#define unlikely(x) __builtin_expect(!!(x), 0)
#else /* __GNUC__ > 2 ... */
#define likely(x)   (x)
#define unlikely(x) (x)
#endif /* __GNUC__ > 2 ... */
#else /* __GNUC__ */
#define likely(x)   (x)
#define unlikely(x) (x)
#endif /* __GNUC__ */
    
static PyObject *__pyx_m;
static PyObject *__pyx_b;
static PyObject *__pyx_empty_tuple;
static int __pyx_lineno;
static int __pyx_clineno = 0;
static const char * __pyx_cfilenm= __FILE__;
static const char *__pyx_filename;
static const char **__pyx_f;

static char __pyx_mdoc[] = "\nMiscellaneous fff routines.\n\nAuthor: Alexis Roche, 2008.\n";

static void __Pyx_RaiseDoubleKeywordsError(
    const char* func_name, PyObject* kw_name); /*proto*/

static void __Pyx_RaiseArgtupleInvalid(const char* func_name, int exact,
    Py_ssize_t num_min, Py_ssize_t num_max, Py_ssize_t num_found); /*proto*/

static int __Pyx_ParseOptionalKeywords(PyObject *kwds, PyObject **argnames[],     PyObject *kwds2, PyObject *values[], Py_ssize_t num_pos_args,     const char* function_name); /*proto*/

static INLINE int __Pyx_SetItemInt(PyObject *o, Py_ssize_t i, PyObject *v, int is_unsigned) {
    int r;
    if (PyList_CheckExact(o) && 0 <= i && i < PyList_GET_SIZE(o)) {
        Py_DECREF(PyList_GET_ITEM(o, i));
        Py_INCREF(v);
        PyList_SET_ITEM(o, i, v);
        return 1;
    }
    else if (Py_TYPE(o)->tp_as_sequence && Py_TYPE(o)->tp_as_sequence->sq_ass_item && (likely(i >= 0) || !is_unsigned))
        r = PySequence_SetItem(o, i, v);
    else {
        PyObject *j = (likely(i >= 0) || !is_unsigned) ? PyInt_FromLong(i) : PyLong_FromUnsignedLongLong((sizeof(unsigned long long) > sizeof(Py_ssize_t) ? (1ULL << (sizeof(Py_ssize_t)*8)) : 0) + i);
        if (!j)
            return -1;
        r = PyObject_SetItem(o, j, v);
        Py_DECREF(j);
    }
    return r;
}

static INLINE PyObject *__Pyx_GetItemInt(PyObject *o, Py_ssize_t i, int is_unsigned) {
    PyObject *r;
    if (PyList_CheckExact(o) && 0 <= i && i < PyList_GET_SIZE(o)) {
        r = PyList_GET_ITEM(o, i);
        Py_INCREF(r);
    }
    else if (PyTuple_CheckExact(o) && 0 <= i && i < PyTuple_GET_SIZE(o)) {
        r = PyTuple_GET_ITEM(o, i);
        Py_INCREF(r);
    }
    else if (Py_TYPE(o)->tp_as_sequence && Py_TYPE(o)->tp_as_sequence->sq_item && (likely(i >= 0) || !is_unsigned))
        r = PySequence_GetItem(o, i);
    else {
        PyObject *j = (likely(i >= 0) || !is_unsigned) ? PyInt_FromLong(i) : PyLong_FromUnsignedLongLong((sizeof(unsigned long long) > sizeof(Py_ssize_t) ? (1ULL << (sizeof(Py_ssize_t)*8)) : 0) + i);
        if (!j)
            return 0;
        r = PyObject_GetItem(o, j);
        Py_DECREF(j);
    }
    return r;
}

static PyObject *__Pyx_Import(PyObject *name, PyObject *from_list); /*proto*/

static PyObject *__Pyx_GetName(PyObject *dict, PyObject *name); /*proto*/

static PyTypeObject *__Pyx_ImportType(const char *module_name, const char *class_name, long size);  /*proto*/

static PyObject *__Pyx_ImportModule(const char *name); /*proto*/

static void __Pyx_AddTraceback(const char *funcname); /*proto*/

static int __Pyx_InitStrings(__Pyx_StringTabEntry *t); /*proto*/

/* Type declarations */

typedef unsigned long __pyx_t_12neuroimaging_9neurospin_5utils_8routines_size_t;
/* Module declarations from numpy */

/* Module declarations from neuroimaging.neurospin.utils.routines */

static PyTypeObject *__pyx_ptype_12neuroimaging_9neurospin_5utils_8routines_dtype = 0;
static PyTypeObject *__pyx_ptype_12neuroimaging_9neurospin_5utils_8routines_ndarray = 0;
static PyTypeObject *__pyx_ptype_12neuroimaging_9neurospin_5utils_8routines_flatiter = 0;
static PyTypeObject *__pyx_ptype_12neuroimaging_9neurospin_5utils_8routines_broadcast = 0;


/* Implementation of neuroimaging.neurospin.utils.routines */
static char __pyx_k_1[] = "0.1";
static PyObject *__pyx_int_0;
static PyObject *__pyx_int_1;
static char __pyx_k_X[] = "X";
static PyObject *__pyx_kp_X;
static char __pyx_k_ratio[] = "ratio";
static PyObject *__pyx_kp_ratio;
static char __pyx_k_interp[] = "interp";
static PyObject *__pyx_kp_interp;
static char __pyx_k_axis[] = "axis";
static PyObject *__pyx_kp_axis;
static char __pyx_k_x[] = "x";
static PyObject *__pyx_kp_x;
static char __pyx_k_VX[] = "VX";
static PyObject *__pyx_kp_VX;
static char __pyx_k_n[] = "n";
static PyObject *__pyx_kp_n;
static char __pyx_k_m[] = "m";
static PyObject *__pyx_kp_m;
static char __pyx_k_magic[] = "magic";
static PyObject *__pyx_kp_magic;
static char __pyx_k_k[] = "k";
static PyObject *__pyx_kp_k;
static char __pyx_k___version__[] = "__version__";
static PyObject *__pyx_kp___version__;
static char __pyx_k_numpy[] = "numpy";
static PyObject *__pyx_kp_numpy;
static char __pyx_k_np[] = "np";
static PyObject *__pyx_kp_np;
static char __pyx_k_shape[] = "shape";
static PyObject *__pyx_kp_shape;
static char __pyx_k_zeros[] = "zeros";
static PyObject *__pyx_kp_zeros;
static char __pyx_k_quantile[] = "quantile";
static PyObject *__pyx_kp_quantile;
static char __pyx_k_reshape[] = "reshape";
static PyObject *__pyx_kp_reshape;
static PyObject *__pyx_kp_1;

/* "d:\home\ar203069\bzr\nipy\dev-trunk-neurospin\neuroimaging\neurospin\utils\routines.pyx":37
 * 
 * # FIXME: Check that this is faster than scipy.stats.scoreatpercentile
 * def quantile(X, double ratio, int interp=False, int axis=0):             # <<<<<<<<<<<<<<
 *     """
 *     q = quantile(data, ratio, interp=False, axis=0).
 */

static PyObject *__pyx_pf_12neuroimaging_9neurospin_5utils_8routines_quantile(PyObject *__pyx_self, PyObject *__pyx_args, PyObject *__pyx_kwds); /*proto*/
static char __pyx_doc_12neuroimaging_9neurospin_5utils_8routines_quantile[] = "\n    q = quantile(data, ratio, interp=False, axis=0).\n\n    Partial sorting algorithm, very fast!!!\n    ";
static PyObject *__pyx_pf_12neuroimaging_9neurospin_5utils_8routines_quantile(PyObject *__pyx_self, PyObject *__pyx_args, PyObject *__pyx_kwds) {
  PyObject *__pyx_v_X = 0;
  double __pyx_v_ratio;
  int __pyx_v_interp;
  int __pyx_v_axis;
  fff_vector *__pyx_v_x;
  fff_vector *__pyx_v_y;
  fffpy_multi_iterator *__pyx_v_multi;
  PyObject *__pyx_v_dims;
  PyObject *__pyx_v_Y;
  PyObject *__pyx_r;
  PyObject *__pyx_1 = 0;
  PyObject *__pyx_2 = 0;
  PyObject *__pyx_3 = 0;
  int __pyx_4;
  static PyObject **__pyx_pyargnames[] = {&__pyx_kp_X,&__pyx_kp_ratio,&__pyx_kp_interp,&__pyx_kp_axis,0};
  __pyx_self = __pyx_self;
  __pyx_v_interp = 0;
  __pyx_v_axis = 0;
  if (unlikely(__pyx_kwds)) {
    PyObject* values[4] = {0,0,0,0};
    Py_ssize_t kw_args = PyDict_Size(__pyx_kwds);
    switch (PyTuple_GET_SIZE(__pyx_args)) {
      case  4: values[3] = PyTuple_GET_ITEM(__pyx_args, 3);
      case  3: values[2] = PyTuple_GET_ITEM(__pyx_args, 2);
      case  2: values[1] = PyTuple_GET_ITEM(__pyx_args, 1);
      case  1: values[0] = PyTuple_GET_ITEM(__pyx_args, 0);
      case  0: break;
      default: goto __pyx_L5_argtuple_error;
    }
    switch (PyTuple_GET_SIZE(__pyx_args)) {
      case  0:
      values[0] = PyDict_GetItem(__pyx_kwds, __pyx_kp_X);
      if (likely(values[0])) kw_args--;
      else goto __pyx_L5_argtuple_error;
      case  1:
      values[1] = PyDict_GetItem(__pyx_kwds, __pyx_kp_ratio);
      if (likely(values[1])) kw_args--;
      else {
        __Pyx_RaiseArgtupleInvalid("quantile", 0, 2, 4, 1); {__pyx_filename = __pyx_f[0]; __pyx_lineno = 37; __pyx_clineno = __LINE__; goto __pyx_L3_error;}
      }
    }
    if (unlikely(kw_args > 0)) {
      if (unlikely(__Pyx_ParseOptionalKeywords(__pyx_kwds, __pyx_pyargnames, 0, values, PyTuple_GET_SIZE(__pyx_args), "quantile") < 0)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 37; __pyx_clineno = __LINE__; goto __pyx_L3_error;}
    }
    __pyx_v_X = values[0];
    __pyx_v_ratio = __pyx_PyFloat_AsDouble(values[1]); if (unlikely(PyErr_Occurred())) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 37; __pyx_clineno = __LINE__; goto __pyx_L3_error;}
    if (values[2]) {
      __pyx_v_interp = __pyx_PyInt_int(values[2]); if (unlikely((__pyx_v_interp == (int)-1) && PyErr_Occurred())) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 37; __pyx_clineno = __LINE__; goto __pyx_L3_error;}
    }
    if (values[3]) {
      __pyx_v_axis = __pyx_PyInt_int(values[3]); if (unlikely((__pyx_v_axis == (int)-1) && PyErr_Occurred())) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 37; __pyx_clineno = __LINE__; goto __pyx_L3_error;}
    }
  } else {
    switch (PyTuple_GET_SIZE(__pyx_args)) {
      case  4:
      __pyx_v_axis = __pyx_PyInt_int(PyTuple_GET_ITEM(__pyx_args, 3)); if (unlikely((__pyx_v_axis == (int)-1) && PyErr_Occurred())) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 37; __pyx_clineno = __LINE__; goto __pyx_L3_error;}
      case  3:
      __pyx_v_interp = __pyx_PyInt_int(PyTuple_GET_ITEM(__pyx_args, 2)); if (unlikely((__pyx_v_interp == (int)-1) && PyErr_Occurred())) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 37; __pyx_clineno = __LINE__; goto __pyx_L3_error;}
      case  2:
      __pyx_v_ratio = __pyx_PyFloat_AsDouble(PyTuple_GET_ITEM(__pyx_args, 1)); if (unlikely(PyErr_Occurred())) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 37; __pyx_clineno = __LINE__; goto __pyx_L3_error;}
      __pyx_v_X = PyTuple_GET_ITEM(__pyx_args, 0);
      break;
      default: goto __pyx_L5_argtuple_error;
    }
  }
  goto __pyx_L4_argument_unpacking_done;
  __pyx_L5_argtuple_error:;
  __Pyx_RaiseArgtupleInvalid("quantile", 0, 2, 4, PyTuple_GET_SIZE(__pyx_args)); {__pyx_filename = __pyx_f[0]; __pyx_lineno = 37; __pyx_clineno = __LINE__; goto __pyx_L3_error;}
  __pyx_L3_error:;
  __Pyx_AddTraceback("neuroimaging.neurospin.utils.routines.quantile");
  return NULL;
  __pyx_L4_argument_unpacking_done:;
  __pyx_v_dims = Py_None; Py_INCREF(Py_None);
  __pyx_v_Y = Py_None; Py_INCREF(Py_None);

  /* "d:\home\ar203069\bzr\nipy\dev-trunk-neurospin\neuroimaging\neurospin\utils\routines.pyx":47
 * 
 *     # Allocate output array Y
 *     dims = list(X.shape)             # <<<<<<<<<<<<<<
 *     dims[axis] = 1
 *     Y = np.zeros(dims)
 */
  __pyx_1 = PyObject_GetAttr(__pyx_v_X, __pyx_kp_shape); if (unlikely(!__pyx_1)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 47; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
  __pyx_2 = PyTuple_New(1); if (unlikely(!__pyx_2)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 47; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
  PyTuple_SET_ITEM(__pyx_2, 0, __pyx_1);
  __pyx_1 = 0;
  __pyx_1 = PyObject_Call(((PyObject *)((PyObject*)&PyList_Type)), ((PyObject *)__pyx_2), NULL); if (unlikely(!__pyx_1)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 47; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
  Py_DECREF(((PyObject *)__pyx_2)); __pyx_2 = 0;
  Py_DECREF(__pyx_v_dims);
  __pyx_v_dims = __pyx_1;
  __pyx_1 = 0;

  /* "d:\home\ar203069\bzr\nipy\dev-trunk-neurospin\neuroimaging\neurospin\utils\routines.pyx":48
 *     # Allocate output array Y
 *     dims = list(X.shape)
 *     dims[axis] = 1             # <<<<<<<<<<<<<<
 *     Y = np.zeros(dims)
 * 
 */
  if (__Pyx_SetItemInt(__pyx_v_dims, __pyx_v_axis, __pyx_int_1, 0) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 48; __pyx_clineno = __LINE__; goto __pyx_L1_error;}

  /* "d:\home\ar203069\bzr\nipy\dev-trunk-neurospin\neuroimaging\neurospin\utils\routines.pyx":49
 *     dims = list(X.shape)
 *     dims[axis] = 1
 *     Y = np.zeros(dims)             # <<<<<<<<<<<<<<
 * 
 *     # Create a new array iterator
 */
  __pyx_2 = __Pyx_GetName(__pyx_m, __pyx_kp_np); if (unlikely(!__pyx_2)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 49; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
  __pyx_1 = PyObject_GetAttr(__pyx_2, __pyx_kp_zeros); if (unlikely(!__pyx_1)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 49; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
  Py_DECREF(__pyx_2); __pyx_2 = 0;
  __pyx_2 = PyTuple_New(1); if (unlikely(!__pyx_2)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 49; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
  Py_INCREF(__pyx_v_dims);
  PyTuple_SET_ITEM(__pyx_2, 0, __pyx_v_dims);
  __pyx_3 = PyObject_Call(__pyx_1, ((PyObject *)__pyx_2), NULL); if (unlikely(!__pyx_3)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 49; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
  Py_DECREF(__pyx_1); __pyx_1 = 0;
  Py_DECREF(((PyObject *)__pyx_2)); __pyx_2 = 0;
  Py_DECREF(__pyx_v_Y);
  __pyx_v_Y = __pyx_3;
  __pyx_3 = 0;

  /* "d:\home\ar203069\bzr\nipy\dev-trunk-neurospin\neuroimaging\neurospin\utils\routines.pyx":52
 * 
 *     # Create a new array iterator
 *     multi = fffpy_multi_iterator_new(2, axis, <void*>X, <void*>Y)             # <<<<<<<<<<<<<<
 * 
 *     # Create vector views on both X and Y
 */
  __pyx_v_multi = fffpy_multi_iterator_new(2, __pyx_v_axis, ((void *)__pyx_v_X), ((void *)__pyx_v_Y));

  /* "d:\home\ar203069\bzr\nipy\dev-trunk-neurospin\neuroimaging\neurospin\utils\routines.pyx":55
 * 
 *     # Create vector views on both X and Y
 *     x = multi.vector[0]             # <<<<<<<<<<<<<<
 *     y = multi.vector[1]
 * 
 */
  __pyx_v_x = (__pyx_v_multi->vector[0]);

  /* "d:\home\ar203069\bzr\nipy\dev-trunk-neurospin\neuroimaging\neurospin\utils\routines.pyx":56
 *     # Create vector views on both X and Y
 *     x = multi.vector[0]
 *     y = multi.vector[1]             # <<<<<<<<<<<<<<
 * 
 *     # Loop
 */
  __pyx_v_y = (__pyx_v_multi->vector[1]);

  /* "d:\home\ar203069\bzr\nipy\dev-trunk-neurospin\neuroimaging\neurospin\utils\routines.pyx":59
 * 
 *     # Loop
 *     while(multi.index < multi.size):             # <<<<<<<<<<<<<<
 *         y.data[0] = fff_vector_quantile(x, ratio, interp)
 *         fffpy_multi_iterator_update(multi)
 */
  while (1) {
    __pyx_4 = (__pyx_v_multi->index < __pyx_v_multi->size);
    if (!__pyx_4) break;

    /* "d:\home\ar203069\bzr\nipy\dev-trunk-neurospin\neuroimaging\neurospin\utils\routines.pyx":60
 *     # Loop
 *     while(multi.index < multi.size):
 *         y.data[0] = fff_vector_quantile(x, ratio, interp)             # <<<<<<<<<<<<<<
 *         fffpy_multi_iterator_update(multi)
 * 
 */
    (__pyx_v_y->data[0]) = fff_vector_quantile(__pyx_v_x, __pyx_v_ratio, __pyx_v_interp);

    /* "d:\home\ar203069\bzr\nipy\dev-trunk-neurospin\neuroimaging\neurospin\utils\routines.pyx":61
 *     while(multi.index < multi.size):
 *         y.data[0] = fff_vector_quantile(x, ratio, interp)
 *         fffpy_multi_iterator_update(multi)             # <<<<<<<<<<<<<<
 * 
 *     # Delete local structures
 */
    fffpy_multi_iterator_update(__pyx_v_multi);
  }

  /* "d:\home\ar203069\bzr\nipy\dev-trunk-neurospin\neuroimaging\neurospin\utils\routines.pyx":64
 * 
 *     # Delete local structures
 *     fffpy_multi_iterator_delete(multi)             # <<<<<<<<<<<<<<
 *     return Y
 * 
 */
  fffpy_multi_iterator_delete(__pyx_v_multi);

  /* "d:\home\ar203069\bzr\nipy\dev-trunk-neurospin\neuroimaging\neurospin\utils\routines.pyx":65
 *     # Delete local structures
 *     fffpy_multi_iterator_delete(multi)
 *     return Y             # <<<<<<<<<<<<<<
 * 
 * # FIXME: Why this and not the numpy median? Check that this is faster.
 */
  Py_INCREF(__pyx_v_Y);
  __pyx_r = __pyx_v_Y;
  goto __pyx_L0;

  __pyx_r = Py_None; Py_INCREF(Py_None);
  goto __pyx_L0;
  __pyx_L1_error:;
  Py_XDECREF(__pyx_1);
  Py_XDECREF(__pyx_2);
  Py_XDECREF(__pyx_3);
  __Pyx_AddTraceback("neuroimaging.neurospin.utils.routines.quantile");
  __pyx_r = NULL;
  __pyx_L0:;
  Py_DECREF(__pyx_v_dims);
  Py_DECREF(__pyx_v_Y);
  return __pyx_r;
}

/* "d:\home\ar203069\bzr\nipy\dev-trunk-neurospin\neuroimaging\neurospin\utils\routines.pyx":68
 * 
 * # FIXME: Why this and not the numpy median? Check that this is faster.
 * def median(x, axis=0):             # <<<<<<<<<<<<<<
 *     """
 *     median(x, axis=0).
 */

static PyObject *__pyx_pf_12neuroimaging_9neurospin_5utils_8routines_median(PyObject *__pyx_self, PyObject *__pyx_args, PyObject *__pyx_kwds); /*proto*/
static char __pyx_doc_12neuroimaging_9neurospin_5utils_8routines_median[] = "\n    median(x, axis=0).\n    Equivalent to: quantile(x, ratio=0.5, interp=True, axis=axis).\n    ";
static PyObject *__pyx_pf_12neuroimaging_9neurospin_5utils_8routines_median(PyObject *__pyx_self, PyObject *__pyx_args, PyObject *__pyx_kwds) {
  PyObject *__pyx_v_x = 0;
  PyObject *__pyx_v_axis = 0;
  PyObject *__pyx_r;
  PyObject *__pyx_1 = 0;
  PyObject *__pyx_2 = 0;
  PyObject *__pyx_3 = 0;
  PyObject *__pyx_4 = 0;
  static PyObject **__pyx_pyargnames[] = {&__pyx_kp_x,&__pyx_kp_axis,0};
  __pyx_self = __pyx_self;
  __pyx_v_axis = __pyx_int_0;
  if (unlikely(__pyx_kwds)) {
    PyObject* values[2] = {0,0};
    Py_ssize_t kw_args = PyDict_Size(__pyx_kwds);
    switch (PyTuple_GET_SIZE(__pyx_args)) {
      case  2: values[1] = PyTuple_GET_ITEM(__pyx_args, 1);
      case  1: values[0] = PyTuple_GET_ITEM(__pyx_args, 0);
      case  0: break;
      default: goto __pyx_L5_argtuple_error;
    }
    switch (PyTuple_GET_SIZE(__pyx_args)) {
      case  0:
      values[0] = PyDict_GetItem(__pyx_kwds, __pyx_kp_x);
      if (likely(values[0])) kw_args--;
      else goto __pyx_L5_argtuple_error;
    }
    if (unlikely(kw_args > 0)) {
      if (unlikely(__Pyx_ParseOptionalKeywords(__pyx_kwds, __pyx_pyargnames, 0, values, PyTuple_GET_SIZE(__pyx_args), "median") < 0)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 68; __pyx_clineno = __LINE__; goto __pyx_L3_error;}
    }
    __pyx_v_x = values[0];
    if (values[1]) {
      __pyx_v_axis = values[1];
    }
  } else {
    switch (PyTuple_GET_SIZE(__pyx_args)) {
      case  2: __pyx_v_axis = PyTuple_GET_ITEM(__pyx_args, 1);
      case  1: __pyx_v_x = PyTuple_GET_ITEM(__pyx_args, 0);
      break;
      default: goto __pyx_L5_argtuple_error;
    }
  }
  goto __pyx_L4_argument_unpacking_done;
  __pyx_L5_argtuple_error:;
  __Pyx_RaiseArgtupleInvalid("median", 0, 1, 2, PyTuple_GET_SIZE(__pyx_args)); {__pyx_filename = __pyx_f[0]; __pyx_lineno = 68; __pyx_clineno = __LINE__; goto __pyx_L3_error;}
  __pyx_L3_error:;
  __Pyx_AddTraceback("neuroimaging.neurospin.utils.routines.median");
  return NULL;
  __pyx_L4_argument_unpacking_done:;

  /* "d:\home\ar203069\bzr\nipy\dev-trunk-neurospin\neuroimaging\neurospin\utils\routines.pyx":73
 *     Equivalent to: quantile(x, ratio=0.5, interp=True, axis=axis).
 *     """
 *     return quantile(x, axis=axis, ratio=0.5, interp=True)             # <<<<<<<<<<<<<<
 * 
 * 
 */
  __pyx_1 = __Pyx_GetName(__pyx_m, __pyx_kp_quantile); if (unlikely(!__pyx_1)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 73; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
  __pyx_2 = PyTuple_New(1); if (unlikely(!__pyx_2)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 73; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
  Py_INCREF(__pyx_v_x);
  PyTuple_SET_ITEM(__pyx_2, 0, __pyx_v_x);
  __pyx_3 = PyDict_New(); if (unlikely(!__pyx_3)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 73; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
  if (PyDict_SetItem(__pyx_3, __pyx_kp_axis, __pyx_v_axis) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 73; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
  __pyx_4 = PyFloat_FromDouble(0.5); if (unlikely(!__pyx_4)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 73; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
  if (PyDict_SetItem(__pyx_3, __pyx_kp_ratio, __pyx_4) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 73; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
  Py_DECREF(__pyx_4); __pyx_4 = 0;
  __pyx_4 = __Pyx_PyBool_FromLong(1); if (unlikely(!__pyx_4)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 73; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
  if (PyDict_SetItem(__pyx_3, __pyx_kp_interp, __pyx_4) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 73; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
  Py_DECREF(__pyx_4); __pyx_4 = 0;
  __pyx_4 = PyEval_CallObjectWithKeywords(__pyx_1, ((PyObject *)__pyx_2), ((PyObject *)__pyx_3)); if (unlikely(!__pyx_4)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 73; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
  Py_DECREF(__pyx_1); __pyx_1 = 0;
  Py_DECREF(((PyObject *)__pyx_2)); __pyx_2 = 0;
  Py_DECREF(((PyObject *)__pyx_3)); __pyx_3 = 0;
  __pyx_r = __pyx_4;
  __pyx_4 = 0;
  goto __pyx_L0;

  __pyx_r = Py_None; Py_INCREF(Py_None);
  goto __pyx_L0;
  __pyx_L1_error:;
  Py_XDECREF(__pyx_1);
  Py_XDECREF(__pyx_2);
  Py_XDECREF(__pyx_3);
  Py_XDECREF(__pyx_4);
  __Pyx_AddTraceback("neuroimaging.neurospin.utils.routines.median");
  __pyx_r = NULL;
  __pyx_L0:;
  return __pyx_r;
}

/* "d:\home\ar203069\bzr\nipy\dev-trunk-neurospin\neuroimaging\neurospin\utils\routines.pyx":76
 * 
 * 
 * def mahalanobis(X, VX):             # <<<<<<<<<<<<<<
 *     """
 *     d2 = mahalanobis(X, VX).
 */

static PyObject *__pyx_pf_12neuroimaging_9neurospin_5utils_8routines_mahalanobis(PyObject *__pyx_self, PyObject *__pyx_args, PyObject *__pyx_kwds); /*proto*/
static char __pyx_doc_12neuroimaging_9neurospin_5utils_8routines_mahalanobis[] = "\n    d2 = mahalanobis(X, VX).\n    axis == 0 assumed. If X is shaped (d,K), VX must be shaped (d,d,K). \n    ";
static PyObject *__pyx_pf_12neuroimaging_9neurospin_5utils_8routines_mahalanobis(PyObject *__pyx_self, PyObject *__pyx_args, PyObject *__pyx_kwds) {
  PyObject *__pyx_v_X = 0;
  PyObject *__pyx_v_VX = 0;
  fff_vector *__pyx_v_x;
  fff_vector *__pyx_v_vx;
  fff_vector *__pyx_v_x_tmp;
  fff_vector *__pyx_v_vx_tmp;
  fff_vector *__pyx_v_d2;
  fff_matrix __pyx_v_Sx;
  fff_matrix *__pyx_v_Sx_tmp;
  fffpy_multi_iterator *__pyx_v_multi;
  int __pyx_v_axis;
  int __pyx_v_n;
  PyObject *__pyx_v_dims;
  PyObject *__pyx_v_dim;
  PyObject *__pyx_v_D2;
  PyObject *__pyx_v_VX_flat;
  PyObject *__pyx_r;
  PyObject *__pyx_1 = 0;
  PyObject *__pyx_2 = 0;
  PyObject *__pyx_3 = 0;
  PyObject *__pyx_4 = 0;
  int __pyx_5;
  int __pyx_6;
  PyObject *__pyx_t_1 = NULL;
  static PyObject **__pyx_pyargnames[] = {&__pyx_kp_X,&__pyx_kp_VX,0};
  __pyx_self = __pyx_self;
  if (unlikely(__pyx_kwds)) {
    PyObject* values[2] = {0,0};
    Py_ssize_t kw_args = PyDict_Size(__pyx_kwds);
    switch (PyTuple_GET_SIZE(__pyx_args)) {
      case  2: values[1] = PyTuple_GET_ITEM(__pyx_args, 1);
      case  1: values[0] = PyTuple_GET_ITEM(__pyx_args, 0);
      case  0: break;
      default: goto __pyx_L5_argtuple_error;
    }
    switch (PyTuple_GET_SIZE(__pyx_args)) {
      case  0:
      values[0] = PyDict_GetItem(__pyx_kwds, __pyx_kp_X);
      if (likely(values[0])) kw_args--;
      else goto __pyx_L5_argtuple_error;
      case  1:
      values[1] = PyDict_GetItem(__pyx_kwds, __pyx_kp_VX);
      if (likely(values[1])) kw_args--;
      else {
        __Pyx_RaiseArgtupleInvalid("mahalanobis", 1, 2, 2, 1); {__pyx_filename = __pyx_f[0]; __pyx_lineno = 76; __pyx_clineno = __LINE__; goto __pyx_L3_error;}
      }
    }
    if (unlikely(kw_args > 0)) {
      if (unlikely(__Pyx_ParseOptionalKeywords(__pyx_kwds, __pyx_pyargnames, 0, values, PyTuple_GET_SIZE(__pyx_args), "mahalanobis") < 0)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 76; __pyx_clineno = __LINE__; goto __pyx_L3_error;}
    }
    __pyx_v_X = values[0];
    __pyx_v_VX = values[1];
  } else if (PyTuple_GET_SIZE(__pyx_args) != 2) {
    goto __pyx_L5_argtuple_error;
  } else {
    __pyx_v_X = PyTuple_GET_ITEM(__pyx_args, 0);
    __pyx_v_VX = PyTuple_GET_ITEM(__pyx_args, 1);
  }
  goto __pyx_L4_argument_unpacking_done;
  __pyx_L5_argtuple_error:;
  __Pyx_RaiseArgtupleInvalid("mahalanobis", 1, 2, 2, PyTuple_GET_SIZE(__pyx_args)); {__pyx_filename = __pyx_f[0]; __pyx_lineno = 76; __pyx_clineno = __LINE__; goto __pyx_L3_error;}
  __pyx_L3_error:;
  __Pyx_AddTraceback("neuroimaging.neurospin.utils.routines.mahalanobis");
  return NULL;
  __pyx_L4_argument_unpacking_done:;
  __pyx_v_dims = Py_None; Py_INCREF(Py_None);
  __pyx_v_dim = Py_None; Py_INCREF(Py_None);
  __pyx_v_D2 = Py_None; Py_INCREF(Py_None);
  __pyx_v_VX_flat = Py_None; Py_INCREF(Py_None);

  /* "d:\home\ar203069\bzr\nipy\dev-trunk-neurospin\neuroimaging\neurospin\utils\routines.pyx":85
 *     cdef fff_matrix *Sx_tmp
 *     cdef fffpy_multi_iterator* multi
 *     cdef int axis=0, n             # <<<<<<<<<<<<<<
 * 
 *     # Allocate output array
 */
  __pyx_v_axis = 0;

  /* "d:\home\ar203069\bzr\nipy\dev-trunk-neurospin\neuroimaging\neurospin\utils\routines.pyx":88
 * 
 *     # Allocate output array
 *     dims = list(X.shape)             # <<<<<<<<<<<<<<
 *     dim = dims[0]
 *     dims[0] = 1
 */
  __pyx_1 = PyObject_GetAttr(__pyx_v_X, __pyx_kp_shape); if (unlikely(!__pyx_1)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 88; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
  __pyx_2 = PyTuple_New(1); if (unlikely(!__pyx_2)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 88; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
  PyTuple_SET_ITEM(__pyx_2, 0, __pyx_1);
  __pyx_1 = 0;
  __pyx_1 = PyObject_Call(((PyObject *)((PyObject*)&PyList_Type)), ((PyObject *)__pyx_2), NULL); if (unlikely(!__pyx_1)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 88; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
  Py_DECREF(((PyObject *)__pyx_2)); __pyx_2 = 0;
  Py_DECREF(__pyx_v_dims);
  __pyx_v_dims = __pyx_1;
  __pyx_1 = 0;

  /* "d:\home\ar203069\bzr\nipy\dev-trunk-neurospin\neuroimaging\neurospin\utils\routines.pyx":89
 *     # Allocate output array
 *     dims = list(X.shape)
 *     dim = dims[0]             # <<<<<<<<<<<<<<
 *     dims[0] = 1
 *     D2 = np.zeros(dims)
 */
  __pyx_2 = __Pyx_GetItemInt(__pyx_v_dims, 0, 0); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 89; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
  Py_DECREF(__pyx_v_dim);
  __pyx_v_dim = __pyx_2;
  __pyx_2 = 0;

  /* "d:\home\ar203069\bzr\nipy\dev-trunk-neurospin\neuroimaging\neurospin\utils\routines.pyx":90
 *     dims = list(X.shape)
 *     dim = dims[0]
 *     dims[0] = 1             # <<<<<<<<<<<<<<
 *     D2 = np.zeros(dims)
 * 
 */
  if (__Pyx_SetItemInt(__pyx_v_dims, 0, __pyx_int_1, 0) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 90; __pyx_clineno = __LINE__; goto __pyx_L1_error;}

  /* "d:\home\ar203069\bzr\nipy\dev-trunk-neurospin\neuroimaging\neurospin\utils\routines.pyx":91
 *     dim = dims[0]
 *     dims[0] = 1
 *     D2 = np.zeros(dims)             # <<<<<<<<<<<<<<
 * 
 *     # Flatten input variance array
 */
  __pyx_1 = __Pyx_GetName(__pyx_m, __pyx_kp_np); if (unlikely(!__pyx_1)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 91; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
  __pyx_2 = PyObject_GetAttr(__pyx_1, __pyx_kp_zeros); if (unlikely(!__pyx_2)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 91; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
  Py_DECREF(__pyx_1); __pyx_1 = 0;
  __pyx_1 = PyTuple_New(1); if (unlikely(!__pyx_1)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 91; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
  Py_INCREF(__pyx_v_dims);
  PyTuple_SET_ITEM(__pyx_1, 0, __pyx_v_dims);
  __pyx_3 = PyObject_Call(__pyx_2, ((PyObject *)__pyx_1), NULL); if (unlikely(!__pyx_3)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 91; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
  Py_DECREF(__pyx_2); __pyx_2 = 0;
  Py_DECREF(((PyObject *)__pyx_1)); __pyx_1 = 0;
  Py_DECREF(__pyx_v_D2);
  __pyx_v_D2 = __pyx_3;
  __pyx_3 = 0;

  /* "d:\home\ar203069\bzr\nipy\dev-trunk-neurospin\neuroimaging\neurospin\utils\routines.pyx":94
 * 
 *     # Flatten input variance array
 *     VX_flat = VX.reshape( [dim*dim]+list(VX.shape[2:]) )             # <<<<<<<<<<<<<<
 * 
 *     # Create a new array iterator
 */
  __pyx_2 = PyObject_GetAttr(__pyx_v_VX, __pyx_kp_reshape); if (unlikely(!__pyx_2)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 94; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
  __pyx_t_1 = PyNumber_Multiply(__pyx_v_dim, __pyx_v_dim); if (unlikely(!__pyx_t_1)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 94; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
  __pyx_1 = PyList_New(1); if (unlikely(!__pyx_1)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 94; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
  PyList_SET_ITEM(__pyx_1, 0, __pyx_t_1);
  __pyx_t_1 = 0;
  __pyx_3 = PyObject_GetAttr(__pyx_v_VX, __pyx_kp_shape); if (unlikely(!__pyx_3)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 94; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
  __pyx_4 = PySequence_GetSlice(__pyx_3, 2, PY_SSIZE_T_MAX); if (unlikely(!__pyx_4)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 94; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
  Py_DECREF(__pyx_3); __pyx_3 = 0;
  __pyx_3 = PyTuple_New(1); if (unlikely(!__pyx_3)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 94; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
  PyTuple_SET_ITEM(__pyx_3, 0, __pyx_4);
  __pyx_4 = 0;
  __pyx_4 = PyObject_Call(((PyObject *)((PyObject*)&PyList_Type)), ((PyObject *)__pyx_3), NULL); if (unlikely(!__pyx_4)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 94; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
  Py_DECREF(((PyObject *)__pyx_3)); __pyx_3 = 0;
  __pyx_t_1 = PyNumber_Add(((PyObject *)__pyx_1), __pyx_4); if (unlikely(!__pyx_t_1)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 94; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
  Py_DECREF(((PyObject *)__pyx_1)); __pyx_1 = 0;
  Py_DECREF(__pyx_4); __pyx_4 = 0;
  __pyx_3 = PyTuple_New(1); if (unlikely(!__pyx_3)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 94; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
  PyTuple_SET_ITEM(__pyx_3, 0, __pyx_t_1);
  __pyx_t_1 = 0;
  __pyx_1 = PyObject_Call(__pyx_2, ((PyObject *)__pyx_3), NULL); if (unlikely(!__pyx_1)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 94; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
  Py_DECREF(__pyx_2); __pyx_2 = 0;
  Py_DECREF(((PyObject *)__pyx_3)); __pyx_3 = 0;
  Py_DECREF(__pyx_v_VX_flat);
  __pyx_v_VX_flat = __pyx_1;
  __pyx_1 = 0;

  /* "d:\home\ar203069\bzr\nipy\dev-trunk-neurospin\neuroimaging\neurospin\utils\routines.pyx":97
 * 
 *     # Create a new array iterator
 *     multi = fffpy_multi_iterator_new(3, axis, <void*>X, <void*>VX_flat, <void*>D2)             # <<<<<<<<<<<<<<
 * 
 *     # Allocate local structures
 */
  __pyx_v_multi = fffpy_multi_iterator_new(3, __pyx_v_axis, ((void *)__pyx_v_X), ((void *)__pyx_v_VX_flat), ((void *)__pyx_v_D2));

  /* "d:\home\ar203069\bzr\nipy\dev-trunk-neurospin\neuroimaging\neurospin\utils\routines.pyx":100
 * 
 *     # Allocate local structures
 *     n = <int> X.shape[axis]             # <<<<<<<<<<<<<<
 *     x_tmp = fff_vector_new(n)
 *     vx_tmp = fff_vector_new(n*n)
 */
  __pyx_4 = PyObject_GetAttr(__pyx_v_X, __pyx_kp_shape); if (unlikely(!__pyx_4)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 100; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
  __pyx_2 = __Pyx_GetItemInt(__pyx_4, __pyx_v_axis, 0); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 100; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
  Py_DECREF(__pyx_4); __pyx_4 = 0;
  __pyx_5 = __pyx_PyInt_int(__pyx_2); if (unlikely((__pyx_5 == (int)-1) && PyErr_Occurred())) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 100; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
  Py_DECREF(__pyx_2); __pyx_2 = 0;
  __pyx_v_n = ((int)__pyx_5);

  /* "d:\home\ar203069\bzr\nipy\dev-trunk-neurospin\neuroimaging\neurospin\utils\routines.pyx":101
 *     # Allocate local structures
 *     n = <int> X.shape[axis]
 *     x_tmp = fff_vector_new(n)             # <<<<<<<<<<<<<<
 *     vx_tmp = fff_vector_new(n*n)
 *     Sx_tmp = fff_matrix_new(n, n)
 */
  __pyx_v_x_tmp = fff_vector_new(__pyx_v_n);

  /* "d:\home\ar203069\bzr\nipy\dev-trunk-neurospin\neuroimaging\neurospin\utils\routines.pyx":102
 *     n = <int> X.shape[axis]
 *     x_tmp = fff_vector_new(n)
 *     vx_tmp = fff_vector_new(n*n)             # <<<<<<<<<<<<<<
 *     Sx_tmp = fff_matrix_new(n, n)
 * 
 */
  __pyx_v_vx_tmp = fff_vector_new((__pyx_v_n * __pyx_v_n));

  /* "d:\home\ar203069\bzr\nipy\dev-trunk-neurospin\neuroimaging\neurospin\utils\routines.pyx":103
 *     x_tmp = fff_vector_new(n)
 *     vx_tmp = fff_vector_new(n*n)
 *     Sx_tmp = fff_matrix_new(n, n)             # <<<<<<<<<<<<<<
 * 
 *     # Create vector views on X, VX_flat and D2
 */
  __pyx_v_Sx_tmp = fff_matrix_new(__pyx_v_n, __pyx_v_n);

  /* "d:\home\ar203069\bzr\nipy\dev-trunk-neurospin\neuroimaging\neurospin\utils\routines.pyx":106
 * 
 *     # Create vector views on X, VX_flat and D2
 *     x = multi.vector[0]             # <<<<<<<<<<<<<<
 *     vx = multi.vector[1]
 *     d2 = multi.vector[2]
 */
  __pyx_v_x = (__pyx_v_multi->vector[0]);

  /* "d:\home\ar203069\bzr\nipy\dev-trunk-neurospin\neuroimaging\neurospin\utils\routines.pyx":107
 *     # Create vector views on X, VX_flat and D2
 *     x = multi.vector[0]
 *     vx = multi.vector[1]             # <<<<<<<<<<<<<<
 *     d2 = multi.vector[2]
 * 
 */
  __pyx_v_vx = (__pyx_v_multi->vector[1]);

  /* "d:\home\ar203069\bzr\nipy\dev-trunk-neurospin\neuroimaging\neurospin\utils\routines.pyx":108
 *     x = multi.vector[0]
 *     vx = multi.vector[1]
 *     d2 = multi.vector[2]             # <<<<<<<<<<<<<<
 * 
 *     # Loop
 */
  __pyx_v_d2 = (__pyx_v_multi->vector[2]);

  /* "d:\home\ar203069\bzr\nipy\dev-trunk-neurospin\neuroimaging\neurospin\utils\routines.pyx":111
 * 
 *     # Loop
 *     while(multi.index < multi.size):             # <<<<<<<<<<<<<<
 *         fff_vector_memcpy(x_tmp, x)
 *         fff_vector_memcpy(vx_tmp, vx)
 */
  while (1) {
    __pyx_6 = (__pyx_v_multi->index < __pyx_v_multi->size);
    if (!__pyx_6) break;

    /* "d:\home\ar203069\bzr\nipy\dev-trunk-neurospin\neuroimaging\neurospin\utils\routines.pyx":112
 *     # Loop
 *     while(multi.index < multi.size):
 *         fff_vector_memcpy(x_tmp, x)             # <<<<<<<<<<<<<<
 *         fff_vector_memcpy(vx_tmp, vx)
 *         Sx = fff_matrix_view(vx_tmp.data, n, n, n) # OK because vx_tmp is contiguous
 */
    fff_vector_memcpy(__pyx_v_x_tmp, __pyx_v_x);

    /* "d:\home\ar203069\bzr\nipy\dev-trunk-neurospin\neuroimaging\neurospin\utils\routines.pyx":113
 *     while(multi.index < multi.size):
 *         fff_vector_memcpy(x_tmp, x)
 *         fff_vector_memcpy(vx_tmp, vx)             # <<<<<<<<<<<<<<
 *         Sx = fff_matrix_view(vx_tmp.data, n, n, n) # OK because vx_tmp is contiguous
 *         d2.data[0] = fff_mahalanobis(x_tmp, &Sx, Sx_tmp)
 */
    fff_vector_memcpy(__pyx_v_vx_tmp, __pyx_v_vx);

    /* "d:\home\ar203069\bzr\nipy\dev-trunk-neurospin\neuroimaging\neurospin\utils\routines.pyx":114
 *         fff_vector_memcpy(x_tmp, x)
 *         fff_vector_memcpy(vx_tmp, vx)
 *         Sx = fff_matrix_view(vx_tmp.data, n, n, n) # OK because vx_tmp is contiguous             # <<<<<<<<<<<<<<
 *         d2.data[0] = fff_mahalanobis(x_tmp, &Sx, Sx_tmp)
 *         fffpy_multi_iterator_update(multi)
 */
    __pyx_v_Sx = fff_matrix_view(__pyx_v_vx_tmp->data, __pyx_v_n, __pyx_v_n, __pyx_v_n);

    /* "d:\home\ar203069\bzr\nipy\dev-trunk-neurospin\neuroimaging\neurospin\utils\routines.pyx":115
 *         fff_vector_memcpy(vx_tmp, vx)
 *         Sx = fff_matrix_view(vx_tmp.data, n, n, n) # OK because vx_tmp is contiguous
 *         d2.data[0] = fff_mahalanobis(x_tmp, &Sx, Sx_tmp)             # <<<<<<<<<<<<<<
 *         fffpy_multi_iterator_update(multi)
 * 
 */
    (__pyx_v_d2->data[0]) = fff_mahalanobis(__pyx_v_x_tmp, (&__pyx_v_Sx), __pyx_v_Sx_tmp);

    /* "d:\home\ar203069\bzr\nipy\dev-trunk-neurospin\neuroimaging\neurospin\utils\routines.pyx":116
 *         Sx = fff_matrix_view(vx_tmp.data, n, n, n) # OK because vx_tmp is contiguous
 *         d2.data[0] = fff_mahalanobis(x_tmp, &Sx, Sx_tmp)
 *         fffpy_multi_iterator_update(multi)             # <<<<<<<<<<<<<<
 * 
 *     # Delete local structs and views
 */
    fffpy_multi_iterator_update(__pyx_v_multi);
  }

  /* "d:\home\ar203069\bzr\nipy\dev-trunk-neurospin\neuroimaging\neurospin\utils\routines.pyx":119
 * 
 *     # Delete local structs and views
 *     fff_vector_delete(x_tmp)             # <<<<<<<<<<<<<<
 *     fff_vector_delete(vx_tmp)
 *     fff_matrix_delete(Sx_tmp)
 */
  fff_vector_delete(__pyx_v_x_tmp);

  /* "d:\home\ar203069\bzr\nipy\dev-trunk-neurospin\neuroimaging\neurospin\utils\routines.pyx":120
 *     # Delete local structs and views
 *     fff_vector_delete(x_tmp)
 *     fff_vector_delete(vx_tmp)             # <<<<<<<<<<<<<<
 *     fff_matrix_delete(Sx_tmp)
 *     fffpy_multi_iterator_delete(multi)
 */
  fff_vector_delete(__pyx_v_vx_tmp);

  /* "d:\home\ar203069\bzr\nipy\dev-trunk-neurospin\neuroimaging\neurospin\utils\routines.pyx":121
 *     fff_vector_delete(x_tmp)
 *     fff_vector_delete(vx_tmp)
 *     fff_matrix_delete(Sx_tmp)             # <<<<<<<<<<<<<<
 *     fffpy_multi_iterator_delete(multi)
 * 
 */
  fff_matrix_delete(__pyx_v_Sx_tmp);

  /* "d:\home\ar203069\bzr\nipy\dev-trunk-neurospin\neuroimaging\neurospin\utils\routines.pyx":122
 *     fff_vector_delete(vx_tmp)
 *     fff_matrix_delete(Sx_tmp)
 *     fffpy_multi_iterator_delete(multi)             # <<<<<<<<<<<<<<
 * 
 *     # Return
 */
  fffpy_multi_iterator_delete(__pyx_v_multi);

  /* "d:\home\ar203069\bzr\nipy\dev-trunk-neurospin\neuroimaging\neurospin\utils\routines.pyx":125
 * 
 *     # Return
 *     D2 = D2.reshape(VX.shape[2:])             # <<<<<<<<<<<<<<
 *     return D2
 * 
 */
  __pyx_3 = PyObject_GetAttr(__pyx_v_D2, __pyx_kp_reshape); if (unlikely(!__pyx_3)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 125; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
  __pyx_1 = PyObject_GetAttr(__pyx_v_VX, __pyx_kp_shape); if (unlikely(!__pyx_1)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 125; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
  __pyx_4 = PySequence_GetSlice(__pyx_1, 2, PY_SSIZE_T_MAX); if (unlikely(!__pyx_4)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 125; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
  Py_DECREF(__pyx_1); __pyx_1 = 0;
  __pyx_2 = PyTuple_New(1); if (unlikely(!__pyx_2)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 125; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
  PyTuple_SET_ITEM(__pyx_2, 0, __pyx_4);
  __pyx_4 = 0;
  __pyx_1 = PyObject_Call(__pyx_3, ((PyObject *)__pyx_2), NULL); if (unlikely(!__pyx_1)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 125; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
  Py_DECREF(__pyx_3); __pyx_3 = 0;
  Py_DECREF(((PyObject *)__pyx_2)); __pyx_2 = 0;
  Py_DECREF(__pyx_v_D2);
  __pyx_v_D2 = __pyx_1;
  __pyx_1 = 0;

  /* "d:\home\ar203069\bzr\nipy\dev-trunk-neurospin\neuroimaging\neurospin\utils\routines.pyx":126
 *     # Return
 *     D2 = D2.reshape(VX.shape[2:])
 *     return D2             # <<<<<<<<<<<<<<
 * 
 * 
 */
  Py_INCREF(__pyx_v_D2);
  __pyx_r = __pyx_v_D2;
  goto __pyx_L0;

  __pyx_r = Py_None; Py_INCREF(Py_None);
  goto __pyx_L0;
  __pyx_L1_error:;
  Py_XDECREF(__pyx_1);
  Py_XDECREF(__pyx_2);
  Py_XDECREF(__pyx_3);
  Py_XDECREF(__pyx_4);
  __Pyx_AddTraceback("neuroimaging.neurospin.utils.routines.mahalanobis");
  __pyx_r = NULL;
  __pyx_L0:;
  Py_DECREF(__pyx_v_dims);
  Py_DECREF(__pyx_v_dim);
  Py_DECREF(__pyx_v_D2);
  Py_DECREF(__pyx_v_VX_flat);
  return __pyx_r;
}

/* "d:\home\ar203069\bzr\nipy\dev-trunk-neurospin\neuroimaging\neurospin\utils\routines.pyx":129
 * 
 * 
 * def permutations(unsigned int n, unsigned int m=1, unsigned long magic=0):             # <<<<<<<<<<<<<<
 *     """
 *     P = permutations(n, m=1, magic=0).
 */

static PyObject *__pyx_pf_12neuroimaging_9neurospin_5utils_8routines_permutations(PyObject *__pyx_self, PyObject *__pyx_args, PyObject *__pyx_kwds); /*proto*/
static char __pyx_doc_12neuroimaging_9neurospin_5utils_8routines_permutations[] = "\n    P = permutations(n, m=1, magic=0).\n    Generate m permutations from [0..n[.\n    ";
static PyObject *__pyx_pf_12neuroimaging_9neurospin_5utils_8routines_permutations(PyObject *__pyx_self, PyObject *__pyx_args, PyObject *__pyx_kwds) {
  unsigned int __pyx_v_n;
  unsigned int __pyx_v_m;
  unsigned long __pyx_v_magic;
  fff_array *__pyx_v_p;
  fff_array *__pyx_v_pi;
  fff_array __pyx_v_pi_view;
  unsigned int __pyx_v_i;
  PyObject *__pyx_v_P;
  PyObject *__pyx_r;
  PyObject *__pyx_1 = 0;
  static PyObject **__pyx_pyargnames[] = {&__pyx_kp_n,&__pyx_kp_m,&__pyx_kp_magic,0};
  __pyx_self = __pyx_self;
  __pyx_v_m = 1;
  __pyx_v_magic = 0;
  if (unlikely(__pyx_kwds)) {
    PyObject* values[3] = {0,0,0};
    Py_ssize_t kw_args = PyDict_Size(__pyx_kwds);
    switch (PyTuple_GET_SIZE(__pyx_args)) {
      case  3: values[2] = PyTuple_GET_ITEM(__pyx_args, 2);
      case  2: values[1] = PyTuple_GET_ITEM(__pyx_args, 1);
      case  1: values[0] = PyTuple_GET_ITEM(__pyx_args, 0);
      case  0: break;
      default: goto __pyx_L5_argtuple_error;
    }
    switch (PyTuple_GET_SIZE(__pyx_args)) {
      case  0:
      values[0] = PyDict_GetItem(__pyx_kwds, __pyx_kp_n);
      if (likely(values[0])) kw_args--;
      else goto __pyx_L5_argtuple_error;
    }
    if (unlikely(kw_args > 0)) {
      if (unlikely(__Pyx_ParseOptionalKeywords(__pyx_kwds, __pyx_pyargnames, 0, values, PyTuple_GET_SIZE(__pyx_args), "permutations") < 0)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 129; __pyx_clineno = __LINE__; goto __pyx_L3_error;}
    }
    __pyx_v_n = PyInt_AsUnsignedLongMask(values[0]); if (unlikely((__pyx_v_n == (unsigned int)-1) && PyErr_Occurred())) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 129; __pyx_clineno = __LINE__; goto __pyx_L3_error;}
    if (values[1]) {
      __pyx_v_m = PyInt_AsUnsignedLongMask(values[1]); if (unlikely((__pyx_v_m == (unsigned int)-1) && PyErr_Occurred())) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 129; __pyx_clineno = __LINE__; goto __pyx_L3_error;}
    }
    if (values[2]) {
      __pyx_v_magic = PyInt_AsUnsignedLongMask(values[2]); if (unlikely((__pyx_v_magic == (unsigned long)-1) && PyErr_Occurred())) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 129; __pyx_clineno = __LINE__; goto __pyx_L3_error;}
    }
  } else {
    switch (PyTuple_GET_SIZE(__pyx_args)) {
      case  3: __pyx_v_magic = PyInt_AsUnsignedLongMask(PyTuple_GET_ITEM(__pyx_args, 2)); if (unlikely((__pyx_v_magic == (unsigned long)-1) && PyErr_Occurred())) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 129; __pyx_clineno = __LINE__; goto __pyx_L3_error;}
      case  2: __pyx_v_m = PyInt_AsUnsignedLongMask(PyTuple_GET_ITEM(__pyx_args, 1)); if (unlikely((__pyx_v_m == (unsigned int)-1) && PyErr_Occurred())) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 129; __pyx_clineno = __LINE__; goto __pyx_L3_error;}
      case  1: __pyx_v_n = PyInt_AsUnsignedLongMask(PyTuple_GET_ITEM(__pyx_args, 0)); if (unlikely((__pyx_v_n == (unsigned int)-1) && PyErr_Occurred())) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 129; __pyx_clineno = __LINE__; goto __pyx_L3_error;}
      break;
      default: goto __pyx_L5_argtuple_error;
    }
  }
  goto __pyx_L4_argument_unpacking_done;
  __pyx_L5_argtuple_error:;
  __Pyx_RaiseArgtupleInvalid("permutations", 0, 1, 3, PyTuple_GET_SIZE(__pyx_args)); {__pyx_filename = __pyx_f[0]; __pyx_lineno = 129; __pyx_clineno = __LINE__; goto __pyx_L3_error;}
  __pyx_L3_error:;
  __Pyx_AddTraceback("neuroimaging.neurospin.utils.routines.permutations");
  return NULL;
  __pyx_L4_argument_unpacking_done:;
  __pyx_v_P = Py_None; Py_INCREF(Py_None);

  /* "d:\home\ar203069\bzr\nipy\dev-trunk-neurospin\neuroimaging\neurospin\utils\routines.pyx":137
 *     cdef fff_array pi_view
 *     cdef unsigned int i
 *     p = fff_array_new2d(FFF_UINT, n, m)             # <<<<<<<<<<<<<<
 *     pi = fff_array_new1d(FFF_UINT, n) ## contiguous, dims=(n,1,1,1)
 * 
 */
  __pyx_v_p = fff_array_new2d(FFF_UINT, __pyx_v_n, __pyx_v_m);

  /* "d:\home\ar203069\bzr\nipy\dev-trunk-neurospin\neuroimaging\neurospin\utils\routines.pyx":138
 *     cdef unsigned int i
 *     p = fff_array_new2d(FFF_UINT, n, m)
 *     pi = fff_array_new1d(FFF_UINT, n) ## contiguous, dims=(n,1,1,1)             # <<<<<<<<<<<<<<
 * 
 *     for i from 0 <= i < m:
 */
  __pyx_v_pi = fff_array_new1d(FFF_UINT, __pyx_v_n);

  /* "d:\home\ar203069\bzr\nipy\dev-trunk-neurospin\neuroimaging\neurospin\utils\routines.pyx":140
 *     pi = fff_array_new1d(FFF_UINT, n) ## contiguous, dims=(n,1,1,1)
 * 
 *     for i from 0 <= i < m:             # <<<<<<<<<<<<<<
 *         fff_permutation(<unsigned int*>pi.data, n, magic+i)
 *         pi_view = fff_array_get_block2d(p, 0, n-1, 1, i, i, 1) ## dims=(n,1,1,1)
 */
  for (__pyx_v_i = 0; __pyx_v_i < __pyx_v_m; __pyx_v_i++) {

    /* "d:\home\ar203069\bzr\nipy\dev-trunk-neurospin\neuroimaging\neurospin\utils\routines.pyx":141
 * 
 *     for i from 0 <= i < m:
 *         fff_permutation(<unsigned int*>pi.data, n, magic+i)             # <<<<<<<<<<<<<<
 *         pi_view = fff_array_get_block2d(p, 0, n-1, 1, i, i, 1) ## dims=(n,1,1,1)
 *         fff_array_copy(&pi_view, pi)
 */
    fff_permutation(((unsigned int *)__pyx_v_pi->data), __pyx_v_n, (__pyx_v_magic + __pyx_v_i));

    /* "d:\home\ar203069\bzr\nipy\dev-trunk-neurospin\neuroimaging\neurospin\utils\routines.pyx":142
 *     for i from 0 <= i < m:
 *         fff_permutation(<unsigned int*>pi.data, n, magic+i)
 *         pi_view = fff_array_get_block2d(p, 0, n-1, 1, i, i, 1) ## dims=(n,1,1,1)             # <<<<<<<<<<<<<<
 *         fff_array_copy(&pi_view, pi)
 * 
 */
    __pyx_v_pi_view = fff_array_get_block2d(__pyx_v_p, 0, (__pyx_v_n - 1), 1, __pyx_v_i, __pyx_v_i, 1);

    /* "d:\home\ar203069\bzr\nipy\dev-trunk-neurospin\neuroimaging\neurospin\utils\routines.pyx":143
 *         fff_permutation(<unsigned int*>pi.data, n, magic+i)
 *         pi_view = fff_array_get_block2d(p, 0, n-1, 1, i, i, 1) ## dims=(n,1,1,1)
 *         fff_array_copy(&pi_view, pi)             # <<<<<<<<<<<<<<
 * 
 *     P = fff_array_toPyArray(p)
 */
    fff_array_copy((&__pyx_v_pi_view), __pyx_v_pi);
  }

  /* "d:\home\ar203069\bzr\nipy\dev-trunk-neurospin\neuroimaging\neurospin\utils\routines.pyx":145
 *         fff_array_copy(&pi_view, pi)
 * 
 *     P = fff_array_toPyArray(p)             # <<<<<<<<<<<<<<
 *     return P
 * 
 */
  __pyx_1 = ((PyObject *)fff_array_toPyArray(__pyx_v_p)); if (unlikely(!__pyx_1)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 145; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
  Py_DECREF(__pyx_v_P);
  __pyx_v_P = __pyx_1;
  __pyx_1 = 0;

  /* "d:\home\ar203069\bzr\nipy\dev-trunk-neurospin\neuroimaging\neurospin\utils\routines.pyx":146
 * 
 *     P = fff_array_toPyArray(p)
 *     return P             # <<<<<<<<<<<<<<
 * 
 * 
 */
  Py_INCREF(__pyx_v_P);
  __pyx_r = __pyx_v_P;
  goto __pyx_L0;

  __pyx_r = Py_None; Py_INCREF(Py_None);
  goto __pyx_L0;
  __pyx_L1_error:;
  Py_XDECREF(__pyx_1);
  __Pyx_AddTraceback("neuroimaging.neurospin.utils.routines.permutations");
  __pyx_r = NULL;
  __pyx_L0:;
  Py_DECREF(__pyx_v_P);
  return __pyx_r;
}

/* "d:\home\ar203069\bzr\nipy\dev-trunk-neurospin\neuroimaging\neurospin\utils\routines.pyx":149
 * 
 * 
 * def combinations(unsigned int k, unsigned int n, unsigned int m=1, unsigned long magic=0):             # <<<<<<<<<<<<<<
 *     """
 *     P = combinations(k, n, m=1, magic=0).
 */

static PyObject *__pyx_pf_12neuroimaging_9neurospin_5utils_8routines_combinations(PyObject *__pyx_self, PyObject *__pyx_args, PyObject *__pyx_kwds); /*proto*/
static char __pyx_doc_12neuroimaging_9neurospin_5utils_8routines_combinations[] = "\n    P = combinations(k, n, m=1, magic=0).\n    Generate m combinations of k elements  from [0..n[.\n    ";
static PyObject *__pyx_pf_12neuroimaging_9neurospin_5utils_8routines_combinations(PyObject *__pyx_self, PyObject *__pyx_args, PyObject *__pyx_kwds) {
  unsigned int __pyx_v_k;
  unsigned int __pyx_v_n;
  unsigned int __pyx_v_m;
  unsigned long __pyx_v_magic;
  fff_array *__pyx_v_p;
  fff_array *__pyx_v_pi;
  fff_array __pyx_v_pi_view;
  unsigned int __pyx_v_i;
  PyObject *__pyx_v_C;
  PyObject *__pyx_r;
  PyObject *__pyx_1 = 0;
  static PyObject **__pyx_pyargnames[] = {&__pyx_kp_k,&__pyx_kp_n,&__pyx_kp_m,&__pyx_kp_magic,0};
  __pyx_self = __pyx_self;
  __pyx_v_m = 1;
  __pyx_v_magic = 0;
  if (unlikely(__pyx_kwds)) {
    PyObject* values[4] = {0,0,0,0};
    Py_ssize_t kw_args = PyDict_Size(__pyx_kwds);
    switch (PyTuple_GET_SIZE(__pyx_args)) {
      case  4: values[3] = PyTuple_GET_ITEM(__pyx_args, 3);
      case  3: values[2] = PyTuple_GET_ITEM(__pyx_args, 2);
      case  2: values[1] = PyTuple_GET_ITEM(__pyx_args, 1);
      case  1: values[0] = PyTuple_GET_ITEM(__pyx_args, 0);
      case  0: break;
      default: goto __pyx_L5_argtuple_error;
    }
    switch (PyTuple_GET_SIZE(__pyx_args)) {
      case  0:
      values[0] = PyDict_GetItem(__pyx_kwds, __pyx_kp_k);
      if (likely(values[0])) kw_args--;
      else goto __pyx_L5_argtuple_error;
      case  1:
      values[1] = PyDict_GetItem(__pyx_kwds, __pyx_kp_n);
      if (likely(values[1])) kw_args--;
      else {
        __Pyx_RaiseArgtupleInvalid("combinations", 0, 2, 4, 1); {__pyx_filename = __pyx_f[0]; __pyx_lineno = 149; __pyx_clineno = __LINE__; goto __pyx_L3_error;}
      }
    }
    if (unlikely(kw_args > 0)) {
      if (unlikely(__Pyx_ParseOptionalKeywords(__pyx_kwds, __pyx_pyargnames, 0, values, PyTuple_GET_SIZE(__pyx_args), "combinations") < 0)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 149; __pyx_clineno = __LINE__; goto __pyx_L3_error;}
    }
    __pyx_v_k = PyInt_AsUnsignedLongMask(values[0]); if (unlikely((__pyx_v_k == (unsigned int)-1) && PyErr_Occurred())) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 149; __pyx_clineno = __LINE__; goto __pyx_L3_error;}
    __pyx_v_n = PyInt_AsUnsignedLongMask(values[1]); if (unlikely((__pyx_v_n == (unsigned int)-1) && PyErr_Occurred())) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 149; __pyx_clineno = __LINE__; goto __pyx_L3_error;}
    if (values[2]) {
      __pyx_v_m = PyInt_AsUnsignedLongMask(values[2]); if (unlikely((__pyx_v_m == (unsigned int)-1) && PyErr_Occurred())) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 149; __pyx_clineno = __LINE__; goto __pyx_L3_error;}
    }
    if (values[3]) {
      __pyx_v_magic = PyInt_AsUnsignedLongMask(values[3]); if (unlikely((__pyx_v_magic == (unsigned long)-1) && PyErr_Occurred())) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 149; __pyx_clineno = __LINE__; goto __pyx_L3_error;}
    }
  } else {
    switch (PyTuple_GET_SIZE(__pyx_args)) {
      case  4:
      __pyx_v_magic = PyInt_AsUnsignedLongMask(PyTuple_GET_ITEM(__pyx_args, 3)); if (unlikely((__pyx_v_magic == (unsigned long)-1) && PyErr_Occurred())) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 149; __pyx_clineno = __LINE__; goto __pyx_L3_error;}
      case  3:
      __pyx_v_m = PyInt_AsUnsignedLongMask(PyTuple_GET_ITEM(__pyx_args, 2)); if (unlikely((__pyx_v_m == (unsigned int)-1) && PyErr_Occurred())) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 149; __pyx_clineno = __LINE__; goto __pyx_L3_error;}
      case  2:
      __pyx_v_n = PyInt_AsUnsignedLongMask(PyTuple_GET_ITEM(__pyx_args, 1)); if (unlikely((__pyx_v_n == (unsigned int)-1) && PyErr_Occurred())) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 149; __pyx_clineno = __LINE__; goto __pyx_L3_error;}
      __pyx_v_k = PyInt_AsUnsignedLongMask(PyTuple_GET_ITEM(__pyx_args, 0)); if (unlikely((__pyx_v_k == (unsigned int)-1) && PyErr_Occurred())) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 149; __pyx_clineno = __LINE__; goto __pyx_L3_error;}
      break;
      default: goto __pyx_L5_argtuple_error;
    }
  }
  goto __pyx_L4_argument_unpacking_done;
  __pyx_L5_argtuple_error:;
  __Pyx_RaiseArgtupleInvalid("combinations", 0, 2, 4, PyTuple_GET_SIZE(__pyx_args)); {__pyx_filename = __pyx_f[0]; __pyx_lineno = 149; __pyx_clineno = __LINE__; goto __pyx_L3_error;}
  __pyx_L3_error:;
  __Pyx_AddTraceback("neuroimaging.neurospin.utils.routines.combinations");
  return NULL;
  __pyx_L4_argument_unpacking_done:;
  __pyx_v_C = Py_None; Py_INCREF(Py_None);

  /* "d:\home\ar203069\bzr\nipy\dev-trunk-neurospin\neuroimaging\neurospin\utils\routines.pyx":157
 *     cdef fff_array pi_view
 *     cdef unsigned int i
 *     p = fff_array_new2d(FFF_UINT, k, m)             # <<<<<<<<<<<<<<
 *     pi = fff_array_new1d(FFF_UINT, k) ## contiguous, dims=(n,1,1,1)
 * 
 */
  __pyx_v_p = fff_array_new2d(FFF_UINT, __pyx_v_k, __pyx_v_m);

  /* "d:\home\ar203069\bzr\nipy\dev-trunk-neurospin\neuroimaging\neurospin\utils\routines.pyx":158
 *     cdef unsigned int i
 *     p = fff_array_new2d(FFF_UINT, k, m)
 *     pi = fff_array_new1d(FFF_UINT, k) ## contiguous, dims=(n,1,1,1)             # <<<<<<<<<<<<<<
 * 
 *     for i from 0 <= i < m:
 */
  __pyx_v_pi = fff_array_new1d(FFF_UINT, __pyx_v_k);

  /* "d:\home\ar203069\bzr\nipy\dev-trunk-neurospin\neuroimaging\neurospin\utils\routines.pyx":160
 *     pi = fff_array_new1d(FFF_UINT, k) ## contiguous, dims=(n,1,1,1)
 * 
 *     for i from 0 <= i < m:             # <<<<<<<<<<<<<<
 *         fff_combination(<unsigned int*>pi.data, k, n, magic+i)
 *         pi_view = fff_array_get_block2d(p, 0, k-1, 1, i, i, 1) ## dims=(k,1,1,1)
 */
  for (__pyx_v_i = 0; __pyx_v_i < __pyx_v_m; __pyx_v_i++) {

    /* "d:\home\ar203069\bzr\nipy\dev-trunk-neurospin\neuroimaging\neurospin\utils\routines.pyx":161
 * 
 *     for i from 0 <= i < m:
 *         fff_combination(<unsigned int*>pi.data, k, n, magic+i)             # <<<<<<<<<<<<<<
 *         pi_view = fff_array_get_block2d(p, 0, k-1, 1, i, i, 1) ## dims=(k,1,1,1)
 *         fff_array_copy(&pi_view, pi)
 */
    fff_combination(((unsigned int *)__pyx_v_pi->data), __pyx_v_k, __pyx_v_n, (__pyx_v_magic + __pyx_v_i));

    /* "d:\home\ar203069\bzr\nipy\dev-trunk-neurospin\neuroimaging\neurospin\utils\routines.pyx":162
 *     for i from 0 <= i < m:
 *         fff_combination(<unsigned int*>pi.data, k, n, magic+i)
 *         pi_view = fff_array_get_block2d(p, 0, k-1, 1, i, i, 1) ## dims=(k,1,1,1)             # <<<<<<<<<<<<<<
 *         fff_array_copy(&pi_view, pi)
 * 
 */
    __pyx_v_pi_view = fff_array_get_block2d(__pyx_v_p, 0, (__pyx_v_k - 1), 1, __pyx_v_i, __pyx_v_i, 1);

    /* "d:\home\ar203069\bzr\nipy\dev-trunk-neurospin\neuroimaging\neurospin\utils\routines.pyx":163
 *         fff_combination(<unsigned int*>pi.data, k, n, magic+i)
 *         pi_view = fff_array_get_block2d(p, 0, k-1, 1, i, i, 1) ## dims=(k,1,1,1)
 *         fff_array_copy(&pi_view, pi)             # <<<<<<<<<<<<<<
 * 
 *     C = fff_array_toPyArray(p)
 */
    fff_array_copy((&__pyx_v_pi_view), __pyx_v_pi);
  }

  /* "d:\home\ar203069\bzr\nipy\dev-trunk-neurospin\neuroimaging\neurospin\utils\routines.pyx":165
 *         fff_array_copy(&pi_view, pi)
 * 
 *     C = fff_array_toPyArray(p)             # <<<<<<<<<<<<<<
 *     return C
 * 
 */
  __pyx_1 = ((PyObject *)fff_array_toPyArray(__pyx_v_p)); if (unlikely(!__pyx_1)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 165; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
  Py_DECREF(__pyx_v_C);
  __pyx_v_C = __pyx_1;
  __pyx_1 = 0;

  /* "d:\home\ar203069\bzr\nipy\dev-trunk-neurospin\neuroimaging\neurospin\utils\routines.pyx":166
 * 
 *     C = fff_array_toPyArray(p)
 *     return C             # <<<<<<<<<<<<<<
 * 
 * 
 */
  Py_INCREF(__pyx_v_C);
  __pyx_r = __pyx_v_C;
  goto __pyx_L0;

  __pyx_r = Py_None; Py_INCREF(Py_None);
  goto __pyx_L0;
  __pyx_L1_error:;
  Py_XDECREF(__pyx_1);
  __Pyx_AddTraceback("neuroimaging.neurospin.utils.routines.combinations");
  __pyx_r = NULL;
  __pyx_L0:;
  Py_DECREF(__pyx_v_C);
  return __pyx_r;
}

/* "d:\home\ar203069\bzr\nipy\dev-trunk-neurospin\neuroimaging\neurospin\utils\routines.pyx":169
 * 
 * 
 * def gamln(double x):             # <<<<<<<<<<<<<<
 *     """ Python bindings to log gamma. Do not use, this is there only for
 *         testing. Use scipy.special.gammaln.
 */

static PyObject *__pyx_pf_12neuroimaging_9neurospin_5utils_8routines_gamln(PyObject *__pyx_self, PyObject *__pyx_arg_x); /*proto*/
static char __pyx_doc_12neuroimaging_9neurospin_5utils_8routines_gamln[] = " Python bindings to log gamma. Do not use, this is there only for\n        testing. Use scipy.special.gammaln.\n    ";
static PyObject *__pyx_pf_12neuroimaging_9neurospin_5utils_8routines_gamln(PyObject *__pyx_self, PyObject *__pyx_arg_x) {
  double __pyx_v_x;
  double __pyx_v_y;
  PyObject *__pyx_r;
  PyObject *__pyx_1 = 0;
  __pyx_self = __pyx_self;
  assert(__pyx_arg_x); {
    __pyx_v_x = __pyx_PyFloat_AsDouble(__pyx_arg_x); if (unlikely(PyErr_Occurred())) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 169; __pyx_clineno = __LINE__; goto __pyx_L3_error;}
  }
  goto __pyx_L4_argument_unpacking_done;
  __pyx_L3_error:;
  __Pyx_AddTraceback("neuroimaging.neurospin.utils.routines.gamln");
  return NULL;
  __pyx_L4_argument_unpacking_done:;

  /* "d:\home\ar203069\bzr\nipy\dev-trunk-neurospin\neuroimaging\neurospin\utils\routines.pyx":174
 *     """
 *     cdef double y
 *     y = fff_gamln(x)             # <<<<<<<<<<<<<<
 *     return y
 * 
 */
  __pyx_v_y = fff_gamln(__pyx_v_x);

  /* "d:\home\ar203069\bzr\nipy\dev-trunk-neurospin\neuroimaging\neurospin\utils\routines.pyx":175
 *     cdef double y
 *     y = fff_gamln(x)
 *     return y             # <<<<<<<<<<<<<<
 * 
 * 
 */
  __pyx_1 = PyFloat_FromDouble(__pyx_v_y); if (unlikely(!__pyx_1)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 175; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
  __pyx_r = __pyx_1;
  __pyx_1 = 0;
  goto __pyx_L0;

  __pyx_r = Py_None; Py_INCREF(Py_None);
  goto __pyx_L0;
  __pyx_L1_error:;
  Py_XDECREF(__pyx_1);
  __Pyx_AddTraceback("neuroimaging.neurospin.utils.routines.gamln");
  __pyx_r = NULL;
  __pyx_L0:;
  return __pyx_r;
}

/* "d:\home\ar203069\bzr\nipy\dev-trunk-neurospin\neuroimaging\neurospin\utils\routines.pyx":178
 * 
 * 
 * def psi(double x):             # <<<<<<<<<<<<<<
 *     """ Python bindings to psi (d gamln(x)/dx. Do not use, this is there only
 *         for testing. Use scipy.special.psi.
 */

static PyObject *__pyx_pf_12neuroimaging_9neurospin_5utils_8routines_psi(PyObject *__pyx_self, PyObject *__pyx_arg_x); /*proto*/
static char __pyx_doc_12neuroimaging_9neurospin_5utils_8routines_psi[] = " Python bindings to psi (d gamln(x)/dx. Do not use, this is there only \n        for testing. Use scipy.special.psi.\n    ";
static PyObject *__pyx_pf_12neuroimaging_9neurospin_5utils_8routines_psi(PyObject *__pyx_self, PyObject *__pyx_arg_x) {
  double __pyx_v_x;
  double __pyx_v_y;
  PyObject *__pyx_r;
  PyObject *__pyx_1 = 0;
  __pyx_self = __pyx_self;
  assert(__pyx_arg_x); {
    __pyx_v_x = __pyx_PyFloat_AsDouble(__pyx_arg_x); if (unlikely(PyErr_Occurred())) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 178; __pyx_clineno = __LINE__; goto __pyx_L3_error;}
  }
  goto __pyx_L4_argument_unpacking_done;
  __pyx_L3_error:;
  __Pyx_AddTraceback("neuroimaging.neurospin.utils.routines.psi");
  return NULL;
  __pyx_L4_argument_unpacking_done:;

  /* "d:\home\ar203069\bzr\nipy\dev-trunk-neurospin\neuroimaging\neurospin\utils\routines.pyx":183
 *     """
 *     cdef double y
 *     y = fff_psi(x)             # <<<<<<<<<<<<<<
 *     return y
 * 
 */
  __pyx_v_y = fff_psi(__pyx_v_x);

  /* "d:\home\ar203069\bzr\nipy\dev-trunk-neurospin\neuroimaging\neurospin\utils\routines.pyx":184
 *     cdef double y
 *     y = fff_psi(x)
 *     return y             # <<<<<<<<<<<<<<
 * 
 */
  __pyx_1 = PyFloat_FromDouble(__pyx_v_y); if (unlikely(!__pyx_1)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 184; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
  __pyx_r = __pyx_1;
  __pyx_1 = 0;
  goto __pyx_L0;

  __pyx_r = Py_None; Py_INCREF(Py_None);
  goto __pyx_L0;
  __pyx_L1_error:;
  Py_XDECREF(__pyx_1);
  __Pyx_AddTraceback("neuroimaging.neurospin.utils.routines.psi");
  __pyx_r = NULL;
  __pyx_L0:;
  return __pyx_r;
}

static struct PyMethodDef __pyx_methods[] = {
  {"quantile", (PyCFunction)__pyx_pf_12neuroimaging_9neurospin_5utils_8routines_quantile, METH_VARARGS|METH_KEYWORDS, __pyx_doc_12neuroimaging_9neurospin_5utils_8routines_quantile},
  {"median", (PyCFunction)__pyx_pf_12neuroimaging_9neurospin_5utils_8routines_median, METH_VARARGS|METH_KEYWORDS, __pyx_doc_12neuroimaging_9neurospin_5utils_8routines_median},
  {"mahalanobis", (PyCFunction)__pyx_pf_12neuroimaging_9neurospin_5utils_8routines_mahalanobis, METH_VARARGS|METH_KEYWORDS, __pyx_doc_12neuroimaging_9neurospin_5utils_8routines_mahalanobis},
  {"permutations", (PyCFunction)__pyx_pf_12neuroimaging_9neurospin_5utils_8routines_permutations, METH_VARARGS|METH_KEYWORDS, __pyx_doc_12neuroimaging_9neurospin_5utils_8routines_permutations},
  {"combinations", (PyCFunction)__pyx_pf_12neuroimaging_9neurospin_5utils_8routines_combinations, METH_VARARGS|METH_KEYWORDS, __pyx_doc_12neuroimaging_9neurospin_5utils_8routines_combinations},
  {"gamln", (PyCFunction)__pyx_pf_12neuroimaging_9neurospin_5utils_8routines_gamln, METH_O, __pyx_doc_12neuroimaging_9neurospin_5utils_8routines_gamln},
  {"psi", (PyCFunction)__pyx_pf_12neuroimaging_9neurospin_5utils_8routines_psi, METH_O, __pyx_doc_12neuroimaging_9neurospin_5utils_8routines_psi},
  {0, 0, 0, 0}
};

static void __pyx_init_filenames(void); /*proto*/

#if PY_MAJOR_VERSION >= 3
static struct PyModuleDef __pyx_moduledef = {
    PyModuleDef_HEAD_INIT,
    "routines",
    __pyx_mdoc, /* m_doc */
    -1, /* m_size */
    __pyx_methods /* m_methods */,
    NULL, /* m_reload */
    NULL, /* m_traverse */
    NULL, /* m_clear */
    NULL /* m_free */
};
#endif

static __Pyx_StringTabEntry __pyx_string_tab[] = {
  {&__pyx_kp_X, __pyx_k_X, sizeof(__pyx_k_X), 1, 1, 1},
  {&__pyx_kp_ratio, __pyx_k_ratio, sizeof(__pyx_k_ratio), 1, 1, 1},
  {&__pyx_kp_interp, __pyx_k_interp, sizeof(__pyx_k_interp), 1, 1, 1},
  {&__pyx_kp_axis, __pyx_k_axis, sizeof(__pyx_k_axis), 1, 1, 1},
  {&__pyx_kp_x, __pyx_k_x, sizeof(__pyx_k_x), 1, 1, 1},
  {&__pyx_kp_VX, __pyx_k_VX, sizeof(__pyx_k_VX), 1, 1, 1},
  {&__pyx_kp_n, __pyx_k_n, sizeof(__pyx_k_n), 1, 1, 1},
  {&__pyx_kp_m, __pyx_k_m, sizeof(__pyx_k_m), 1, 1, 1},
  {&__pyx_kp_magic, __pyx_k_magic, sizeof(__pyx_k_magic), 1, 1, 1},
  {&__pyx_kp_k, __pyx_k_k, sizeof(__pyx_k_k), 1, 1, 1},
  {&__pyx_kp___version__, __pyx_k___version__, sizeof(__pyx_k___version__), 1, 1, 1},
  {&__pyx_kp_numpy, __pyx_k_numpy, sizeof(__pyx_k_numpy), 1, 1, 1},
  {&__pyx_kp_np, __pyx_k_np, sizeof(__pyx_k_np), 0, 1, 1},
  {&__pyx_kp_shape, __pyx_k_shape, sizeof(__pyx_k_shape), 1, 1, 1},
  {&__pyx_kp_zeros, __pyx_k_zeros, sizeof(__pyx_k_zeros), 1, 1, 1},
  {&__pyx_kp_quantile, __pyx_k_quantile, sizeof(__pyx_k_quantile), 1, 1, 1},
  {&__pyx_kp_reshape, __pyx_k_reshape, sizeof(__pyx_k_reshape), 1, 1, 1},
  {&__pyx_kp_1, __pyx_k_1, sizeof(__pyx_k_1), 0, 0, 0},
  {0, 0, 0, 0, 0, 0}
};
static int __Pyx_InitCachedBuiltins(void) {
  return 0;
  return -1;
}

static int __Pyx_InitGlobals(void) {
  __pyx_int_0 = PyInt_FromLong(0); if (unlikely(!__pyx_int_0)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 1; __pyx_clineno = __LINE__; goto __pyx_L1_error;};
  __pyx_int_1 = PyInt_FromLong(1); if (unlikely(!__pyx_int_1)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 1; __pyx_clineno = __LINE__; goto __pyx_L1_error;};
  if (__Pyx_InitStrings(__pyx_string_tab) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 1; __pyx_clineno = __LINE__; goto __pyx_L1_error;};
  return 0;
  __pyx_L1_error:;
  return -1;
}

#if PY_MAJOR_VERSION < 3
PyMODINIT_FUNC initroutines(void); /*proto*/
PyMODINIT_FUNC initroutines(void)
#else
PyMODINIT_FUNC PyInit_routines(void); /*proto*/
PyMODINIT_FUNC PyInit_routines(void)
#endif
{
  PyObject *__pyx_1 = 0;
  __pyx_empty_tuple = PyTuple_New(0); if (unlikely(!__pyx_empty_tuple)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 1; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
  /*--- Library function declarations ---*/
  __pyx_init_filenames();
  /*--- Initialize various global constants etc. ---*/
  if (unlikely(__Pyx_InitGlobals() < 0)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 1; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
  /*--- Module creation code ---*/
  #if PY_MAJOR_VERSION < 3
  __pyx_m = Py_InitModule4("routines", __pyx_methods, __pyx_mdoc, 0, PYTHON_API_VERSION);
  #else
  __pyx_m = PyModule_Create(&__pyx_moduledef);
  #endif
  if (!__pyx_m) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 1; __pyx_clineno = __LINE__; goto __pyx_L1_error;};
  #if PY_MAJOR_VERSION < 3
  Py_INCREF(__pyx_m);
  #endif
  __pyx_b = PyImport_AddModule(__Pyx_BUILTIN_MODULE_NAME);
  if (!__pyx_b) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 1; __pyx_clineno = __LINE__; goto __pyx_L1_error;};
  if (PyObject_SetAttrString(__pyx_m, "__builtins__", __pyx_b) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 1; __pyx_clineno = __LINE__; goto __pyx_L1_error;};
  /*--- Builtin init code ---*/
  if (unlikely(__Pyx_InitCachedBuiltins() < 0)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 1; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
  __pyx_skip_dispatch = 0;
  /*--- Global init code ---*/
  /*--- Function export code ---*/
  /*--- Type init code ---*/
  __pyx_ptype_12neuroimaging_9neurospin_5utils_8routines_dtype = __Pyx_ImportType("numpy", "dtype", sizeof(PyArray_Descr)); if (unlikely(!__pyx_ptype_12neuroimaging_9neurospin_5utils_8routines_dtype)) {__pyx_filename = __pyx_f[1]; __pyx_lineno = 74; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
  __pyx_ptype_12neuroimaging_9neurospin_5utils_8routines_ndarray = __Pyx_ImportType("numpy", "ndarray", sizeof(PyArrayObject)); if (unlikely(!__pyx_ptype_12neuroimaging_9neurospin_5utils_8routines_ndarray)) {__pyx_filename = __pyx_f[1]; __pyx_lineno = 79; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
  __pyx_ptype_12neuroimaging_9neurospin_5utils_8routines_flatiter = __Pyx_ImportType("numpy", "flatiter", sizeof(PyArrayIterObject)); if (unlikely(!__pyx_ptype_12neuroimaging_9neurospin_5utils_8routines_flatiter)) {__pyx_filename = __pyx_f[1]; __pyx_lineno = 88; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
  __pyx_ptype_12neuroimaging_9neurospin_5utils_8routines_broadcast = __Pyx_ImportType("numpy", "broadcast", sizeof(PyArrayMultiIterObject)); if (unlikely(!__pyx_ptype_12neuroimaging_9neurospin_5utils_8routines_broadcast)) {__pyx_filename = __pyx_f[1]; __pyx_lineno = 94; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
  /*--- Type import code ---*/
  /*--- Function import code ---*/
  /*--- Execution code ---*/

  /* "d:\home\ar203069\bzr\nipy\dev-trunk-neurospin\neuroimaging\neurospin\utils\routines.pyx":9
 * """
 * 
 * __version__ = '0.1'             # <<<<<<<<<<<<<<
 * 
 * # Includes from the python headers
 */
  if (PyObject_SetAttr(__pyx_m, __pyx_kp___version__, __pyx_kp_1) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 9; __pyx_clineno = __LINE__; goto __pyx_L1_error;}

  /* "d:\home\ar203069\bzr\nipy\dev-trunk-neurospin\neuroimaging\neurospin\utils\routines.pyx":32
 * 
 * # Initialize numpy
 * fffpy_import_array()             # <<<<<<<<<<<<<<
 * import_array()
 * import numpy as np
 */
  fffpy_import_array();

  /* "d:\home\ar203069\bzr\nipy\dev-trunk-neurospin\neuroimaging\neurospin\utils\routines.pyx":33
 * # Initialize numpy
 * fffpy_import_array()
 * import_array()             # <<<<<<<<<<<<<<
 * import numpy as np
 * 
 */
  import_array();

  /* "d:\home\ar203069\bzr\nipy\dev-trunk-neurospin\neuroimaging\neurospin\utils\routines.pyx":34
 * fffpy_import_array()
 * import_array()
 * import numpy as np             # <<<<<<<<<<<<<<
 * 
 * # FIXME: Check that this is faster than scipy.stats.scoreatpercentile
 */
  __pyx_1 = __Pyx_Import(__pyx_kp_numpy, 0); if (unlikely(!__pyx_1)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 34; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
  if (PyObject_SetAttr(__pyx_m, __pyx_kp_np, __pyx_1) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 34; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
  Py_DECREF(__pyx_1); __pyx_1 = 0;

  /* "d:\home\ar203069\bzr\nipy\dev-trunk-neurospin\neuroimaging\neurospin\utils\routines.pyx":178
 * 
 * 
 * def psi(double x):             # <<<<<<<<<<<<<<
 *     """ Python bindings to psi (d gamln(x)/dx. Do not use, this is there only
 *         for testing. Use scipy.special.psi.
 */
  #if PY_MAJOR_VERSION < 3
  return;
  #else
  return __pyx_m;
  #endif
  __pyx_L1_error:;
  Py_XDECREF(__pyx_1);
  __Pyx_AddTraceback("neuroimaging.neurospin.utils.routines");
  #if PY_MAJOR_VERSION >= 3
  return NULL;
  #endif
}

static const char *__pyx_filenames[] = {
  "routines.pyx",
  "numpy.pxi",
};

/* Runtime support code */

static void __pyx_init_filenames(void) {
  __pyx_f = __pyx_filenames;
}

static void __Pyx_RaiseDoubleKeywordsError(
    const char* func_name,
    PyObject* kw_name)
{
    PyErr_Format(PyExc_TypeError,
        #if PY_MAJOR_VERSION >= 3
        "%s() got multiple values for keyword argument '%U'", func_name, kw_name);
        #else
        "%s() got multiple values for keyword argument '%s'", func_name,
        PyString_AS_STRING(kw_name));
        #endif
}

static void __Pyx_RaiseArgtupleInvalid(
    const char* func_name,
    int exact,
    Py_ssize_t num_min,
    Py_ssize_t num_max,
    Py_ssize_t num_found)
{
    Py_ssize_t num_expected;
    const char *number, *more_or_less;

    if (num_found < num_min) {
        num_expected = num_min;
        more_or_less = "at least";
    } else {
        num_expected = num_max;
        more_or_less = "at most";
    }
    if (exact) {
        more_or_less = "exactly";
    }
    number = (num_expected == 1) ? "" : "s";
    PyErr_Format(PyExc_TypeError,
        #if PY_VERSION_HEX < 0x02050000
            "%s() takes %s %d positional argument%s (%d given)",
        #else
            "%s() takes %s %zd positional argument%s (%zd given)",
        #endif
        func_name, more_or_less, num_expected, number, num_found);
}

static int __Pyx_ParseOptionalKeywords(
    PyObject *kwds,
    PyObject **argnames[],
    PyObject *kwds2,
    PyObject *values[],
    Py_ssize_t num_pos_args,
    const char* function_name)
{
    PyObject *key = 0, *value = 0;
    Py_ssize_t pos = 0;
    PyObject*** name;
    PyObject*** first_kw_arg = argnames + num_pos_args;

    while (PyDict_Next(kwds, &pos, &key, &value)) {
        #if PY_MAJOR_VERSION < 3
        if (unlikely(!PyString_CheckExact(key)) && unlikely(!PyString_Check(key))) {
        #else
        if (unlikely(!PyUnicode_CheckExact(key)) && unlikely(!PyUnicode_Check(key))) {
        #endif
            goto invalid_keyword_type;
        } else {
            name = argnames;
            while (*name && (**name != key)) name++;
            if (*name) {
                if (name < first_kw_arg) goto arg_passed_twice;
                values[name-argnames] = value;
            } else {
                for (name = first_kw_arg; *name; name++) {
                    #if PY_MAJOR_VERSION >= 3
                    if (PyUnicode_GET_SIZE(**name) == PyUnicode_GET_SIZE(key) &&
                        PyUnicode_Compare(**name, key) == 0) break;
                    #else
                    if (PyString_GET_SIZE(**name) == PyString_GET_SIZE(key) &&
                        strcmp(PyString_AS_STRING(**name),
                               PyString_AS_STRING(key)) == 0) break;
                    #endif
                }
                if (*name) {
                    values[name-argnames] = value;
                } else {
                    /* unexpected keyword found */
                    for (name=argnames; name != first_kw_arg; name++) {
                        if (**name == key) goto arg_passed_twice;
                        #if PY_MAJOR_VERSION >= 3
                        if (PyUnicode_GET_SIZE(**name) == PyUnicode_GET_SIZE(key) &&
                            PyUnicode_Compare(**name, key) == 0) goto arg_passed_twice;
                        #else
                        if (PyString_GET_SIZE(**name) == PyString_GET_SIZE(key) &&
                            strcmp(PyString_AS_STRING(**name),
                                   PyString_AS_STRING(key)) == 0) goto arg_passed_twice;
                        #endif
                    }
                    if (kwds2) {
                        if (unlikely(PyDict_SetItem(kwds2, key, value))) goto bad;
                    } else {
                        goto invalid_keyword;
                    }
                }
            }
        }
    }
    return 0;
arg_passed_twice:
    __Pyx_RaiseDoubleKeywordsError(function_name, **name);
    goto bad;
invalid_keyword_type:
    PyErr_Format(PyExc_TypeError,
        "%s() keywords must be strings", function_name);
    goto bad;
invalid_keyword:
    PyErr_Format(PyExc_TypeError,
    #if PY_MAJOR_VERSION < 3
        "%s() got an unexpected keyword argument '%s'",
        function_name, PyString_AsString(key));
    #else
        "%s() got an unexpected keyword argument '%U'",
        function_name, key);
    #endif
bad:
    return -1;
}



static PyObject *__Pyx_Import(PyObject *name, PyObject *from_list) {
    PyObject *__import__ = 0;
    PyObject *empty_list = 0;
    PyObject *module = 0;
    PyObject *global_dict = 0;
    PyObject *empty_dict = 0;
    PyObject *list;
    __import__ = PyObject_GetAttrString(__pyx_b, "__import__");
    if (!__import__)
        goto bad;
    if (from_list)
        list = from_list;
    else {
        empty_list = PyList_New(0);
        if (!empty_list)
            goto bad;
        list = empty_list;
    }
    global_dict = PyModule_GetDict(__pyx_m);
    if (!global_dict)
        goto bad;
    empty_dict = PyDict_New();
    if (!empty_dict)
        goto bad;
    module = PyObject_CallFunction(__import__, "OOOO",
        name, global_dict, empty_dict, list);
bad:
    Py_XDECREF(empty_list);
    Py_XDECREF(__import__);
    Py_XDECREF(empty_dict);
    return module;
}

static PyObject *__Pyx_GetName(PyObject *dict, PyObject *name) {
    PyObject *result;
    result = PyObject_GetAttr(dict, name);
    if (!result)
        PyErr_SetObject(PyExc_NameError, name);
    return result;
}

#ifndef __PYX_HAVE_RT_ImportType
#define __PYX_HAVE_RT_ImportType
static PyTypeObject *__Pyx_ImportType(const char *module_name, const char *class_name,
    long size)
{
    PyObject *py_module = 0;
    PyObject *result = 0;
    PyObject *py_name = 0;

    py_module = __Pyx_ImportModule(module_name);
    if (!py_module)
        goto bad;
    #if PY_MAJOR_VERSION < 3
    py_name = PyString_FromString(class_name);
    #else
    py_name = PyUnicode_FromString(class_name);
    #endif
    if (!py_name)
        goto bad;
    result = PyObject_GetAttr(py_module, py_name);
    Py_DECREF(py_name);
    py_name = 0;
    Py_DECREF(py_module);
    py_module = 0;
    if (!result)
        goto bad;
    if (!PyType_Check(result)) {
        PyErr_Format(PyExc_TypeError, 
            "%s.%s is not a type object",
            module_name, class_name);
        goto bad;
    }
    if (((PyTypeObject *)result)->tp_basicsize != size) {
        PyErr_Format(PyExc_ValueError, 
            "%s.%s does not appear to be the correct type object",
            module_name, class_name);
        goto bad;
    }
    return (PyTypeObject *)result;
bad:
    Py_XDECREF(py_module);
    Py_XDECREF(result);
    return 0;
}
#endif

#ifndef __PYX_HAVE_RT_ImportModule
#define __PYX_HAVE_RT_ImportModule
static PyObject *__Pyx_ImportModule(const char *name) {
    PyObject *py_name = 0;
    PyObject *py_module = 0;

    #if PY_MAJOR_VERSION < 3
    py_name = PyString_FromString(name);
    #else
    py_name = PyUnicode_FromString(name);
    #endif
    if (!py_name)
        goto bad;
    py_module = PyImport_Import(py_name);
    Py_DECREF(py_name);
    return py_module;
bad:
    Py_XDECREF(py_name);
    return 0;
}
#endif

#include "compile.h"
#include "frameobject.h"
#include "traceback.h"

static void __Pyx_AddTraceback(const char *funcname) {
    PyObject *py_srcfile = 0;
    PyObject *py_funcname = 0;
    PyObject *py_globals = 0;
    PyObject *empty_string = 0;
    PyCodeObject *py_code = 0;
    PyFrameObject *py_frame = 0;

    #if PY_MAJOR_VERSION < 3
    py_srcfile = PyString_FromString(__pyx_filename);
    #else
    py_srcfile = PyUnicode_FromString(__pyx_filename);
    #endif
    if (!py_srcfile) goto bad;
    if (__pyx_clineno) {
        #if PY_MAJOR_VERSION < 3
        py_funcname = PyString_FromFormat( "%s (%s:%d)", funcname, __pyx_cfilenm, __pyx_clineno);
        #else
        py_funcname = PyUnicode_FromFormat( "%s (%s:%d)", funcname, __pyx_cfilenm, __pyx_clineno);
        #endif
    }
    else {
        #if PY_MAJOR_VERSION < 3
        py_funcname = PyString_FromString(funcname);
        #else
        py_funcname = PyUnicode_FromString(funcname);
        #endif
    }
    if (!py_funcname) goto bad;
    py_globals = PyModule_GetDict(__pyx_m);
    if (!py_globals) goto bad;
    #if PY_MAJOR_VERSION < 3
    empty_string = PyString_FromStringAndSize("", 0);
    #else
    empty_string = PyBytes_FromStringAndSize("", 0);
    #endif
    if (!empty_string) goto bad;
    py_code = PyCode_New(
        0,            /*int argcount,*/
        #if PY_MAJOR_VERSION >= 3
        0,            /*int kwonlyargcount,*/
        #endif
        0,            /*int nlocals,*/
        0,            /*int stacksize,*/
        0,            /*int flags,*/
        empty_string, /*PyObject *code,*/
        __pyx_empty_tuple,  /*PyObject *consts,*/
        __pyx_empty_tuple,  /*PyObject *names,*/
        __pyx_empty_tuple,  /*PyObject *varnames,*/
        __pyx_empty_tuple,  /*PyObject *freevars,*/
        __pyx_empty_tuple,  /*PyObject *cellvars,*/
        py_srcfile,   /*PyObject *filename,*/
        py_funcname,  /*PyObject *name,*/
        __pyx_lineno,   /*int firstlineno,*/
        empty_string  /*PyObject *lnotab*/
    );
    if (!py_code) goto bad;
    py_frame = PyFrame_New(
        PyThreadState_GET(), /*PyThreadState *tstate,*/
        py_code,             /*PyCodeObject *code,*/
        py_globals,          /*PyObject *globals,*/
        0                    /*PyObject *locals*/
    );
    if (!py_frame) goto bad;
    py_frame->f_lineno = __pyx_lineno;
    PyTraceBack_Here(py_frame);
bad:
    Py_XDECREF(py_srcfile);
    Py_XDECREF(py_funcname);
    Py_XDECREF(empty_string);
    Py_XDECREF(py_code);
    Py_XDECREF(py_frame);
}

static int __Pyx_InitStrings(__Pyx_StringTabEntry *t) {
    while (t->p) {
        #if PY_MAJOR_VERSION < 3
        if (t->is_unicode && (!t->is_identifier)) {
            *t->p = PyUnicode_DecodeUTF8(t->s, t->n - 1, NULL);
        } else if (t->intern) {
            *t->p = PyString_InternFromString(t->s);
        } else {
            *t->p = PyString_FromStringAndSize(t->s, t->n - 1);
        }
        #else  /* Python 3+ has unicode identifiers */
        if (t->is_identifier || (t->is_unicode && t->intern)) {
            *t->p = PyUnicode_InternFromString(t->s);
        } else if (t->is_unicode) {
            *t->p = PyUnicode_FromStringAndSize(t->s, t->n - 1);
        } else {
            *t->p = PyBytes_FromStringAndSize(t->s, t->n - 1);
        }
        #endif
        if (!*t->p)
            return -1;
        ++t;
    }
    return 0;
}

/* Type Conversion Functions */

static INLINE Py_ssize_t __pyx_PyIndex_AsSsize_t(PyObject* b) {
  Py_ssize_t ival;
  PyObject* x = PyNumber_Index(b);
  if (!x) return -1;
  ival = PyInt_AsSsize_t(x);
  Py_DECREF(x);
  return ival;
}

static INLINE int __Pyx_PyObject_IsTrue(PyObject* x) {
   if (x == Py_True) return 1;
   else if (x == Py_False) return 0;
   else return PyObject_IsTrue(x);
}

static INLINE PY_LONG_LONG __pyx_PyInt_AsLongLong(PyObject* x) {
    if (PyInt_CheckExact(x)) {
        return PyInt_AS_LONG(x);
    }
    else if (PyLong_CheckExact(x)) {
        return PyLong_AsLongLong(x);
    }
    else {
        PY_LONG_LONG val;
        PyObject* tmp = PyNumber_Int(x); if (!tmp) return (PY_LONG_LONG)-1;
        val = __pyx_PyInt_AsLongLong(tmp);
        Py_DECREF(tmp);
        return val;
    }
}

static INLINE unsigned PY_LONG_LONG __pyx_PyInt_AsUnsignedLongLong(PyObject* x) {
    if (PyInt_CheckExact(x)) {
        long val = PyInt_AS_LONG(x);
        if (unlikely(val < 0)) {
            PyErr_SetString(PyExc_TypeError, "Negative assignment to unsigned type.");
            return (unsigned PY_LONG_LONG)-1;
        }
        return val;
    }
    else if (PyLong_CheckExact(x)) {
        return PyLong_AsUnsignedLongLong(x);
    }
    else {
        PY_LONG_LONG val;
        PyObject* tmp = PyNumber_Int(x); if (!tmp) return (PY_LONG_LONG)-1;
        val = __pyx_PyInt_AsUnsignedLongLong(tmp);
        Py_DECREF(tmp);
        return val;
    }
}


static INLINE unsigned char __pyx_PyInt_unsigned_char(PyObject* x) {
    if (sizeof(unsigned char) < sizeof(long)) {
        long long_val = __pyx_PyInt_AsLong(x);
        unsigned char val = (unsigned char)long_val;
        if (unlikely((val != long_val)  || (long_val < 0))) {
            PyErr_SetString(PyExc_OverflowError, "value too large to convert to unsigned char");
            return (unsigned char)-1;
        }
        return val;
    }
    else {
        return __pyx_PyInt_AsLong(x);
    }
}

static INLINE unsigned short __pyx_PyInt_unsigned_short(PyObject* x) {
    if (sizeof(unsigned short) < sizeof(long)) {
        long long_val = __pyx_PyInt_AsLong(x);
        unsigned short val = (unsigned short)long_val;
        if (unlikely((val != long_val)  || (long_val < 0))) {
            PyErr_SetString(PyExc_OverflowError, "value too large to convert to unsigned short");
            return (unsigned short)-1;
        }
        return val;
    }
    else {
        return __pyx_PyInt_AsLong(x);
    }
}

static INLINE char __pyx_PyInt_char(PyObject* x) {
    if (sizeof(char) < sizeof(long)) {
        long long_val = __pyx_PyInt_AsLong(x);
        char val = (char)long_val;
        if (unlikely((val != long_val) )) {
            PyErr_SetString(PyExc_OverflowError, "value too large to convert to char");
            return (char)-1;
        }
        return val;
    }
    else {
        return __pyx_PyInt_AsLong(x);
    }
}

static INLINE short __pyx_PyInt_short(PyObject* x) {
    if (sizeof(short) < sizeof(long)) {
        long long_val = __pyx_PyInt_AsLong(x);
        short val = (short)long_val;
        if (unlikely((val != long_val) )) {
            PyErr_SetString(PyExc_OverflowError, "value too large to convert to short");
            return (short)-1;
        }
        return val;
    }
    else {
        return __pyx_PyInt_AsLong(x);
    }
}

static INLINE int __pyx_PyInt_int(PyObject* x) {
    if (sizeof(int) < sizeof(long)) {
        long long_val = __pyx_PyInt_AsLong(x);
        int val = (int)long_val;
        if (unlikely((val != long_val) )) {
            PyErr_SetString(PyExc_OverflowError, "value too large to convert to int");
            return (int)-1;
        }
        return val;
    }
    else {
        return __pyx_PyInt_AsLong(x);
    }
}

static INLINE long __pyx_PyInt_long(PyObject* x) {
    if (sizeof(long) < sizeof(long)) {
        long long_val = __pyx_PyInt_AsLong(x);
        long val = (long)long_val;
        if (unlikely((val != long_val) )) {
            PyErr_SetString(PyExc_OverflowError, "value too large to convert to long");
            return (long)-1;
        }
        return val;
    }
    else {
        return __pyx_PyInt_AsLong(x);
    }
}

static INLINE signed char __pyx_PyInt_signed_char(PyObject* x) {
    if (sizeof(signed char) < sizeof(long)) {
        long long_val = __pyx_PyInt_AsLong(x);
        signed char val = (signed char)long_val;
        if (unlikely((val != long_val) )) {
            PyErr_SetString(PyExc_OverflowError, "value too large to convert to signed char");
            return (signed char)-1;
        }
        return val;
    }
    else {
        return __pyx_PyInt_AsLong(x);
    }
}

static INLINE signed short __pyx_PyInt_signed_short(PyObject* x) {
    if (sizeof(signed short) < sizeof(long)) {
        long long_val = __pyx_PyInt_AsLong(x);
        signed short val = (signed short)long_val;
        if (unlikely((val != long_val) )) {
            PyErr_SetString(PyExc_OverflowError, "value too large to convert to signed short");
            return (signed short)-1;
        }
        return val;
    }
    else {
        return __pyx_PyInt_AsLong(x);
    }
}

static INLINE signed int __pyx_PyInt_signed_int(PyObject* x) {
    if (sizeof(signed int) < sizeof(long)) {
        long long_val = __pyx_PyInt_AsLong(x);
        signed int val = (signed int)long_val;
        if (unlikely((val != long_val) )) {
            PyErr_SetString(PyExc_OverflowError, "value too large to convert to signed int");
            return (signed int)-1;
        }
        return val;
    }
    else {
        return __pyx_PyInt_AsLong(x);
    }
}

static INLINE signed long __pyx_PyInt_signed_long(PyObject* x) {
    if (sizeof(signed long) < sizeof(long)) {
        long long_val = __pyx_PyInt_AsLong(x);
        signed long val = (signed long)long_val;
        if (unlikely((val != long_val) )) {
            PyErr_SetString(PyExc_OverflowError, "value too large to convert to signed long");
            return (signed long)-1;
        }
        return val;
    }
    else {
        return __pyx_PyInt_AsLong(x);
    }
}

static INLINE long double __pyx_PyInt_long_double(PyObject* x) {
    if (sizeof(long double) < sizeof(long)) {
        long long_val = __pyx_PyInt_AsLong(x);
        long double val = (long double)long_val;
        if (unlikely((val != long_val) )) {
            PyErr_SetString(PyExc_OverflowError, "value too large to convert to long double");
            return (long double)-1;
        }
        return val;
    }
    else {
        return __pyx_PyInt_AsLong(x);
    }
}

